ALTER TABLE [cqm2019].[DoctorCQMCalcPop1CMS68v8_NQF0419] WITH CHECK ADD CONSTRAINT [FK_DoctorCQMCalcPop1CMS68v8_NQF0419_doctors]
   FOREIGN KEY([DoctorId]) REFERENCES [dbo].[doctors] ([dr_id])

GO
ALTER TABLE [cqm2019].[DoctorCQMCalcPop1CMS68v8_NQF0419] WITH CHECK ADD CONSTRAINT [FK_DoctorCQMCalcPop1CMS68v8_NQF0419_patients]
   FOREIGN KEY([PatientId]) REFERENCES [dbo].[patients] ([pa_id])

GO
ALTER TABLE [cqm2019].[DoctorCQMCalcPop1CMS68v8_NQF0419] WITH CHECK ADD CONSTRAINT [FK_DoctorCQMCalcPop1CMS68v8_NQF0419_DoctorCQMCalculationRequest]
   FOREIGN KEY([RequestId]) REFERENCES [cqm2019].[DoctorCQMCalculationRequest] ([RequestId])

GO
