SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [core].[ufn_GetPrescriberInfoBySPI] 
( 
    @SPI VARCHAR(50)
) 
	RETURNS @Output TABLE(DoctorId BIGINT,DoctorCompanyId BIGINT,DoctorGroupId BIGINT,IsEPCSEnabled BIT
) 
BEGIN 
   
    INSERT INTO @Output (DoctorId,DoctorCompanyId,DoctorGroupId,IsEPCSEnabled)  
	SELECT D.dr_id,DG.dc_id,dg.dg_id,D.epcs_enabled--D.DR_FIRST_NAME,dr_enabled, D.DR_PREFIX, D.DR_SUFFIX, D.NPI, D.TIME_DIFFERENCE, D.DR_MIDDLE_INITIAL, D.DR_LAST_NAME, D.DR_ID, D.DG_ID, DG.DC_ID, D.DR_ADDRESS1, D.DR_ADDRESS2, D.DR_CITY,  D.DR_STATE, D.DR_DEA_NUMB, D.DR_ZIP, D.DR_PHONE, D.DR_FAX,D.epcs_enabled, D.PRESCRIBING_AUTHORITY 
	FROM DOCTORS D WITH(NOLOCK)
	INNER JOIN DOC_GROUPS DG  WITH(NOLOCK) ON D.DG_ID = DG.DG_ID 
	WHERE D.dr_enabled=1 AND  D.SPI_ID = @SPI
    RETURN 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
