SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [core].[ufn_GetPharmacyInfoByNCPDPNumber] 
( 
    @NCPDPNumber VARCHAR(50)
) 
	RETURNS @Output TABLE(PharmacyId BIGINT) 
BEGIN 
   
    INSERT INTO @Output (PharmacyId)  
	SELECT P.PHARM_ID--, P.PHARM_COMPANY_NAME, P.PHARM_ADDRESS1, P.PHARM_ADDRESS2, P.PHARM_CITY, P.PHARM_STATE, P.PHARM_ZIP, P.PHARM_PHONE, P.PHARM_FAX, P.NCPDP_NUMB, P.PHARM_PARTICIPANT, P.SERVICE_LEVEL, CASE WHEN x.pharmacy_id IS null THEN 0 ELSE 1 END MO 
	FROM pharmacies P WITH(NOLOCK) 
	LEFT OUTER JOIN pharm_mo_xref X WITH(NOLOCK) on p.pharm_id = X.pharmacy_id 
	WHERE PHARM_ENABLED=1 AND P.NCPDP_NUMB = @NCPDPNumber
    RETURN 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
