SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[IS_CLIENT_PREF_TIME] 
	(@DT AS DATETIME, 
	 @TZ AS VARCHAR(12),
	 @prefstarttime AS DATETIME,
	 @prefendtime AS DATETIME)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULT AS BIT
	DECLARE @NEWDT AS DATETIME
	DECLARE @TODAY AS DATETIME
	SET @NEWDT=dbo.GET_TZTIME(@DT,@TZ)
	SET @TODAY=DATEADD(dd, DATEDIFF(d, 0, @DT), 0)
	IF @NEWDT >= @TODAY+@prefstarttime AND @NEWDT<= @TODAY+@prefendtime  
		SET @RESULT= 1
	ELSE
		SET @RESULT= 0
	RETURN  @RESULT 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
