SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [dbo].[spCheckRebuildFDBIndexes] 
AS
BEGIN
	DECLARE @SCHEMA_NAME VARCHAR(50)

	SELECT @SCHEMA_NAME = fdb_schema_next_name 
	FROM dbo.fdb_schema_current 
	WHERE fdb_schema_next_need_index_rebuild = 1
	AND fdb_schema_next_has_errors = 0 
	
	IF NOT @SCHEMA_NAME IS NULL BEGIN
		PRINT 'Rebuilding indexes on schema ' + @SCHEMA_NAME
		EXEC dbo.spRebuildIndexes @ONLY_SCHEMA_NAME = @SCHEMA_NAME
		UPDATE dbo.fdb_schema_current SET fdb_schema_next_need_index_rebuild = 0 WHERE fdb_schema_current_id = 1
		PRINT 'Done rebuilding indexes on schema ' + @SCHEMA_NAME
	END ELSE BEGIN
		PRINT 'Nothing to rebuild'
	END
END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE dbo.spDoFDBSwap
AS 	
BEGIN
	SET NOCOUNT ON
	BEGIN TRANSACTION

	BEGIN TRY
		DECLARE @CURR_SCHEMA VARCHAR(10)
		DECLARE @NEW_SCHEMA VARCHAR(10)
		DECLARE @CURR_SCHEMA_ID INT
		DECLARE @NEW_SCHEMA_ID INT
		DECLARE @TABLE_NAME VARCHAR(255)
		DECLARE @SQL NVARCHAR(4000)
		DECLARE @ERROR NVARCHAR(MAX)

		SELECT @CURR_SCHEMA = fdb_schema_current_name FROM dbo.fdb_schema_current WHERE fdb_schema_current_id = 1

		IF @CURR_SCHEMA = 'fdb_a' BEGIN
			SET @NEW_SCHEMA = 'fdb_b'
		END ELSE BEGIN
			SET @NEW_SCHEMA = 'fdb_a'
		END

		SELECT @CURR_SCHEMA_ID = schema_id FROM sys.schemas WHERE name = @CURR_SCHEMA
		SELECT @NEW_SCHEMA_ID = schema_id FROM sys.schemas WHERE name = @NEW_SCHEMA

		PRINT 'Current schema: [' + CONVERT(VARCHAR(3), @CURR_SCHEMA_ID) + '] ' + @CURR_SCHEMA
		PRINT 'New schema: [' + CONVERT(VARCHAR(3), @NEW_SCHEMA_ID) + '] ' + @NEW_SCHEMA

		IF EXISTS (SELECT fdb_schema_current_id FROM dbo.fdb_schema_current WHERE fdb_schema_current_id = 1 AND fdb_schema_next_has_errors = 1) BEGIN
			SET @ERROR = 'Errors could exist in the data for the next FDB schema [' + @NEW_SCHEMA + '], the schemas can''t be swapped. Review the errors in the FDBUpdater daemon, fix any issues, then reset fdb_schema_next_has_errors to false in fdb_schema_current and try again.'
			RAISERROR (@ERROR, 18, 1)
		END

		PRINT 'Synchronize Custom Medications'
		SET @SQL = 'INSERT INTO ' + @NEW_SCHEMA + '.RNMMIDNDC (MEDID, med_name, MED_MEDID_DESC, obsdtec, NDC, MED_REF_DEA_CD, ROUTED_DOSAGE_FORM_MED_ID, med_routed_df_med_id_desc, ROUTED_MED_ID, MED_ROUTED_MED_ID_DESC, MED_NAME_ID, MED_NAME_TYPE_CD, MED_DOSAGE_FORM_ID, MED_DOSAGE_FORM_ABBR, MED_DOSAGE_FORM_DESC, MED_ROUTE_ID, MED_ROUTE_ABBR, MED_ROUTE_DESC, ETC_ID) 
		SELECT MEDID, med_name, MED_MEDID_DESC, obsdtec, NDC, MED_REF_DEA_CD, ROUTED_DOSAGE_FORM_MED_ID, med_routed_df_med_id_desc, ROUTED_MED_ID, MED_ROUTED_MED_ID_DESC, MED_NAME_ID, MED_NAME_TYPE_CD, MED_DOSAGE_FORM_ID, MED_DOSAGE_FORM_ABBR, MED_DOSAGE_FORM_DESC, MED_ROUTE_ID, MED_ROUTE_ABBR, MED_ROUTE_DESC, ETC_ID 
		FROM ' + @CURR_SCHEMA + '.RNMMIDNDC Z 
		WHERE Z.MEDID > 999999 
		AND NOT EXISTS (
			SELECT MEDID 
			FROM ' + @NEW_SCHEMA + '.RNMMIDNDC 
			WHERE MEDID = Z.MEDID
		)'
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		SET @SQL = 'INSERT INTO ' + @NEW_SCHEMA + '.RMIID1 (MEDID, MED_MEDID_DESC, ROUTED_DOSAGE_FORM_MED_ID, GCN_SEQNO, MED_GCNSEQNO_ASSIGN_CD, MED_NAME_SOURCE_CD, MED_REF_FED_LEGEND_IND, MED_REF_DEA_CD, MED_REF_MULTI_SOURCE_CD, MED_REF_GEN_DRUG_NAME_CD, MED_REF_GEN_COMP_PRICE_CD, MED_REF_GEN_SPREAD_CD, MED_REF_INNOV_IND, MED_REF_GEN_THERA_EQU_CD, MED_REF_DESI_IND, MED_REF_DESI2_IND, MED_STATUS_CD, GCN_STRING) 
		SELECT MEDID, MED_MEDID_DESC, ROUTED_DOSAGE_FORM_MED_ID, GCN_SEQNO, MED_GCNSEQNO_ASSIGN_CD, MED_NAME_SOURCE_CD, MED_REF_FED_LEGEND_IND, MED_REF_DEA_CD, MED_REF_MULTI_SOURCE_CD, MED_REF_GEN_DRUG_NAME_CD, MED_REF_GEN_COMP_PRICE_CD, MED_REF_GEN_SPREAD_CD, MED_REF_INNOV_IND, MED_REF_GEN_THERA_EQU_CD, MED_REF_DESI_IND, MED_REF_DESI2_IND, MED_STATUS_CD, GCN_STRING 
		FROM ' + @CURR_SCHEMA + '.RMIID1 Z 
		WHERE Z.MEDID > 999999 
		AND NOT EXISTS (
			SELECT MEDID 
			FROM ' + @NEW_SCHEMA + '.RMIID1 
			WHERE MEDID = Z.MEDID
		)'
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		PRINT 'Synchronize Active Meds'
		SET @SQL = '
		TRUNCATE TABLE ' + @NEW_SCHEMA + '.active_drugs;

		INSERT INTO ' + @NEW_SCHEMA + '.active_drugs (medid, is_active) VALUES (0, 0);

		INSERT INTO ' + @NEW_SCHEMA + '.active_drugs 
		SELECT DISTINCT MEDID, 1 FROM ' + @NEW_SCHEMA + '.RNMMIDNDC;

		INSERT INTO ' + @NEW_SCHEMA + '.active_drugs
		SELECT MEDID, 0 FROM ' + @NEW_SCHEMA + '.RMIID1 WHERE medid NOT IN (
			SELECT medid FROM ' + @NEW_SCHEMA + '.active_drugs
		);

		IF NOT EXISTS(SELECT 1 FROM ' + @NEW_SCHEMA + '.active_drugs WHERE medid = 999999)
		BEGIN
			INSERT INTO ' + @NEW_SCHEMA + '.active_drugs (medid, is_active) VALUES (999999, 1)
		END;

		IF NOT EXISTS(SELECT 1 FROM ' + @NEW_SCHEMA + '.active_drugs WHERE medid = -1)
		BEGIN
			INSERT INTO ' + @NEW_SCHEMA + '.active_drugs (medid, is_active) VALUES (-1, 1)
		END;'
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		SET @SQL = 'UPDATE ' + @NEW_SCHEMA + '.RNMMIDNDC SET NDC = '''' 
		WHERE LEN(NDC) > 0 
		AND LEN(NDC) <> 11'
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		SET @SQL = 'UPDATE ' + @NEW_SCHEMA + '.RMIID1 SET GCN_STRING = NULL 
		WHERE GCN_STRING LIKE ''0''
		AND NOT GCN_STRING IS NULL'
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		SET @SQL = 'UPDATE ' + @NEW_SCHEMA + '.RMIID1 SET GCN_STRING = '''' 
		WHERE MEDID = 662863
		AND GCN_STRING <> '''''
		PRINT @SQL 
		EXECUTE sys.sp_executesql @statement = @SQL 

		DECLARE TABLES_CUR CURSOR FORWARD_ONLY READ_ONLY LOCAL FOR 	
			SELECT name
			FROM sys.tables 
			WHERE schema_id = @CURR_SCHEMA_ID

		OPEN TABLES_CUR
		FETCH NEXT FROM TABLES_CUR INTO @TABLE_NAME	
		WHILE @@FETCH_STATUS = 0 BEGIN 	
			PRINT 'Table: ' + @TABLE_NAME 

			SET @SQL = 'DROP SYNONYM IF EXISTS dbo.' + @TABLE_NAME
			PRINT @SQL
			EXECUTE sys.sp_executesql @statement = @SQL

			SET @SQL = 'CREATE SYNONYM dbo.' + @TABLE_NAME + ' FOR ' + @NEW_SCHEMA + '.' + @TABLE_NAME
			PRINT @SQL
			EXECUTE sys.sp_executesql @statement = @SQL
			
			FETCH NEXT FROM TABLES_CUR INTO @TABLE_NAME	
		END  	
		CLOSE TABLES_CUR
		DEALLOCATE TABLES_CUR

		UPDATE dbo.fdb_schema_current 
		SET fdb_schema_current_name = @NEW_SCHEMA, 
		fdb_schema_current_activated = GETDATE(), 
		fdb_schema_next_name = @CURR_SCHEMA
		WHERE fdb_schema_current_id = 1

		SET @ERROR = ''
	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION
			PRINT 'Transaction failed'
		END
		SET @ERROR = 'Error Number: ' + CAST(ERROR_NUMBER() AS VARCHAR(10)) + '; ' + CHAR(10) +
        'Error Severity: ' + CAST(ERROR_SEVERITY() AS VARCHAR(10)) + '; ' + CHAR(10) +
        'Error State: ' + CAST(ERROR_STATE() AS VARCHAR(10)) + '; ' + CHAR(10) +
        'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(10)) + '; ' + CHAR(10) +
        'Error Message: ' + ERROR_MESSAGE()
		PRINT @ERROR
	END CATCH

	IF @@TRANCOUNT > 0 BEGIN
		COMMIT TRANSACTION
		PRINT 'Transaction successful' 
	END
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE spQRefreshViews 
as 	
  begin 	
		set nocount on 	

		declare @Pass     int; 	
		declare @PassMax  int; 	
		declare @ViewName varchar(90); 	

		declare views_cursor cursor for 	
			select TABLE_NAME 	
			from INFORMATION_SCHEMA.VIEWS 	
			where TABLE_NAME not in ('sysconstraints', 'syssegments') 	
			and TABLE_SCHEMA = 'dbo' 	
			order by len(TABLE_NAME); 	
				
		set @PassMax = 9; 	

		set @Pass = 1; 	
		while @Pass <= @PassMax begin 	
			print 'Pass ' + cast(@Pass as varchar(10)); 	
			open views_cursor; 	
			fetch next from views_cursor into @ViewName; 	
			while @@FETCH_STATUS = 0 begin 	
				print 'sp_refreshview ' + @ViewName; 	
				exec sp_refreshview @ViewName; 	
				fetch next from views_cursor into @ViewName; 	
			end  	
			close views_cursor; 	
			set @Pass = @Pass + 1; 	
		end 	
		deallocate views_cursor; 	
  end
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE dbo.spRebuildIndexes (@ONLY_SCHEMA_NAME NVARCHAR(50))
AS
BEGIN
	DECLARE @SCHEMA_NAME VARCHAR(50)
	DECLARE @TABLE_NAME VARCHAR(255)
	DECLARE @SQL NVARCHAR(4000)

	DECLARE TABLES_CUR CURSOR FORWARD_ONLY READ_ONLY LOCAL FOR
		SELECT S.name AS sname, T.name AS tname 
		FROM sys.tables T 
		INNER JOIN sys.schemas S ON T.schema_id = S.schema_id 
		WHERE T.type = 'U'
		AND S.name = CASE WHEN @ONLY_SCHEMA_NAME IS NULL THEN S.name ELSE @ONLY_SCHEMA_NAME END 

	OPEN TABLES_CUR
	FETCH NEXT FROM TABLES_CUR INTO @SCHEMA_NAME, @TABLE_NAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @SQL = 'ALTER INDEX ALL ON ' + @SCHEMA_NAME + '.' + @TABLE_NAME + ' REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = OFF)'
		PRINT @SQL
		EXECUTE sp_executesql @statement = @SQL
		FETCH NEXT FROM TABLES_CUR INTO @SCHEMA_NAME, @TABLE_NAME
	END

	CLOSE TABLES_CUR
	DEALLOCATE TABLES_CUR
END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE dbo.spRunPostBCPUpdates_fdb_a
AS
BEGIN
	TRUNCATE TABLE fdb_a.RNMMIDNDC

	INSERT INTO fdb_a.RNMMIDNDC
	(
		NDC,
		OBSDTEC,
		LBLRID,
		GCN_SEQNO,
		LN,
		BN,
		DEA,
		GPI,
		OBC,
		REPACK,
		LN25,
		MEDID,
		MED_STRENGTH,
		MED_STRENGTH_UOM,
		MED_MEDID_DESC,
		MED_REF_DEA_CD,
		GENERIC_MEDID,
		ROUTED_DOSAGE_FORM_MED_ID,
		med_routed_df_med_id_desc,
		ROUTED_MED_ID,
		MED_ROUTED_MED_ID_DESC,
		MED_NAME_ID,
		MED_NAME,
		MED_NAME_TYPE_CD,
		MED_DOSAGE_FORM_ID,
		MED_DOSAGE_FORM_ABBR,
		MED_DOSAGE_FORM_DESC,
		MED_ROUTE_ID,
		MED_ROUTE_ABBR,
		MED_ROUTE_DESC,
		ETC_ID,
		ETC_NAME
	)
	SELECT DISTINCT A.NDC, A.OBSDTEC, A.LBLRID, A.GCN_SEQNO, A.LN, A.BN, A.DEA, A.GPI, A.OBC, A.REPACK,
	A.LN25, R.MEDID, R.MED_STRENGTH, R.MED_STRENGTH_UOM, R.MED_MEDID_DESC, R.MED_REF_DEA_CD, R.GENERIC_MEDID,
	R.ROUTED_DOSAGE_FORM_MED_ID, C.MED_ROUTED_DF_MED_ID_DESC, C.ROUTED_MED_ID, D.MED_ROUTED_MED_ID_DESC,
	E.MED_NAME_ID, E.MED_NAME, E.MED_NAME_TYPE_CD, C.MED_DOSAGE_FORM_ID,
	F.MED_DOSAGE_FORM_ABBR, F.MED_DOSAGE_FORM_DESC, G.MED_ROUTE_ID, G.MED_ROUTE_ABBR,
	G.MED_ROUTE_DESC, 0 ETC_ID, '' ETC_NAME 
	FROM fdb_a.RNDC14 A 
	INNER JOIN fdb_a.RMINDC1 B ON A.NDC = B.NDC 
	INNER JOIN fdb_a.RMIID1 R ON B.MEDID = R.MEDID
	INNER JOIN fdb_a.RMIDFID1 C ON R.ROUTED_DOSAGE_FORM_MED_ID = C.ROUTED_DOSAGE_FORM_MED_ID
	INNER JOIN fdb_a.RMIRMID1 D ON C.ROUTED_MED_ID = D.ROUTED_MED_ID
	INNER JOIN fdb_a.RMINMID1 E ON D.MED_NAME_ID = E.MED_NAME_ID
	INNER JOIN fdb_a.RMIDFD1 F ON C.MED_DOSAGE_FORM_ID = F.MED_DOSAGE_FORM_ID
	INNER JOIN fdb_a.RMIRTD1 G ON D.MED_ROUTE_ID = G.MED_ROUTE_ID
	WHERE A.OBSDTEC IS NULL 

	UPDATE fdb_a.RNMMIDNDC  
	SET RNMMIDNDC.ETC_ID = T.ETC_ID, RNMMIDNDC.ETC_NAME = T.ETC_NAME 
	FROM (
		SELECT Q.MEDID,  Q.ETC_ID, S.ETC_NAME 
		FROM (
			SELECT R.MEDID, MAX(I.ETC_ID) ETC_ID 
			FROM fdb_a.RMIID1 R 
			INNER JOIN fdb_a.RETCMED0 H ON R.MEDID = H.MEDID
			INNER JOIN fdb_a.RETCTBL0 I ON H.ETC_ID = I.ETC_ID 
			WHERE H.ETC_DEFAULT_USE_IND = 1
			GROUP BY R.MEDID
		) Q 
		INNER JOIN fdb_a.RETCTBL0 S ON Q.ETC_ID = S.ETC_ID
	) T
	WHERE RNMMIDNDC.MEDID = T.MEDID 

	UPDATE fdb_a.RNMMIDNDC SET REPACK = '0' WHERE REPACK = '1'

	UPDATE fdb_a.RNMMIDNDC 
	SET MED_MEDID_DESC = MED_NAME + ' ' + MED_STRENGTH + ' ' + MED_STRENGTH_UOM + ' ' + MED_DOSAGE_FORM_ABBR 
	WHERE MED_NAME LIKE 'metoprolol%'

	UPDATE fdb_a.RMIID1 SET MED_REF_GEN_COMP_PRICE_CD = MED_REF_GEN_DRUG_NAME_CD WHERE 1 = 1

	INSERT INTO fdb_a.RMIID1
	SELECT * FROM RxGlobalNew.dbo.RMIID1 
	WHERE EXISTS (
		SELECT OLD_MEDID 
		FROM dbo.unmatched_drugs
		WHERE OLD_MEDID = RMIID1.MEDID
	)
	AND NOT EXISTS (
		SELECT MEDID
		FROM fdb_a.RMIID1
		WHERE MEDID = RMIID1.MEDID
	)

	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC = a.MED_MEDID_DESC 
	FROM fdb_a.RNMMIDNDC a WHERE RMIID1.MEDID = a.MEDID 
	AND a.MED_NAME LIKE 'metoprolol%'

	UPDATE fdb_a.RMIID1 SET MED_STATUS_CD = 3 WHERE MEDID = 448245

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_NAME LIKE 'soma'

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID IN (
		SELECT DISTINCT MEDID FROM fdb_a.RNMMIDNDC WHERE MED_NAME LIKE 'soma'
	)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MED_MEDID_DESC LIKE 'Fioricet%'
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MED_MEDID_DESC LIKE 'Fioricet%'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 150853
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 150853

	--Sudogest 30 mg tablet
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MEDID = 207818
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MEDID = 207818

	--Sudogest 60 mg tablet
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MEDID = 296252
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MEDID = 296252

	-- Esgic 50 mg-325 mg-40 mg capsule
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 229265
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 229265

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'tramadol%'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'tramadol%'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'ultram %'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'ultram %'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg capsule'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg capsule'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg tablet'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg tablet'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-300 mg-40 mg capsule'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-300 mg-40 mg capsule'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MED_MEDID_DESC LIKE 'Zyrtec-D 5 mg-120 mg tablet,extended release'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MED_MEDID_DESC LIKE 'Zyrtec-D 5 mg-120 mg tablet,extended release'

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 183265
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 183265

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 261487
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 261487

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 475510
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 475510

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'omnitrope %'
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'omnitrope %' 

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 472756
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 472756

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 449050
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 449050

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 591179
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 591179

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 279935
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 279935

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 572978
	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 572978

	IF NOT EXISTS(SELECT 1 FROM fdb_a.RMIID1 WHERE MEDID = 999999)
	BEGIN
		INSERT INTO fdb_a.RMIID1 (MEDID, ROUTED_DOSAGE_FORM_MED_ID, MED_STRENGTH, MED_STRENGTH_UOM, MED_MEDID_DESC,
		GCN_SEQNO, MED_GCNSEQNO_ASSIGN_CD, MED_NAME_SOURCE_CD, MED_REF_FED_LEGEND_IND,MED_REF_DEA_CD,
		MED_REF_MULTI_SOURCE_CD, MED_REF_GEN_DRUG_NAME_CD, MED_REF_GEN_COMP_PRICE_CD,
		MED_REF_GEN_SPREAD_CD, MED_REF_INNOV_IND, MED_REF_GEN_THERA_EQU_CD, MED_REF_DESI_IND, MED_REF_DESI2_IND,
		MED_STATUS_CD, GENERIC_MEDID)
		VALUES (999999, 0, NULL, NULL, 'No Active Meds', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	END

	IF NOT EXISTS(SELECT 1 FROM fdb_a.RETCMED0 WHERE MEDID = 999999 AND ETC_ID = 2753)
	BEGIN
		INSERT INTO fdb_a.RETCMED0 (MEDID, ETC_ID, ETC_COMMON_USE_IND, ETC_DEFAULT_USE_IND)
		VALUES (999999, 2753, 1, 1)
	END

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC = 'Metrogel 1 % Topical Gel Pump' WHERE MEDID = 474502
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC = 'Metrogel 1 % Topical Gel Pump' WHERE MEDID = 474502

	IF NOT EXISTS(SELECT 1 FROM  fdb_a.RMIID1 WHERE MEDID = -1)
	BEGIN
		INSERT INTO fdb_a.RMIID1
					(MEDID
					,ROUTED_DOSAGE_FORM_MED_ID
					,MED_STRENGTH
					,MED_STRENGTH_UOM
					,MED_MEDID_DESC
					,GCN_SEQNO
					,MED_GCNSEQNO_ASSIGN_CD
					,MED_NAME_SOURCE_CD
					,MED_REF_FED_LEGEND_IND
					,MED_REF_DEA_CD
					,MED_REF_MULTI_SOURCE_CD
					,MED_REF_GEN_DRUG_NAME_CD
					,MED_REF_GEN_COMP_PRICE_CD
					,MED_REF_GEN_SPREAD_CD
					,MED_REF_INNOV_IND
					,MED_REF_GEN_THERA_EQU_CD
					,MED_REF_DESI_IND
					,MED_REF_DESI2_IND
					,MED_STATUS_CD
					,GENERIC_MEDID)
				VALUES
					(-1
					,0
					,NULL
					,NULL
					,'Free Text Medication'
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0)
	END

	IF NOT EXISTS(SELECT 1 FROM fdb_a.RETCMED0 WHERE MEDID = -1)
	BEGIN
		INSERT INTO fdb_a.RETCMED0 (
			MEDID
			,ETC_ID
			,ETC_COMMON_USE_IND
			,ETC_DEFAULT_USE_IND
		) VALUES (
			-1
			,2753
			,1
			,1
		)
	END

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='Morphine 30mg IR tablet' WHERE MEDID IN (235596)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='Morphine 30mg IR tablet' WHERE MEDID IN (235596)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='Morphine 15mg IR tablet' WHERE MEDID IN (282842)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='Morphine 15mg IR tablet' WHERE MEDID IN (282842)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 15 mg IR tablet' WHERE MEDID IN (211994)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='oxycodone 15 mg IR tablet' WHERE MEDID IN (211994)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 30 mg IR tablet' WHERE MEDID IN (272950)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='oxycodone 30 mg IR tablet' WHERE MEDID IN (272950)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 5 mg IR tablet' WHERE MEDID IN (298962)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='oxycodone 5 mg IR tablet' WHERE MEDID IN (298962)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 10 mg IR tablet' WHERE MEDID IN (554375)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='oxycodone 10 mg IR tablet' WHERE MEDID IN (554375)

	UPDATE fdb_a.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 20 mg IR tablet' WHERE MEDID IN (554376)
	UPDATE fdb_a.RMIID1 SET MED_MEDID_DESC='oxycodone 20 mg IR tablet' WHERE MEDID IN (554376)

	INSERT INTO fdb_a.RNMMIDNDC (NDC,MEDID,MED_MEDID_DESC,MED_REF_DEA_CD,ROUTED_DOSAGE_FORM_MED_ID,med_routed_df_med_id_desc,ROUTED_MED_ID,MED_ROUTED_MED_ID_DESC,MED_NAME_ID,MED_NAME,MED_NAME_TYPE_CD,MED_DOSAGE_FORM_ID,MED_DOSAGE_FORM_ABBR,MED_DOSAGE_FORM_DESC,MED_ROUTE_ID,MED_ROUTE_ABBR,MED_ROUTE_DESC,ETC_ID)
	VALUES ('',999999,'No Active Meds',0,0,'No Active Meds',0,'No Active Meds',0,'No Active Meds','',0,'','',0,'','',0)

	UPDATE RM SET GCN_STRING = RG.GCN 
	FROM fdb_a.RMIID1 RM 
	INNER JOIN fdb_a.RGCN0 RG ON RM.GCN_SEQNO = RG.GCN_SEQNO
	WHERE 1 = 1

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 247230
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 247230

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(162323, 187428, 197020 , 229421, 258949, 271154, 554511, 574742, 574743)

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(162323, 187428, 197020 , 229421, 258949, 271154, 554511, 574742, 574743)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(155629, 164059, 192149, 196133, 242690, 263989)

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(155629, 164059, 192149, 196133, 242690, 263989)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN (247230,594369,188463,259028,452812)

	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN (247230,594369,188463,259028,452812)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 288226
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 288226

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (156741, 446351)
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (156741, 446351)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (224665, 434834)
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (224665, 434834)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (244365)
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (244365)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (451132, 569501)
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (451132, 569501)

	UPDATE fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (473583)
	UPDATE fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (473583)

	UPDATE  fdb_a.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (291728,430988,259052,476487,564130, 197837)
	UPDATE  fdb_a.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (291728,430988,259052,476487,564130, 197837)

	UPDATE fdb_a.RNMMIDNDC SET OBSDTEC = GETDATE() WHERE MEDID = 999999 

	IF NOT EXISTS (SELECT * FROM fdb_a.RDAMAPM0 WHERE DAM_CONCEPT_ID_DESC = 'Fluoroquinolones')
	BEGIN
		INSERT INTO fdb_a.RDAMAPM0 (
			DAM_CONCEPT_ID, DAM_CONCEPT_ID_TYP, DAM_CONCEPT_ID_DESC
		) VALUES (
			900599, 1, 'Fluoroquinolones'
		)
	END

	TRUNCATE TABLE fdb_a.REVDEL0_Active_Med

	INSERT INTO fdb_a.REVDEL0_Active_Med (EVD_EXT_VOCAB_ID, EVD_FDB_VOCAB_ID)
	SELECT MAX(EVD_EXT_VOCAB_ID) EVD_EXT_VOCAB_ID, EVD_FDB_VOCAB_ID 
	FROM fdb_a.REVDEL0 
	WHERE EVD_FDB_VOCAB_TYPE_ID = 3
	GROUP BY EVD_FDB_VOCAB_ID
END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE dbo.spRunPostBCPUpdates_fdb_b
AS
BEGIN
	TRUNCATE TABLE fdb_b.RNMMIDNDC

	INSERT INTO fdb_b.RNMMIDNDC
	(
		NDC,
		OBSDTEC,
		LBLRID,
		GCN_SEQNO,
		LN,
		BN,
		DEA,
		GPI,
		OBC,
		REPACK,
		LN25,
		MEDID,
		MED_STRENGTH,
		MED_STRENGTH_UOM,
		MED_MEDID_DESC,
		MED_REF_DEA_CD,
		GENERIC_MEDID,
		ROUTED_DOSAGE_FORM_MED_ID,
		med_routed_df_med_id_desc,
		ROUTED_MED_ID,
		MED_ROUTED_MED_ID_DESC,
		MED_NAME_ID,
		MED_NAME,
		MED_NAME_TYPE_CD,
		MED_DOSAGE_FORM_ID,
		MED_DOSAGE_FORM_ABBR,
		MED_DOSAGE_FORM_DESC,
		MED_ROUTE_ID,
		MED_ROUTE_ABBR,
		MED_ROUTE_DESC,
		ETC_ID,
		ETC_NAME
	)
	SELECT DISTINCT A.NDC, A.OBSDTEC, A.LBLRID, A.GCN_SEQNO, A.LN, A.BN, A.DEA, A.GPI, A.OBC, A.REPACK,
	A.LN25, R.MEDID, R.MED_STRENGTH, R.MED_STRENGTH_UOM, R.MED_MEDID_DESC, R.MED_REF_DEA_CD, R.GENERIC_MEDID,
	R.ROUTED_DOSAGE_FORM_MED_ID, C.MED_ROUTED_DF_MED_ID_DESC, C.ROUTED_MED_ID, D.MED_ROUTED_MED_ID_DESC,
	E.MED_NAME_ID, E.MED_NAME, E.MED_NAME_TYPE_CD, C.MED_DOSAGE_FORM_ID,
	F.MED_DOSAGE_FORM_ABBR, F.MED_DOSAGE_FORM_DESC, G.MED_ROUTE_ID, G.MED_ROUTE_ABBR,
	G.MED_ROUTE_DESC, 0 ETC_ID, '' ETC_NAME 
	FROM fdb_b.RNDC14 A 
	INNER JOIN fdb_b.RMINDC1 B ON A.NDC = B.NDC 
	INNER JOIN fdb_b.RMIID1 R ON B.MEDID = R.MEDID
	INNER JOIN fdb_b.RMIDFID1 C ON R.ROUTED_DOSAGE_FORM_MED_ID = C.ROUTED_DOSAGE_FORM_MED_ID
	INNER JOIN fdb_b.RMIRMID1 D ON C.ROUTED_MED_ID = D.ROUTED_MED_ID
	INNER JOIN fdb_b.RMINMID1 E ON D.MED_NAME_ID = E.MED_NAME_ID
	INNER JOIN fdb_b.RMIDFD1 F ON C.MED_DOSAGE_FORM_ID = F.MED_DOSAGE_FORM_ID
	INNER JOIN fdb_b.RMIRTD1 G ON D.MED_ROUTE_ID = G.MED_ROUTE_ID
	WHERE A.OBSDTEC IS NULL 

	UPDATE fdb_b.RNMMIDNDC  
	SET RNMMIDNDC.ETC_ID = T.ETC_ID, RNMMIDNDC.ETC_NAME = T.ETC_NAME 
	FROM (
		SELECT Q.MEDID,  Q.ETC_ID, S.ETC_NAME 
		FROM (
			SELECT R.MEDID, MAX(I.ETC_ID) ETC_ID 
			FROM fdb_b.RMIID1 R 
			INNER JOIN fdb_b.RETCMED0 H ON R.MEDID = H.MEDID
			INNER JOIN fdb_b.RETCTBL0 I ON H.ETC_ID = I.ETC_ID 
			WHERE H.ETC_DEFAULT_USE_IND = 1
			GROUP BY R.MEDID
		) Q 
		INNER JOIN fdb_b.RETCTBL0 S ON Q.ETC_ID = S.ETC_ID
	) T
	WHERE RNMMIDNDC.MEDID = T.MEDID 

	UPDATE fdb_b.RNMMIDNDC SET REPACK = '0' WHERE REPACK = '1'

	UPDATE fdb_b.RNMMIDNDC 
	SET MED_MEDID_DESC = MED_NAME + ' ' + MED_STRENGTH + ' ' + MED_STRENGTH_UOM + ' ' + MED_DOSAGE_FORM_ABBR 
	WHERE MED_NAME LIKE 'metoprolol%'

	UPDATE fdb_b.RMIID1 SET MED_REF_GEN_COMP_PRICE_CD = MED_REF_GEN_DRUG_NAME_CD WHERE 1 = 1

	INSERT INTO fdb_b.RMIID1
	SELECT * FROM RxGlobalNew.dbo.RMIID1 
	WHERE EXISTS (
		SELECT OLD_MEDID 
		FROM dbo.unmatched_drugs
		WHERE OLD_MEDID = RMIID1.MEDID
	)
	AND NOT EXISTS (
		SELECT MEDID
		FROM fdb_b.RMIID1
		WHERE MEDID = RMIID1.MEDID
	)

	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC = a.MED_MEDID_DESC 
	FROM fdb_b.RNMMIDNDC a WHERE RMIID1.MEDID = a.MEDID 
	AND a.MED_NAME LIKE 'metoprolol%'

	UPDATE fdb_b.RMIID1 SET MED_STATUS_CD = 3 WHERE MEDID = 448245

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_NAME LIKE 'soma'

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID IN (
		SELECT DISTINCT MEDID FROM fdb_b.RNMMIDNDC WHERE MED_NAME LIKE 'soma'
	)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MED_MEDID_DESC LIKE 'Fioricet%'
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MED_MEDID_DESC LIKE 'Fioricet%'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 150853
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 150853

	--Sudogest 30 mg tablet
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MEDID = 207818
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MEDID = 207818

	--Sudogest 60 mg tablet
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 3 WHERE MEDID = 296252
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 3 WHERE MEDID = 296252

	-- Esgic 50 mg-325 mg-40 mg capsule
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 229265
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 229265

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'tramadol%'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'tramadol%'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'ultram %'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'ultram %'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg capsule'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg capsule'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg tablet'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-325 mg-40 mg tablet'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-300 mg-40 mg capsule'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'butalbital-acetaminophen-caffeine 50 mg-300 mg-40 mg capsule'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MED_MEDID_DESC LIKE 'Zyrtec-D 5 mg-120 mg tablet,extended release'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MED_MEDID_DESC LIKE 'Zyrtec-D 5 mg-120 mg tablet,extended release'

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 183265
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 183265

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 261487
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 261487

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MEDID = 475510
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MEDID = 475510

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'omnitrope %'
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 4 WHERE MED_MEDID_DESC LIKE 'omnitrope %' 

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 472756
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 472756

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 449050
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 449050

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 591179
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 591179

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 279935
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 279935

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 572978
	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 572978

	IF NOT EXISTS(SELECT 1 FROM fdb_b.RMIID1 WHERE MEDID = 999999)
	BEGIN
		INSERT INTO fdb_b.RMIID1 (MEDID, ROUTED_DOSAGE_FORM_MED_ID, MED_STRENGTH, MED_STRENGTH_UOM, MED_MEDID_DESC,
		GCN_SEQNO, MED_GCNSEQNO_ASSIGN_CD, MED_NAME_SOURCE_CD, MED_REF_FED_LEGEND_IND,MED_REF_DEA_CD,
		MED_REF_MULTI_SOURCE_CD, MED_REF_GEN_DRUG_NAME_CD, MED_REF_GEN_COMP_PRICE_CD,
		MED_REF_GEN_SPREAD_CD, MED_REF_INNOV_IND, MED_REF_GEN_THERA_EQU_CD, MED_REF_DESI_IND, MED_REF_DESI2_IND,
		MED_STATUS_CD, GENERIC_MEDID)
		VALUES (999999, 0, NULL, NULL, 'No Active Meds', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	END

	IF NOT EXISTS(SELECT 1 FROM fdb_b.RETCMED0 WHERE MEDID = 999999 AND ETC_ID = 2753)
	BEGIN
		INSERT INTO fdb_b.RETCMED0 (MEDID, ETC_ID, ETC_COMMON_USE_IND, ETC_DEFAULT_USE_IND)
		VALUES (999999, 2753, 1, 1)
	END

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC = 'Metrogel 1 % Topical Gel Pump' WHERE MEDID = 474502
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC = 'Metrogel 1 % Topical Gel Pump' WHERE MEDID = 474502

	IF NOT EXISTS(SELECT 1 FROM  fdb_b.RMIID1 WHERE MEDID = -1)
	BEGIN
		INSERT INTO fdb_b.RMIID1
					(MEDID
					,ROUTED_DOSAGE_FORM_MED_ID
					,MED_STRENGTH
					,MED_STRENGTH_UOM
					,MED_MEDID_DESC
					,GCN_SEQNO
					,MED_GCNSEQNO_ASSIGN_CD
					,MED_NAME_SOURCE_CD
					,MED_REF_FED_LEGEND_IND
					,MED_REF_DEA_CD
					,MED_REF_MULTI_SOURCE_CD
					,MED_REF_GEN_DRUG_NAME_CD
					,MED_REF_GEN_COMP_PRICE_CD
					,MED_REF_GEN_SPREAD_CD
					,MED_REF_INNOV_IND
					,MED_REF_GEN_THERA_EQU_CD
					,MED_REF_DESI_IND
					,MED_REF_DESI2_IND
					,MED_STATUS_CD
					,GENERIC_MEDID)
				VALUES
					(-1
					,0
					,NULL
					,NULL
					,'Free Text Medication'
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0
					,0)
	END

	IF NOT EXISTS(SELECT 1 FROM fdb_b.RETCMED0 WHERE MEDID = -1)
	BEGIN
		INSERT INTO fdb_b.RETCMED0 (
			MEDID
			,ETC_ID
			,ETC_COMMON_USE_IND
			,ETC_DEFAULT_USE_IND
		) VALUES (
			-1
			,2753
			,1
			,1
		)
	END

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='Morphine 30mg IR tablet' WHERE MEDID IN (235596)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='Morphine 30mg IR tablet' WHERE MEDID IN (235596)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='Morphine 15mg IR tablet' WHERE MEDID IN (282842)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='Morphine 15mg IR tablet' WHERE MEDID IN (282842)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 15 mg IR tablet' WHERE MEDID IN (211994)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='oxycodone 15 mg IR tablet' WHERE MEDID IN (211994)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 30 mg IR tablet' WHERE MEDID IN (272950)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='oxycodone 30 mg IR tablet' WHERE MEDID IN (272950)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 5 mg IR tablet' WHERE MEDID IN (298962)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='oxycodone 5 mg IR tablet' WHERE MEDID IN (298962)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 10 mg IR tablet' WHERE MEDID IN (554375)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='oxycodone 10 mg IR tablet' WHERE MEDID IN (554375)

	UPDATE fdb_b.RNMMIDNDC SET MED_MEDID_DESC='oxycodone 20 mg IR tablet' WHERE MEDID IN (554376)
	UPDATE fdb_b.RMIID1 SET MED_MEDID_DESC='oxycodone 20 mg IR tablet' WHERE MEDID IN (554376)

	INSERT INTO fdb_b.RNMMIDNDC (NDC,MEDID,MED_MEDID_DESC,MED_REF_DEA_CD,ROUTED_DOSAGE_FORM_MED_ID,med_routed_df_med_id_desc,ROUTED_MED_ID,MED_ROUTED_MED_ID_DESC,MED_NAME_ID,MED_NAME,MED_NAME_TYPE_CD,MED_DOSAGE_FORM_ID,MED_DOSAGE_FORM_ABBR,MED_DOSAGE_FORM_DESC,MED_ROUTE_ID,MED_ROUTE_ABBR,MED_ROUTE_DESC,ETC_ID)
	VALUES ('',999999,'No Active Meds',0,0,'No Active Meds',0,'No Active Meds',0,'No Active Meds','',0,'','',0,'','',0)

	UPDATE RM SET GCN_STRING = RG.GCN 
	FROM fdb_b.RMIID1 RM 
	INNER JOIN fdb_b.RGCN0 RG ON RM.GCN_SEQNO = RG.GCN_SEQNO
	WHERE 1 = 1

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 247230
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 247230

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(162323, 187428, 197020 , 229421, 258949, 271154, 554511, 574742, 574743)

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(162323, 187428, 197020 , 229421, 258949, 271154, 554511, 574742, 574743)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(155629, 164059, 192149, 196133, 242690, 263989)

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN(155629, 164059, 192149, 196133, 242690, 263989)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN (247230,594369,188463,259028,452812)

	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 
	WHERE MEDID IN (247230,594369,188463,259028,452812)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID = 288226
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID = 288226

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (156741, 446351)
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (156741, 446351)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (224665, 434834)
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (224665, 434834)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (244365)
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (244365)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (451132, 569501)
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (451132, 569501)

	UPDATE fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (473583)
	UPDATE fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (473583)

	UPDATE  fdb_b.RMIID1 SET MED_REF_DEA_CD = 5 WHERE MEDID IN (291728,430988,259052,476487,564130, 197837)
	UPDATE  fdb_b.RNMMIDNDC SET MED_REF_DEA_CD = 5 WHERE MEDID IN (291728,430988,259052,476487,564130, 197837)

	UPDATE fdb_b.RNMMIDNDC SET OBSDTEC = GETDATE() WHERE MEDID = 999999 

	IF NOT EXISTS (SELECT * FROM fdb_b.RDAMAPM0 WHERE DAM_CONCEPT_ID_DESC = 'Fluoroquinolones')
	BEGIN
		INSERT INTO fdb_b.RDAMAPM0 (
			DAM_CONCEPT_ID, DAM_CONCEPT_ID_TYP, DAM_CONCEPT_ID_DESC
		) VALUES (
			900599, 1, 'Fluoroquinolones'
		)
	END

	TRUNCATE TABLE fdb_b.REVDEL0_Active_Med

	INSERT INTO fdb_b.REVDEL0_Active_Med (EVD_EXT_VOCAB_ID, EVD_FDB_VOCAB_ID)
	SELECT MAX(EVD_EXT_VOCAB_ID) EVD_EXT_VOCAB_ID, EVD_FDB_VOCAB_ID 
	FROM fdb_b.REVDEL0 
	WHERE EVD_FDB_VOCAB_TYPE_ID = 3
	GROUP BY EVD_FDB_VOCAB_ID
END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
