CREATE SYNONYM [dbo].[active_drugs] FOR [fdb_a].[active_drugs]
GO
CREATE SYNONYM [dbo].[RADIMEF0] FOR [fdb_a].[RADIMEF0]
GO
CREATE SYNONYM [dbo].[RADIMGC4] FOR [fdb_a].[RADIMGC4]
GO
CREATE SYNONYM [dbo].[RADIMIE4] FOR [fdb_a].[RADIMIE4]
GO
CREATE SYNONYM [dbo].[RADIMMA5] FOR [fdb_a].[RADIMMA5]
GO
CREATE SYNONYM [dbo].[RADIMMO5] FOR [fdb_a].[RADIMMO5]
GO
CREATE SYNONYM [dbo].[RADIMSL1] FOR [fdb_a].[RADIMSL1]
GO
CREATE SYNONYM [dbo].[RAHFSD1] FOR [fdb_a].[RAHFSD1]
GO
CREATE SYNONYM [dbo].[RAHFSGC1] FOR [fdb_a].[RAHFSGC1]
GO
CREATE SYNONYM [dbo].[RAPPLNA0] FOR [fdb_a].[RAPPLNA0]
GO
CREATE SYNONYM [dbo].[RAPPLSL0] FOR [fdb_a].[RAPPLSL0]
GO
CREATE SYNONYM [dbo].[RAPPLTD0] FOR [fdb_a].[RAPPLTD0]
GO
CREATE SYNONYM [dbo].[RATCD0] FOR [fdb_a].[RATCD0]
GO
CREATE SYNONYM [dbo].[RATCGC0] FOR [fdb_a].[RATCGC0]
GO
CREATE SYNONYM [dbo].[RCMMD0] FOR [fdb_a].[RCMMD0]
GO
CREATE SYNONYM [dbo].[RCMMGC0] FOR [fdb_a].[RCMMGC0]
GO
CREATE SYNONYM [dbo].[RDAMAGD1] FOR [fdb_a].[RDAMAGD1]
GO
CREATE SYNONYM [dbo].[RDAMAPM0] FOR [fdb_a].[RDAMAPM0]
GO
CREATE SYNONYM [dbo].[RDAMCD0] FOR [fdb_a].[RDAMCD0]
GO
CREATE SYNONYM [dbo].[RDAMCSD1] FOR [fdb_a].[RDAMCSD1]
GO
CREATE SYNONYM [dbo].[RDAMGHC0] FOR [fdb_a].[RDAMGHC0]
GO
CREATE SYNONYM [dbo].[RDAMGRH0] FOR [fdb_a].[RDAMGRH0]
GO
CREATE SYNONYM [dbo].[RDAMGSD0] FOR [fdb_a].[RDAMGSD0]
GO
CREATE SYNONYM [dbo].[RDAMGX0] FOR [fdb_a].[RDAMGX0]
GO
CREATE SYNONYM [dbo].[RDAMXHC0] FOR [fdb_a].[RDAMXHC0]
GO
CREATE SYNONYM [dbo].[RDAMXSD0] FOR [fdb_a].[RDAMXSD0]
GO
CREATE SYNONYM [dbo].[RDAMXSH0] FOR [fdb_a].[RDAMXSH0]
GO
CREATE SYNONYM [dbo].[RDCCD0] FOR [fdb_a].[RDCCD0]
GO
CREATE SYNONYM [dbo].[RDDIMAG0] FOR [fdb_a].[RDDIMAG0]
GO
CREATE SYNONYM [dbo].[RDDIMIN0] FOR [fdb_a].[RDDIMIN0]
GO
CREATE SYNONYM [dbo].[RDDIMRD0] FOR [fdb_a].[RDDIMRD0]
GO
CREATE SYNONYM [dbo].[RDDIMRG0] FOR [fdb_a].[RDDIMRG0]
GO
CREATE SYNONYM [dbo].[RDDIMRM0] FOR [fdb_a].[RDDIMRM0]
GO
CREATE SYNONYM [dbo].[RDFIMGC0] FOR [fdb_a].[RDFIMGC0]
GO
CREATE SYNONYM [dbo].[RDFIMMA0] FOR [fdb_a].[RDFIMMA0]
GO
CREATE SYNONYM [dbo].[RDFIMMO0] FOR [fdb_a].[RDFIMMO0]
GO
CREATE SYNONYM [dbo].[RDFIMRG0] FOR [fdb_a].[RDFIMRG0]
GO
CREATE SYNONYM [dbo].[RDFIMRM0] FOR [fdb_a].[RDFIMRM0]
GO
CREATE SYNONYM [dbo].[RDLIMCR0] FOR [fdb_a].[RDLIMCR0]
GO
CREATE SYNONYM [dbo].[RDLIMDD0] FOR [fdb_a].[RDLIMDD0]
GO
CREATE SYNONYM [dbo].[RDLIMDI0] FOR [fdb_a].[RDLIMDI0]
GO
CREATE SYNONYM [dbo].[RDLIMDR0] FOR [fdb_a].[RDLIMDR0]
GO
CREATE SYNONYM [dbo].[RDLIMGC1] FOR [fdb_a].[RDLIMGC1]
GO
CREATE SYNONYM [dbo].[RDLIMID0] FOR [fdb_a].[RDLIMID0]
GO
CREATE SYNONYM [dbo].[RDLIMMA1] FOR [fdb_a].[RDLIMMA1]
GO
CREATE SYNONYM [dbo].[RDLIMMI0] FOR [fdb_a].[RDLIMMI0]
GO
CREATE SYNONYM [dbo].[RDLIMMO1] FOR [fdb_a].[RDLIMMO1]
GO
CREATE SYNONYM [dbo].[RDLIMRG0] FOR [fdb_a].[RDLIMRG0]
GO
CREATE SYNONYM [dbo].[RDLIMRM0] FOR [fdb_a].[RDLIMRM0]
GO
CREATE SYNONYM [dbo].[RDLIMSD0] FOR [fdb_a].[RDLIMSD0]
GO
CREATE SYNONYM [dbo].[RDLIMTD0] FOR [fdb_a].[RDLIMTD0]
GO
CREATE SYNONYM [dbo].[RDOSED2] FOR [fdb_a].[RDOSED2]
GO
CREATE SYNONYM [dbo].[RDPTCL0] FOR [fdb_a].[RDPTCL0]
GO
CREATE SYNONYM [dbo].[RDPTGC0] FOR [fdb_a].[RDPTGC0]
GO
CREATE SYNONYM [dbo].[RDPTRG0] FOR [fdb_a].[RDPTRG0]
GO
CREATE SYNONYM [dbo].[RDPTRTM0] FOR [fdb_a].[RDPTRTM0]
GO
CREATE SYNONYM [dbo].[RETCCTD0] FOR [fdb_a].[RETCCTD0]
GO
CREATE SYNONYM [dbo].[RETCGC0] FOR [fdb_a].[RETCGC0]
GO
CREATE SYNONYM [dbo].[RETCGCH0] FOR [fdb_a].[RETCGCH0]
GO
CREATE SYNONYM [dbo].[RETCHCH0] FOR [fdb_a].[RETCHCH0]
GO
CREATE SYNONYM [dbo].[RETCHCL0] FOR [fdb_a].[RETCHCL0]
GO
CREATE SYNONYM [dbo].[RETCHIC0] FOR [fdb_a].[RETCHIC0]
GO
CREATE SYNONYM [dbo].[RETCHLH0] FOR [fdb_a].[RETCHLH0]
GO
CREATE SYNONYM [dbo].[RETCMDH0] FOR [fdb_a].[RETCMDH0]
GO
CREATE SYNONYM [dbo].[RETCMED0] FOR [fdb_a].[RETCMED0]
GO
CREATE SYNONYM [dbo].[RETCMNM0] FOR [fdb_a].[RETCMNM0]
GO
CREATE SYNONYM [dbo].[RETCNDC0] FOR [fdb_a].[RETCNDC0]
GO
CREATE SYNONYM [dbo].[RETCNDH0] FOR [fdb_a].[RETCNDH0]
GO
CREATE SYNONYM [dbo].[RETCNMH0] FOR [fdb_a].[RETCNMH0]
GO
CREATE SYNONYM [dbo].[RETCSCH0] FOR [fdb_a].[RETCSCH0]
GO
CREATE SYNONYM [dbo].[RETCTBL0] FOR [fdb_a].[RETCTBL0]
GO
CREATE SYNONYM [dbo].[RETCXRF0] FOR [fdb_a].[RETCXRF0]
GO
CREATE SYNONYM [dbo].[REVDEL0] FOR [fdb_a].[REVDEL0]
GO
CREATE SYNONYM [dbo].[REVDEL0_Active_Med] FOR [fdb_a].[REVDEL0_Active_Med]
GO
CREATE SYNONYM [dbo].[REVDEV0] FOR [fdb_a].[REVDEV0]
GO
CREATE SYNONYM [dbo].[REVDLT0] FOR [fdb_a].[REVDLT0]
GO
CREATE SYNONYM [dbo].[REVDVS0] FOR [fdb_a].[REVDVS0]
GO
CREATE SYNONYM [dbo].[REVDVT0] FOR [fdb_a].[REVDVT0]
GO
CREATE SYNONYM [dbo].[RGCN0] FOR [fdb_a].[RGCN0]
GO
CREATE SYNONYM [dbo].[RGCNINH0] FOR [fdb_a].[RGCNINH0]
GO
CREATE SYNONYM [dbo].[RGCNINS0] FOR [fdb_a].[RGCNINS0]
GO
CREATE SYNONYM [dbo].[RGCNSEQ4] FOR [fdb_a].[RGCNSEQ4]
GO
CREATE SYNONYM [dbo].[RGCNSTR0] FOR [fdb_a].[RGCNSTR0]
GO
CREATE SYNONYM [dbo].[RGTCD0] FOR [fdb_a].[RGTCD0]
GO
CREATE SYNONYM [dbo].[RHIC1D2] FOR [fdb_a].[RHIC1D2]
GO
CREATE SYNONYM [dbo].[RHIC2D3] FOR [fdb_a].[RHIC2D3]
GO
CREATE SYNONYM [dbo].[RHIC3D3] FOR [fdb_a].[RHIC3D3]
GO
CREATE SYNONYM [dbo].[RHIC3L2] FOR [fdb_a].[RHIC3L2]
GO
CREATE SYNONYM [dbo].[RHIC4D2] FOR [fdb_a].[RHIC4D2]
GO
CREATE SYNONYM [dbo].[RHICCAS1] FOR [fdb_a].[RHICCAS1]
GO
CREATE SYNONYM [dbo].[RHICD5] FOR [fdb_a].[RHICD5]
GO
CREATE SYNONYM [dbo].[RHICHCR0] FOR [fdb_a].[RHICHCR0]
GO
CREATE SYNONYM [dbo].[RHICL1] FOR [fdb_a].[RHICL1]
GO
CREATE SYNONYM [dbo].[RHICLSQ1] FOR [fdb_a].[RHICLSQ1]
GO
CREATE SYNONYM [dbo].[RHICRH0] FOR [fdb_a].[RHICRH0]
GO
CREATE SYNONYM [dbo].[RHICSCD0] FOR [fdb_a].[RHICSCD0]
GO
CREATE SYNONYM [dbo].[RLBLRID3] FOR [fdb_a].[RLBLRID3]
GO
CREATE SYNONYM [dbo].[RLBLWD0] FOR [fdb_a].[RLBLWD0]
GO
CREATE SYNONYM [dbo].[RLBLWGC0] FOR [fdb_a].[RLBLWGC0]
GO
CREATE SYNONYM [dbo].[RLBLWV0] FOR [fdb_a].[RLBLWV0]
GO
CREATE SYNONYM [dbo].[RLBLWVD0] FOR [fdb_a].[RLBLWVD0]
GO
CREATE SYNONYM [dbo].[RMEDCD0] FOR [fdb_a].[RMEDCD0]
GO
CREATE SYNONYM [dbo].[RMEDDIN0] FOR [fdb_a].[RMEDDIN0]
GO
CREATE SYNONYM [dbo].[RMEDDIS0] FOR [fdb_a].[RMEDDIS0]
GO
CREATE SYNONYM [dbo].[RMEDIN0] FOR [fdb_a].[RMEDIN0]
GO
CREATE SYNONYM [dbo].[RMEDIS0] FOR [fdb_a].[RMEDIS0]
GO
CREATE SYNONYM [dbo].[RMEDMGL0] FOR [fdb_a].[RMEDMGL0]
GO
CREATE SYNONYM [dbo].[RMEDMHL0] FOR [fdb_a].[RMEDMHL0]
GO
CREATE SYNONYM [dbo].[RMEDNIN0] FOR [fdb_a].[RMEDNIN0]
GO
CREATE SYNONYM [dbo].[RMEDNIS0] FOR [fdb_a].[RMEDNIS0]
GO
CREATE SYNONYM [dbo].[RMEDRIN0] FOR [fdb_a].[RMEDRIN0]
GO
CREATE SYNONYM [dbo].[RMEDRIS0] FOR [fdb_a].[RMEDRIS0]
GO
CREATE SYNONYM [dbo].[RMIDE2D1] FOR [fdb_a].[RMIDE2D1]
GO
CREATE SYNONYM [dbo].[RMIDEAD1] FOR [fdb_a].[RMIDEAD1]
GO
CREATE SYNONYM [dbo].[RMIDESD1] FOR [fdb_a].[RMIDESD1]
GO
CREATE SYNONYM [dbo].[RMIDFD1] FOR [fdb_a].[RMIDFD1]
GO
CREATE SYNONYM [dbo].[RMIDFID1] FOR [fdb_a].[RMIDFID1]
GO
CREATE SYNONYM [dbo].[RMIDFRH1] FOR [fdb_a].[RMIDFRH1]
GO
CREATE SYNONYM [dbo].[RMIGC1] FOR [fdb_a].[RMIGC1]
GO
CREATE SYNONYM [dbo].[RMIGCND1] FOR [fdb_a].[RMIGCND1]
GO
CREATE SYNONYM [dbo].[RMIGECD1] FOR [fdb_a].[RMIGECD1]
GO
CREATE SYNONYM [dbo].[RMIGNCD1] FOR [fdb_a].[RMIGNCD1]
GO
CREATE SYNONYM [dbo].[RMIGPCD1] FOR [fdb_a].[RMIGPCD1]
GO
CREATE SYNONYM [dbo].[RMIGSCD1] FOR [fdb_a].[RMIGSCD1]
GO
CREATE SYNONYM [dbo].[RMIID1] FOR [fdb_a].[RMIID1]
GO
CREATE SYNONYM [dbo].[RMIINND1] FOR [fdb_a].[RMIINND1]
GO
CREATE SYNONYM [dbo].[RMILGND1] FOR [fdb_a].[RMILGND1]
GO
CREATE SYNONYM [dbo].[RMIMLTD1] FOR [fdb_a].[RMIMLTD1]
GO
CREATE SYNONYM [dbo].[RMINAMD1] FOR [fdb_a].[RMINAMD1]
GO
CREATE SYNONYM [dbo].[RMINDC1] FOR [fdb_a].[RMINDC1]
GO
CREATE SYNONYM [dbo].[RMINMD1] FOR [fdb_a].[RMINMD1]
GO
CREATE SYNONYM [dbo].[RMINMID1] FOR [fdb_a].[RMINMID1]
GO
CREATE SYNONYM [dbo].[RMINMRH1] FOR [fdb_a].[RMINMRH1]
GO
CREATE SYNONYM [dbo].[RMIRH1] FOR [fdb_a].[RMIRH1]
GO
CREATE SYNONYM [dbo].[RMIRMID1] FOR [fdb_a].[RMIRMID1]
GO
CREATE SYNONYM [dbo].[RMIRMRH1] FOR [fdb_a].[RMIRMRH1]
GO
CREATE SYNONYM [dbo].[RMIRTD1] FOR [fdb_a].[RMIRTD1]
GO
CREATE SYNONYM [dbo].[RMISCD1] FOR [fdb_a].[RMISCD1]
GO
CREATE SYNONYM [dbo].[RMMADMA1] FOR [fdb_a].[RMMADMA1]
GO
CREATE SYNONYM [dbo].[RMMARMA0] FOR [fdb_a].[RMMARMA0]
GO
CREATE SYNONYM [dbo].[RMMGDMA0] FOR [fdb_a].[RMMGDMA0]
GO
CREATE SYNONYM [dbo].[RMMGRMA0] FOR [fdb_a].[RMMGRMA0]
GO
CREATE SYNONYM [dbo].[RMTLAID0] FOR [fdb_a].[RMTLAID0]
GO
CREATE SYNONYM [dbo].[RMTLEVL0] FOR [fdb_a].[RMTLEVL0]
GO
CREATE SYNONYM [dbo].[RMTLITD0] FOR [fdb_a].[RMTLITD0]
GO
CREATE SYNONYM [dbo].[RMTLLAB0] FOR [fdb_a].[RMTLLAB0]
GO
CREATE SYNONYM [dbo].[RMTLLRH0] FOR [fdb_a].[RMTLLRH0]
GO
CREATE SYNONYM [dbo].[RMTLLSD0] FOR [fdb_a].[RMTLLSD0]
GO
CREATE SYNONYM [dbo].[RMTLMID0] FOR [fdb_a].[RMTLMID0]
GO
CREATE SYNONYM [dbo].[RMTLPID0] FOR [fdb_a].[RMTLPID0]
GO
CREATE SYNONYM [dbo].[RMTLPLB0] FOR [fdb_a].[RMTLPLB0]
GO
CREATE SYNONYM [dbo].[RMTLPRH0] FOR [fdb_a].[RMTLPRH0]
GO
CREATE SYNONYM [dbo].[RMTLPSD0] FOR [fdb_a].[RMTLPSD0]
GO
CREATE SYNONYM [dbo].[RMTLSCD0] FOR [fdb_a].[RMTLSCD0]
GO
CREATE SYNONYM [dbo].[RMTLSID0] FOR [fdb_a].[RMTLSID0]
GO
CREATE SYNONYM [dbo].[RMTLSLT0] FOR [fdb_a].[RMTLSLT0]
GO
CREATE SYNONYM [dbo].[RMTLSND0] FOR [fdb_a].[RMTLSND0]
GO
CREATE SYNONYM [dbo].[RMTLSRH0] FOR [fdb_a].[RMTLSRH0]
GO
CREATE SYNONYM [dbo].[RMTLSSD0] FOR [fdb_a].[RMTLSSD0]
GO
CREATE SYNONYM [dbo].[RMTLSYN0] FOR [fdb_a].[RMTLSYN0]
GO
CREATE SYNONYM [dbo].[RMTLVTD0] FOR [fdb_a].[RMTLVTD0]
GO
CREATE SYNONYM [dbo].[RNDC14] FOR [fdb_a].[RNDC14]
GO
CREATE SYNONYM [dbo].[RNDCINH0] FOR [fdb_a].[RNDCINH0]
GO
CREATE SYNONYM [dbo].[RNDCINR0] FOR [fdb_a].[RNDCINR0]
GO
CREATE SYNONYM [dbo].[RNMMIDNDC] FOR [fdb_a].[RNMMIDNDC]
GO
CREATE SYNONYM [dbo].[RNP2] FOR [fdb_a].[RNP2]
GO
CREATE SYNONYM [dbo].[RNPTYPD0] FOR [fdb_a].[RNPTYPD0]
GO
CREATE SYNONYM [dbo].[ROBCD0] FOR [fdb_a].[ROBCD0]
GO
CREATE SYNONYM [dbo].[ROBCNDC0] FOR [fdb_a].[ROBCNDC0]
GO
CREATE SYNONYM [dbo].[RPDMMA0] FOR [fdb_a].[RPDMMA0]
GO
CREATE SYNONYM [dbo].[RPDMUND0] FOR [fdb_a].[RPDMUND0]
GO
CREATE SYNONYM [dbo].[RPDMWT1] FOR [fdb_a].[RPDMWT1]
GO
CREATE SYNONYM [dbo].[RPEMGC0] FOR [fdb_a].[RPEMGC0]
GO
CREATE SYNONYM [dbo].[RPEMMA5] FOR [fdb_a].[RPEMMA5]
GO
CREATE SYNONYM [dbo].[RPEMMOE2] FOR [fdb_a].[RPEMMOE2]
GO
CREATE SYNONYM [dbo].[RPEMOGC0] FOR [fdb_a].[RPEMOGC0]
GO
CREATE SYNONYM [dbo].[RPEMORG0] FOR [fdb_a].[RPEMORG0]
GO
CREATE SYNONYM [dbo].[RPEMRG0] FOR [fdb_a].[RPEMRG0]
GO
CREATE SYNONYM [dbo].[RROUTED3] FOR [fdb_a].[RROUTED3]
GO
CREATE SYNONYM [dbo].[RRTGN0] FOR [fdb_a].[RRTGN0]
GO
CREATE SYNONYM [dbo].[RRTGNGC0] FOR [fdb_a].[RRTGNGC0]
GO
CREATE SYNONYM [dbo].[RRTGNND0] FOR [fdb_a].[RRTGNND0]
GO
CREATE SYNONYM [dbo].[RRTGNSD0] FOR [fdb_a].[RRTGNSD0]
GO
CREATE SYNONYM [dbo].[RSTR1] FOR [fdb_a].[RSTR1]
GO
CREATE SYNONYM [dbo].[RSTRSCD0] FOR [fdb_a].[RSTRSCD0]
GO
CREATE SYNONYM [dbo].[RSTRTD0] FOR [fdb_a].[RSTRTD0]
GO
CREATE SYNONYM [dbo].[RSTRUOM0] FOR [fdb_a].[RSTRUOM0]
GO
CREATE SYNONYM [dbo].[RTCD0] FOR [fdb_a].[RTCD0]
GO
CREATE SYNONYM [dbo].[RTMDFID0] FOR [fdb_a].[RTMDFID0]
GO
CREATE SYNONYM [dbo].[RTMGRPD0] FOR [fdb_a].[RTMGRPD0]
GO
CREATE SYNONYM [dbo].[RTMMID0] FOR [fdb_a].[RTMMID0]
GO
CREATE SYNONYM [dbo].[RTMNMID0] FOR [fdb_a].[RTMNMID0]
GO
CREATE SYNONYM [dbo].[RTMRMID0] FOR [fdb_a].[RTMRMID0]
GO
CREATE SYNONYM [dbo].[RTMSRCD0] FOR [fdb_a].[RTMSRCD0]
GO
CREATE SYNONYM [dbo].[RUNITSD0] FOR [fdb_a].[RUNITSD0]
GO
CREATE SYNONYM [dbo].[RXRFAHX0] FOR [fdb_a].[RXRFAHX0]
GO
CREATE SYNONYM [dbo].[RXRFDDX0] FOR [fdb_a].[RXRFDDX0]
GO
