SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW RPACKAGEDDRUG AS SELECT NDC,GCN_SEQNO, '1' GMI, ROUTED_DOSAGE_FORM_MED_ID, MEDID, MED_REF_DEA_CD, LBLRID, LN, '' MFG, LN25, BN, GPI, REPACK, OBSDTEC FROM RNMMIDNDC 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
