SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW [dbo].[vwMedGCN]
AS
SELECT  MEDID,MAX(CASE WHEN GCN_STRING IS NULL THEN '' ELSE GCN_STRING END) AS GCN_SEQNO
FROM RMIID1 R1 with(nolock) 
--LEFT OUTER JOIN RGCN0 RV WITH(NOLOCK) ON R1.GCN_SEQNO = RV.GCN_SEQNO 
GROUP BY MEDID
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
