SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW vwRxNormCodes
AS 
WITH CTE AS
(
Select *,Row_Number()OVER(PARTITION BY Medid ORDER BY Medid) RN from (
select 0 as RefMode, EVD_EXT_VOCAB_TYPE_ID,R2.EVD_VOCAB_TYPE_DESC,EVD_EXT_VOCAB_ID as RxNormCode, EVD_FDB_VOCAB_ID as Medid
				from  REVDEL0 R1 WITH(NOLOCK) inner join REVDVT0 R2 WITH(NOLOCK) on R1.EVD_EXT_VOCAB_TYPE_ID=R2.EVD_VOCAB_TYPE_ID
				INNER JOIN RMIID1 R3 ON EVD_FDB_VOCAB_ID = R3.MEDID 
				where EVD_FDB_VOCAB_TYPE_ID=3 AND EVD_EXT_VOCAB_TYPE_ID in (502,504,505) AND R3.med_ref_gen_drug_name_cd =  2
			UNION ALL
			SELECT 1 as RefMode, EVD_EXT_VOCAB_TYPE_ID,R2.EVD_VOCAB_TYPE_DESC,EVD_EXT_VOCAB_ID as RxNormCode, EVD_FDB_VOCAB_ID as MedId from REVDEL0 R1 WITH(NOLOCK) 
				inner join REVDVT0 R2 WITH(NOLOCK) on R1.EVD_EXT_VOCAB_TYPE_ID=R2.EVD_VOCAB_TYPE_ID 
				where EVD_FDB_VOCAB_TYPE_ID=3 AND EVD_EXT_VOCAB_TYPE_ID in (501,503)
) as res)
Select * from CTE WHERE RN = 1  
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
