version: "3.9"
services:
  sql:
    ports:
      - "1433:1433" # May cause conflict if another SQL edition is running locally
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sql1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Apex@2023
