CREATE TABLE [bk].[patient_vitals] (
   [pa_vt_id] [int] NOT NULL,
   [pa_id] [int] NOT NULL,
   [pa_wt] [float] NOT NULL,
   [pa_ht] [float] NOT NULL,
   [pa_pulse] [float] NOT NULL,
   [pa_bp_sys] [float] NOT NULL,
   [pa_bp_dys] [float] NOT NULL,
   [pa_glucose] [float] NOT NULL,
   [pa_resp_rate] [float] NOT NULL,
   [pa_temp] [float] NOT NULL,
   [pa_bmi] [float] NOT NULL,
   [age] [int] NOT NULL,
   [date_added] [datetime] NOT NULL,
   [dg_id] [int] NOT NULL,
   [added_by] [int] NOT NULL,
   [added_for] [int] NOT NULL,
   [record_date] [datetime] NOT NULL,
   [pa_oxm] [float] NOT NULL,
   [record_modified_date] [datetime] NULL,
   [pa_hc] [float] NOT NULL,
   [pa_bp_location] [int] NULL,
   [pa_bp_sys_statnding] [float] NULL,
   [pa_bp_dys_statnding] [float] NULL,
   [pa_bp_location_statnding] [int] NULL,
   [pa_bp_sys_supine] [float] NULL,
   [pa_bp_dys_supine] [float] NULL,
   [pa_bp_location_supine] [int] NULL,
   [pa_temp_method] [int] NULL,
   [pa_pulse_rhythm] [int] NULL,
   [pa_pulse_standing] [float] NULL,
   [pa_pulse_rhythm_standing] [int] NULL,
   [pa_pulse_supine] [float] NULL,
   [pa_pulse_rhythm_supine] [int] NULL,
   [pa_heart_rate] [float] NULL,
   [pa_fio2] [float] NULL,
   [pa_flow] [float] NULL,
   [pa_resp_quality] [int] NULL,
   [pa_comment] [varchar](max) NULL,
   [created_date] [datetime] NOT NULL,
   [active] [bit] NULL,
   [last_modified_date] [datetime] NULL,
   [last_modified_by] [int] NULL,
   [pa_merge_reqid] [bigint] NULL,
   [PatientUnmergeRequestId] [bigint] NULL
)


GO
