CREATE TABLE [bk].[patient_extended_details] (
   [pa_id] [int] NOT NULL,
   [pa_ext_ref] [bit] NOT NULL,
   [pa_ref_name_details] [varchar](255) NULL,
   [pa_ref_date] [smalldatetime] NULL,
   [prim_dr_id] [int] NOT NULL,
   [dr_id] [int] NOT NULL,
   [cell_phone] [varchar](50) NULL,
   [marital_status] [tinyint] NULL,
   [empl_status] [tinyint] NULL,
   [work_phone] [varchar](50) NULL,
   [other_phone] [varchar](50) NULL,
   [comm_pref] [tinyint] NULL,
   [pref_phone] [tinyint] NULL,
   [time_zone] [varchar](6) NULL,
   [pref_start_time] [time] NULL,
   [pref_end_time] [time] NULL,
   [mother_first] [varchar](35) NULL,
   [mother_middle] [varchar](35) NULL,
   [mother_last] [varchar](35) NULL,
   [pa_death_date] [smalldatetime] NULL,
   [emergency_contact_first] [varchar](35) NULL,
   [emergency_contact_last] [varchar](35) NULL,
   [emergency_contact_address1] [varchar](100) NULL,
   [emergency_contact_address2] [varchar](100) NULL,
   [emergency_contact_city] [varchar](50) NULL,
   [emergency_contact_state] [varchar](2) NULL,
   [emergency_contact_zip] [varchar](20) NULL,
   [emergency_contact_phone] [varchar](20) NULL,
   [emergency_contact_release_documents] [bit] NULL,
   [emergency_contact_relationship] [varchar](3) NULL,
   [created_date] [datetime] NOT NULL,
   [active] [bit] NULL,
   [last_modified_date] [datetime] NULL,
   [last_modified_by] [int] NULL,
   [pa_merge_reqid] [bigint] NULL,
   [PatientUnmergeRequestId] [bigint] NULL
)


GO
