CREATE TABLE [dbo].[doctors] (
   [dr_id] [int] NOT NULL
      IDENTITY (1,1),
   [dg_id] [int] NULL,
   [dr_field_not_used1] [int] NULL,
   [dr_username] [varchar](50) NULL,
   [dr_password] [varchar](250) NULL,
   [dr_prefix] [varchar](10) NULL,
   [dr_first_name] [varchar](50) NULL,
   [dr_middle_initial] [varchar](20) NULL,
   [dr_last_name] [varchar](50) NULL,
   [dr_suffix] [varchar](20) NULL,
   [dr_address1] [varchar](100) NULL,
   [dr_address2] [varchar](100) NULL,
   [dr_city] [varchar](50) NULL,
   [dr_state] [varchar](30) NULL,
   [dr_zip] [varchar](20) NULL,
   [dr_phone] [varchar](30) NULL,
   [dr_phone_alt1] [varchar](30) NULL,
   [dr_phone_alt2] [varchar](30) NULL,
   [dr_phone_emerg] [varchar](30) NULL,
   [dr_fax] [varchar](30) NULL,
   [dr_email] [varchar](50) NULL,
   [dr_lic_numb] [varchar](50) NULL,
   [dr_lic_state] [varchar](30) NULL,
   [dr_dea_numb] [varchar](30) NULL,
   [dr_sig_file] [varchar](100) NOT NULL,
   [dr_sig_width] [varchar](4) NOT NULL,
   [dr_sig_height] [varchar](4) NOT NULL,
   [dr_create_date] [datetime] NOT NULL,
   [dr_enabled] [bit] NOT NULL,
   [dr_ma] [bit] NOT NULL,
   [prim_dr_id] [int] NOT NULL,
   [dr_last_pat_id] [varchar](30) NOT NULL,
   [dr_last_phrm_id] [varchar](30) NOT NULL,
   [dr_def_pharm_state] [varchar](2) NOT NULL,
   [dr_def_pharm_city] [varchar](50) NOT NULL,
   [dr_palm_dev_id] [varchar](30) NOT NULL,
   [dr_palm_conn_time] [datetime] NOT NULL,
   [dr_exp_date] [datetime] NULL,
   [dr_agreement_acptd] [bit] NOT NULL,
   [dr_logoff_int] [int] NOT NULL,
   [dr_pharm_search_opt] [int] NOT NULL,
   [dr_logged_in] [bit] NOT NULL,
   [dr_session_id] [varchar](255) NULL,
   [time_difference] [int] NULL,
   [hipaa_agreement_acptd] [bit] NOT NULL,
   [fav_patients_criteria] [int] NOT NULL,
   [activated_date] [datetime] NULL,
   [deactivated_date] [datetime] NULL,
   [dr_type] [int] NOT NULL,
   [prescribing_authority] [int] NOT NULL,
   [medco_target_physician] [int] NOT NULL,
   [sfi_docid] [varchar](255) NULL,
   [sfi_docpracticename] [varchar](255) NULL,
   [sfi_is_sfi] [bit] NOT NULL,
   [sfi_login] [varchar](50) NULL,
   [sfi_encrypted_password] [varchar](50) NULL,
   [sfi_password_decrypted] [bit] NOT NULL,
   [medco_reported] [smalldatetime] NULL,
   [report_print_date] [smalldatetime] NOT NULL,
   [dr_def_print_options] [smallint] NULL,
   [dr_def_no_pharm_print_options] [smallint] NULL,
   [dr_def_pat_history_back_to] [smallint] NULL,
   [dr_last_alias_dr_id] [int] NULL,
   [dr_last_auth_dr_id] [int] NULL,
   [dr_def_rxcard_history_back_to] [smallint] NULL,
   [dr_rxcard_search_consent_type] [varchar](50) NULL,
   [dr_dea_hidden] [bit] NOT NULL,
   [dr_opt_two_printers] [bit] NULL,
   [office_contact_name] [varchar](50) NULL,
   [office_contact_email] [varchar](50) NULL,
   [office_contact_phone] [varchar](50) NULL,
   [best_call_time] [varchar](50) NULL,
   [practice_mgmt_sys] [varchar](50) NULL,
   [internet_connect_type] [varchar](50) NULL,
   [pda_type] [varchar](50) NULL,
   [how_heard_about] [varchar](50) NULL,
   [numb_dr_in_practice] [int] NULL,
   [is_sub_practice] [bit] NULL,
   [use_pda] [bit] NULL,
   [professional_designation] [varchar](50) NULL,
   [medco_rebilled] [bit] NULL,
   [rxhub_reported] [smalldatetime] NULL,
   [medco_rebill_date] [smalldatetime] NULL,
   [dr_first_login_date] [datetime] NULL,
   [dr_force_pass_change] [bit] NOT NULL,
   [rxhub_reportable] [bit] NULL,
   [dr_dea_suffix] [varchar](10) NULL,
   [spi_id] [varchar](19) NULL,
   [password_expiry_date] [smalldatetime] NULL,
   [ss_enable] [bit] NULL,
   [dr_speciality_code] [varchar](50) NULL,
   [dr_view_group_prescriptions] [int] NOT NULL,
   [epocrates_active] [bit] NOT NULL,
   [billing_enabled] [bit] NOT NULL,
   [rights] [bigint] NOT NULL,
   [dr_promo] [varchar](50) NULL,
   [NPI] [varchar](30) NULL,
   [AvgNumb] [int] NULL,
   [printpref] [smallint] NULL,
   [beta_tester] [bit] NULL,
   [DR_SEVERITY] [tinyint] NOT NULL,
   [sales_person_id] [smallint] NULL,
   [dr_status] [smallint] NOT NULL,
   [lab_enabled] [bit] NULL,
   [lowusage_lock] [bit] NOT NULL,
   [loginlock] [bit] NOT NULL,
   [loginattempts] [tinyint] NOT NULL,
   [msg_alert_cell_number] [varchar](20) NULL,
   [commpreference] [char](1) NULL,
   [epcs_enabled] [bit] NULL,
   [billingDate] [datetime] NULL,
   [salt] [varchar](250) NULL,
   [timezone] [varchar](10) NULL,
   [isMigrated] [bit] NOT NULL,
   [IsEmailVerified] [bit] NOT NULL,
   [IsEmailVerificationPending] [bit] NOT NULL,
   [low_usage_removed_date] [datetime] NULL

   ,CONSTRAINT [PK_doctors] PRIMARY KEY NONCLUSTERED ([dr_id])
)

CREATE NONCLUSTERED INDEX [_dta_index_doctors_23_1927066001__K1_K2_7_9_97] ON [dbo].[doctors] ([dr_id], [dg_id]) INCLUDE ([dr_first_name], [dr_last_name], [NPI])
CREATE NONCLUSTERED INDEX [_dta_index_doctors_7_450868723__K1_7_9] ON [dbo].[doctors] ([dr_id]) INCLUDE ([dr_first_name], [dr_last_name])
CREATE NONCLUSTERED INDEX [_dta_index_doctors_7_450868723__K1_K2_6_7_9] ON [dbo].[doctors] ([dr_id], [dg_id]) INCLUDE ([dr_first_name], [dr_last_name], [dr_prefix])
CREATE NONCLUSTERED INDEX [_dta_index_doctors_7_450868723__K29_K51_K1_K2_7_9_24_97] ON [dbo].[doctors] ([dr_enabled], [medco_target_physician], [dr_id], [dg_id]) INCLUDE ([dr_dea_numb], [dr_first_name], [dr_last_name], [NPI])
CREATE CLUSTERED INDEX [doctors5] ON [dbo].[doctors] ([dg_id])
CREATE NONCLUSTERED INDEX [ix_doctors_dg_id_dr_enabled_lowusage_lock_loginlock_prescribing_authority] ON [dbo].[doctors] ([dg_id], [dr_enabled], [lowusage_lock], [loginlock], [prescribing_authority])
CREATE UNIQUE NONCLUSTERED INDEX [UserNameNoDups] ON [dbo].[doctors] ([dr_username])

GO
