CREATE TABLE [dbo].[doctor_info] (
   [dr_id] [int] NOT NULL,
   [dr_dea_address1] [varchar](100) NULL,
   [dr_dea_address2] [varchar](100) NULL,
   [dr_dea_city] [varchar](50) NULL,
   [dr_dea_state] [varchar](30) NULL,
   [dr_dea_zip] [varchar](20) NULL,
   [dr_dea_first_name] [varchar](50) NULL,
   [dr_dea_last_name] [varchar](50) NULL,
   [dr_dea_middle_initial] [varchar](20) NULL,
   [spectrum_id] [varchar](30) NULL,
   [blowusageemail] [bit] NOT NULL,
   [labcorp_id] [varchar](50) NULL,
   [securityset] [bit] NULL,
   [bduplicateuser] [bit] NULL,
   [is_coupon_enabled] [bit] NULL,
   [is_custom_tester] [int] NULL,
   [is_epcs] [bit] NULL,
   [IS_MUALERTS_ENABLED] [smallint] NULL,
   [settings] [smallint] NOT NULL,
   [system_level_cds] [int] NULL,
   [VersionURL] [varchar](200) NULL,
   [bOverrideDEA] [bit] NOT NULL,
   [encounter_version] [varchar](10) NULL,
   [vitals_unit_type] [varchar](5) NULL,
   [INLCUDE_ICD_Prescription] [bit] NULL,
   [return_to_prov_dashboard] [bit] NULL,
   [Add_Medications_To_My_Fav_Drugs] [bit] NULL,
   [EnableRulesEngine] [bit] NULL,
   [is_bannerads_enabled] [bit] NULL,
   [hide_walkme] [bit] NULL,
   [staff_preferred_prescriber] [bigint] NULL,
   [is_pain_scale_enabled] [bit] NULL,
   [dr_dea_certificate_external_id] [varchar](250) NULL,
   [dr_dea_certificate_file_name] [varchar](250) NULL,
   [dr_alternate_name_registered] [bit] NULL,
   [dr_prescribe_suboxone] [bit] NULL,
   [is_institutional_dea] [bit] NULL,
   [manual_encounter_forms_sort] [bit] NULL,
   [show_encounter_forms_sort_message] [bit] NULL,
   [dont_ignore_popup_on_patient_intake_sync] [bit] NULL,
   [hide_encounter_sign_confirmation_popup] [bit] NOT NULL,
   [dont_ignore_popup_on_doctor_sign_encounter] [bit] NOT NULL,
   [dont_ignore_popup_on_doctor_release_encounter] [bit] NULL

   ,CONSTRAINT [PK_doctor_info] PRIMARY KEY CLUSTERED ([dr_id])
)


GO
