CREATE TABLE [erx].[RxChangeRequests] (
   [ChgReqId] [bigint] NOT NULL
      IDENTITY (1,1),
   [DoctorGroupId] [int] NOT NULL,
   [DoctorId] [int] NOT NULL,
   [PatientId] [int] NOT NULL,
   [RequestDate] [datetime] NOT NULL,
   [PrescriberOrderNumber] [varchar](100) NULL,
   [MessageId] [varchar](100) NULL,
   [PresId] [int] NULL,
   [ChgType] [int] NULL,
   [InitDate] [datetime] NULL,
   [MsgDate] [datetime] NULL,
   [Status] [varchar](max) NULL,
   [DeliveryMethod] [bigint] NULL,
   [DocInfoText] [varchar](5000) NULL,
   [HasMissMatch] [bit] NULL,
   [MissMatchReason] [varchar](max) NULL,
   [DrugName] [varchar](125) NULL,
   [DrugNDC] [varchar](11) NULL,
   [DrugForm] [varchar](3) NULL,
   [DrugStrength] [varchar](70) NULL,
   [DrugStrengthUnits] [varchar](3) NULL,
   [Qty1] [varchar](35) NULL,
   [Qty1Units] [varchar](50) NULL,
   [Qty1Enum] [tinyint] NULL,
   [Qty2] [varchar](35) NULL,
   [Qty2Units] [varchar](50) NULL,
   [Qty2Enum] [tinyint] NULL,
   [Dosage1] [varchar](1000) NULL,
   [Dosage2] [varchar](70) NULL,
   [DaysSupply] [int] NULL,
   [Date1] [smalldatetime] NULL,
   [Date1Enum] [tinyint] NULL,
   [Date2] [smalldatetime] NULL,
   [Date2Enum] [tinyint] NULL,
   [Date3] [smalldatetime] NULL,
   [Date3Enum] [tinyint] NULL,
   [SubstitutionCode] [tinyint] NULL,
   [VoidComments] [varchar](255) NULL,
   [VoidCode] [smallint] NULL,
   [Comments1] [varchar](210) NULL,
   [Comments2] [varchar](70) NULL,
   [Comments3] [varchar](70) NULL,
   [DrugStrengthCode] [varchar](15) NULL,
   [DrugStrengthSourceCode] [varchar](3) NULL,
   [DrugFormCode] [varchar](15) NULL,
   [DrugFormSourceCode] [varchar](3) NULL,
   [Qty1UnitsPotencyCode] [varchar](15) NULL,
   [Qty2UnitsPotencyCode] [varchar](15) NULL,
   [DispDrugInfo] [bit] NULL,
   [Refills] [varchar](35) NULL,
   [RefillsType] [tinyint] NULL,
   [PharmSeg] [varchar](7999) NULL,
   [DoctorSeg] [varchar](7999) NULL,
   [SupervisorSeg] [varchar](7999) NULL,
   [PatientSeg] [varchar](5000) NULL,
   [ReqDrug] [varchar](max) NULL,
   [PrescDrug] [varchar](max) NULL,
   [FullReqMessage] [xml] NULL,
   [ResponseType] [int] NULL,
   [RequestSeg] [varchar](max) NULL,
   [PriorAuthNum] [varchar](100) NULL,
   [IsApproved] [bit] NULL,
   [IsVoided] [bit] NULL,
   [pharm_id] [int] NULL,
   [pharm_ncpdp] [varchar](15) NULL,
   [recverVector] [varchar](50) NULL,
   [senderVector] [varchar](50) NULL,
   [versionType] [varchar](5) NULL,
   [msg_ref_number] [varchar](35) NULL,
   [NoOfMedicationsRequested] [int] NULL,
   [ApprovedChgReqInfoId] [bigint] NULL

   ,CONSTRAINT [PK_RxChangeRequests] PRIMARY KEY CLUSTERED ([ChgReqId])
)


GO
