CREATE TABLE [dbo].[patient_extended_details] (
   [pa_id] [int] NOT NULL,
   [pa_ext_ref] [bit] NOT NULL,
   [pa_ref_name_details] [varchar](255) NULL,
   [pa_ref_date] [smalldatetime] NULL,
   [prim_dr_id] [int] NOT NULL,
   [dr_id] [int] NOT NULL,
   [cell_phone] [varchar](50) NULL,
   [marital_status] [tinyint] NULL,
   [empl_status] [tinyint] NULL,
   [work_phone] [varchar](50) NULL,
   [other_phone] [varchar](50) NULL,
   [comm_pref] [tinyint] NULL,
   [pref_phone] [tinyint] NULL,
   [time_zone] [varchar](6) NULL,
   [pref_start_time] [time] NULL,
   [pref_end_time] [time] NULL,
   [mother_first] [varchar](35) NULL,
   [mother_middle] [varchar](35) NULL,
   [mother_last] [varchar](35) NULL,
   [pa_death_date] [smalldatetime] NULL,
   [emergency_contact_first] [varchar](35) NULL,
   [emergency_contact_last] [varchar](35) NULL,
   [emergency_contact_address1] [varchar](100) NULL,
   [emergency_contact_address2] [varchar](100) NULL,
   [emergency_contact_city] [varchar](50) NULL,
   [emergency_contact_state] [varchar](2) NULL,
   [emergency_contact_zip] [varchar](20) NULL,
   [emergency_contact_phone] [varchar](20) NULL,
   [emergency_contact_relationship] [varchar](3) NULL,
   [emergency_contact_release_documents] [bit] NULL,
   [active] [bit] NULL,
   [last_modified_date] [datetime] NULL,
   [last_modified_by] [int] NULL,
   [created_by_system] [varchar](50) NULL,
   [pa_phone_ctry_code] [varchar](5) NULL,
   [cell_phone_ctry_code] [varchar](5) NULL,
   [work_phone_ctry_code] [varchar](5) NULL,
   [other_phone_ctry_code] [varchar](5) NULL,
   [pa_phone_dial_code] [varchar](5) NULL,
   [cell_phone_dial_code] [varchar](5) NULL,
   [work_phone_dial_code] [varchar](5) NULL,
   [other_phone_dial_code] [varchar](5) NULL,
   [pa_phone_full] [varchar](30) NULL,
   [cell_phone_full] [varchar](30) NULL,
   [work_phone_full] [varchar](30) NULL,
   [other_phone_full] [varchar](30) NULL,
   [restricted_access] [int] NULL,
   [pa_sexual_orientation] [tinyint] NULL,
   [pa_sexual_orientation_detail] [varchar](200) NULL,
   [pa_gender_identity_detail] [varchar](200) NULL,
   [pa_gender_identity] [tinyint] NULL,
   [pa_death_cause] [varchar](100) NULL,
   [pa_nick_name] [varchar](50) NULL,
   [is_patient_intake_sync_review_pending] [bit] NULL,
   [pa_previous_name] [varchar](50) NULL,
   [pa_previous_address_1] [varchar](100) NULL,
   [pa_previous_address_2] [varchar](100) NULL,
   [pa_previous_address_state] [varchar](2) NULL,
   [pa_previous_address_city] [varchar](50) NULL,
   [pa_previous_address_zip] [varchar](20) NULL

   ,CONSTRAINT [PK_patient_extended_details] PRIMARY KEY CLUSTERED ([pa_id])
)


GO
