CREATE TABLE [dbo].[patients_20447] (
   [pa_id] [int] NULL,
   [pa_field_not_used1] [int] NULL,
   [dg_id] [int] NOT NULL,
   [dr_id] [int] NOT NULL,
   [pa_first] [varchar](50) NOT NULL,
   [pa_middle] [varchar](50) NOT NULL,
   [pa_last] [varchar](61) NULL,
   [pa_ssn] [varchar](50) NULL,
   [pa_dob] [smalldatetime] NULL,
   [pa_address1] [varchar](100) NOT NULL,
   [pa_address2] [varchar](100) NOT NULL,
   [pa_city] [varchar](50) NOT NULL,
   [pa_state] [varchar](2) NOT NULL,
   [pa_zip] [varchar](20) NOT NULL,
   [pa_phone] [varchar](20) NOT NULL,
   [pa_wgt] [int] NOT NULL,
   [pa_sex] [varchar](1) NOT NULL,
   [ic_id] [int] NOT NULL,
   [ic_group_numb] [varchar](30) NOT NULL,
   [card_holder_id] [varchar](30) NOT NULL,
   [card_holder_first] [varchar](50) NOT NULL,
   [card_holder_mi] [varchar](1) NOT NULL,
   [card_holder_last] [varchar](50) NOT NULL,
   [ic_plan_numb] [varchar](30) NOT NULL,
   [ins_relate_code] [varchar](4) NOT NULL,
   [ins_person_code] [varchar](4) NOT NULL,
   [formulary_id] [varchar](30) NOT NULL,
   [alternative_id] [varchar](30) NOT NULL,
   [pa_bin] [varchar](30) NOT NULL,
   [primary_pharm_id] [int] NULL,
   [pa_notes] [varchar](255) NULL,
   [ph_drugs] [varchar](100) NULL,
   [pa_email] [varchar](80) NULL,
   [pa_ext] [varchar](10) NULL,
   [rxhub_pbm_id] [varchar](15) NULL,
   [pbm_member_id] [varchar](80) NULL,
   [def_ins_id] [int] NOT NULL,
   [last_check_date] [smalldatetime] NOT NULL,
   [check_eligibility] [bit] NOT NULL,
   [sfi_is_sfi] [bit] NULL,
   [sfi_patid] [varchar](50) NULL,
   [pa_ht] [int] NOT NULL,
   [pa_upd_stat] [smallint] NULL,
   [pa_flag] [tinyint] NULL,
   [pa_ext_id] [varchar](20) NULL,
   [access_date] [datetime] NULL,
   [access_user] [int] NULL,
   [pa_ins_type] [tinyint] NULL,
   [pa_race_type] [tinyint] NULL,
   [pa_ethn_type] [tinyint] NULL,
   [pref_lang] [smallint] NULL,
   [add_date] [smalldatetime] NULL,
   [add_by_user] [int] NULL,
   [record_modified_date] [datetime] NULL,
   [pa_ext_ssn_no] [varchar](25) NULL,
   [pa_prefix] [varchar](10) NULL,
   [pa_suffix] [varchar](10) NULL
)


GO
