CREATE TABLE [dbo].[prescriptions_archive] (
   [pres_id] [int] NOT NULL,
   [dr_id] [int] NOT NULL,
   [dg_id] [int] NOT NULL,
   [pharm_id] [int] NOT NULL,
   [pa_id] [int] NOT NULL,
   [pres_entry_date] [datetime] NULL,
   [pres_read_date] [datetime] NULL,
   [only_faxed] [bit] NULL,
   [pharm_viewed] [bit] NOT NULL,
   [off_dr_list] [bit] NOT NULL,
   [opener_user_id] [int] NOT NULL,
   [pres_is_refill] [bit] NOT NULL,
   [rx_number] [varchar](50) NOT NULL,
   [last_pharm_name] [varchar](80) NOT NULL,
   [last_pharm_address] [varchar](50) NOT NULL,
   [last_pharm_city] [varchar](30) NOT NULL,
   [last_pharm_state] [varchar](30) NOT NULL,
   [last_pharm_phone] [varchar](30) NOT NULL,
   [pharm_state_holder] [varchar](50) NOT NULL,
   [pharm_city_holder] [varchar](50) NOT NULL,
   [pharm_id_holder] [varchar](20) NOT NULL,
   [fax_conf_send_date] [datetime] NULL,
   [fax_conf_numb_pages] [int] NULL,
   [fax_conf_remote_fax_id] [varchar](100) NULL,
   [fax_conf_error_string] [varchar](600) NULL,
   [pres_delivery_method] [int] NULL,
   [prim_dr_id] [int] NOT NULL,
   [print_count] [int] NOT NULL,
   [pda_written] [bit] NOT NULL,
   [authorizing_dr_id] [int] NULL,
   [sfi_is_sfi] [bit] NOT NULL,
   [sfi_pres_id] [varchar](50) NULL,
   [field_not_used1] [int] NULL,
   [admin_notes] [varchar](600) NULL,
   [pres_approved_date] [datetime] NULL,
   [pres_void] [bit] NULL,
   [last_edit_date] [datetime] NULL,
   [last_edit_dr_id] [int] NULL,
   [pres_prescription_type] [int] NULL,
   [pres_void_comments] [varchar](255) NULL,
   [eligibility_checked] [bit] NULL,
   [eligibility_trans_id] [int] NULL,
   [off_pharm_list] [bit] NOT NULL,
   [DoPrintAfterPatHistory] [bit] NOT NULL,
   [DoPrintAfterPatOrig] [bit] NOT NULL,
   [DoPrintAfterPatCopy] [bit] NOT NULL,
   [DoPrintAfterPatMonograph] [bit] NOT NULL,
   [PatOrigPrintType] [int] NOT NULL,
   [PrintHistoryBackMonths] [int] NOT NULL,
   [DoPrintAfterScriptGuide] [bit] NOT NULL,
   [approve_source] [varchar](1) NULL,
   [pres_void_code] [smallint] NULL,
   [send_count] [smallint] NOT NULL,
   [print_options] [int] NOT NULL,
   [writing_dr_id] [int] NULL,
   [presc_src] [tinyint] NULL,
   [pres_start_date] [datetime] NULL,
   [pres_end_date] [datetime] NULL,
   [is_signed] [bit] NULL

   ,CONSTRAINT [PK__prescrip__3CE2B63731B9C501] PRIMARY KEY CLUSTERED ([pres_id])
)

CREATE NONCLUSTERED INDEX [_dta_index_prescriptions_archive_23_491252905__K1_K3_K2_K5_K4_6_35_36_39_40] ON [dbo].[prescriptions_archive] ([pres_id], [dg_id], [dr_id], [pa_id], [pharm_id]) INCLUDE ([pres_entry_date], [pres_approved_date], [pres_void], [pres_prescription_type], [pres_void_comments])
CREATE NONCLUSTERED INDEX [_dta_index_prescriptions_archive_9_2011258320__K5_K36_K2_K1_K4_K35_K27_K57_K58] ON [dbo].[prescriptions_archive] ([pa_id], [pres_void], [dr_id], [pres_id], [pharm_id], [pres_approved_date], [prim_dr_id], [pres_start_date], [pres_end_date])
CREATE NONCLUSTERED INDEX [dtapres_id_archive] ON [dbo].[prescriptions_archive] ([pres_id])
CREATE NONCLUSTERED INDEX [IX_prescriptions_archive-dr_id-pres_void-pres_approved_date] ON [dbo].[prescriptions_archive] ([dr_id], [pres_void], [pres_approved_date]) INCLUDE ([pres_id], [pres_delivery_method])

GO
