CREATE TABLE [dbo].[refill_requests] (
   [refreq_id] [int] NOT NULL
      IDENTITY (1,1),
   [dg_id] [int] NOT NULL,
   [dr_id] [int] NOT NULL,
   [pa_id] [int] NOT NULL,
   [pharm_id] [int] NOT NULL,
   [pharm_ncpdp] [varchar](15) NULL,
   [refreq_date] [datetime] NOT NULL,
   [trc_number] [varchar](100) NULL,
   [ctrl_number] [varchar](100) NULL,
   [recverVector] [varchar](50) NULL,
   [senderVector] [varchar](50) NULL,
   [pres_id] [int] NULL,
   [response_type] [int] NULL,
   [init_date] [datetime] NULL,
   [msg_date] [datetime] NULL,
   [response_id] [varchar](15) NULL,
   [status_code] [varchar](15) NULL,
   [status_code_qualifier] [varchar](15) NULL,
   [status_msg] [varchar](255) NULL,
   [response_conf_date] [smalldatetime] NULL,
   [error_string] [varchar](255) NULL,
   [pres_fill_time] [datetime] NULL,
   [msg_ref_number] [varchar](35) NOT NULL,
   [drug_name] [varchar](125) NULL,
   [drug_ndc] [varchar](11) NULL,
   [drug_form] [varchar](3) NULL,
   [drug_strength] [varchar](70) NULL,
   [drug_strength_units] [varchar](3) NULL,
   [qty1] [varchar](35) NULL,
   [qty1_units] [varchar](50) NULL,
   [qty1_enum] [tinyint] NULL,
   [qty2] [varchar](35) NULL,
   [qty2_units] [varchar](50) NULL,
   [qty2_enum] [tinyint] NULL,
   [dosage1] [varchar](140) NULL,
   [dosage2] [varchar](70) NULL,
   [days_supply] [int] NULL,
   [date1] [smalldatetime] NULL,
   [date1_enum] [tinyint] NULL,
   [date2] [smalldatetime] NULL,
   [date2_enum] [tinyint] NULL,
   [date3] [smalldatetime] NULL,
   [date3_enum] [tinyint] NULL,
   [substitution_code] [tinyint] NULL,
   [refills] [varchar](35) NULL,
   [refills_enum] [tinyint] NULL,
   [void_comments] [varchar](255) NULL,
   [void_code] [smallint] NULL,
   [comments1] [varchar](210) NULL,
   [comments2] [varchar](70) NULL,
   [comments3] [varchar](70) NULL,
   [disp_drug_info] [bit] NOT NULL,
   [supervisor] [varchar](100) NULL,
   [SupervisorSeg] [varchar](5000) NULL,
   [PharmSeg] [varchar](5000) NULL,
   [PatientSeg] [varchar](5000) NULL,
   [DoctorSeg] [varchar](5000) NULL,
   [DispDRUSeg] [varchar](max) NULL,
   [PrescDRUSeg] [varchar](max) NULL,
   [drug_strength_code] [varchar](15) NULL,
   [drug_strength_source_code] [varchar](3) NULL,
   [drug_form_code] [varchar](15) NULL,
   [drug_form_source_code] [varchar](3) NULL,
   [qty1_units_potency_code] [varchar](15) NULL,
   [qty2_units_potency_code] [varchar](15) NULL,
   [doc_info_text] [varchar](5000) NULL,
   [fullRequestMessage] [xml] NULL,
   [versionType] [varchar](5) NULL,
   [has_miss_match] [bit] NULL,
   [miss_match_reson] [varchar](max) NULL

   ,CONSTRAINT [PK_refill_requests] PRIMARY KEY NONCLUSTERED ([refreq_id])
)

CREATE NONCLUSTERED INDEX [_dta_index_refill_requests_7_1336443885__K12_K1_38_39_40_41_42_43] ON [dbo].[refill_requests] ([pres_id], [refreq_id]) INCLUDE ([date1], [date1_enum], [date2], [date2_enum], [date3], [date3_enum])
CREATE NONCLUSTERED INDEX [IDX_refill_requests_pa_id] ON [dbo].[refill_requests] ([pa_id])
CREATE CLUSTERED INDEX [refill_requests1] ON [dbo].[refill_requests] ([pres_id])

GO
