SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[ufn_GetNDCByDrugId] 
(  
	@DrugId BIGINT
) 
	RETURNS VARCHAR(50)
BEGIN 
	DECLARE @NDC VARCHAR(20)
	SELECT TOP 1  @NDC=RNM.NDC
	FROM RNMMIDNDC RNM WITH(NOLOCK) 
	WHERE RNM.MEDID=@DrugId
	RETURN  @NDC
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
