CREATE TABLE [fdb_a].[RETCTBL0] (
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_NAME] [varchar](70) NULL,
   [ETC_ULTIMATE_CHILD_IND] [varchar](1) NULL,
   [ETC_DRUG_CONCEPT_LINK_IND] [varchar](1) NULL,
   [ETC_PARENT_ETC_ID] [numeric](8,0) NULL,
   [ETC_FORMULARY_LEVEL_IND] [varchar](1) NULL,
   [ETC_PRESENTATION_SEQNO] [numeric](5,0) NULL,
   [ETC_ULTIMATE_PARENT_ETC_ID] [numeric](8,0) NULL,
   [ETC_HIERARCHY_LEVEL] [numeric](2,0) NULL,
   [ETC_SORT_NUMBER] [numeric](5,0) NULL,
   [ETC_RETIRED_IND] [varchar](1) NULL,
   [ETC_RETIRED_DATE] [datetime] NULL

   ,CONSTRAINT [RETCTBL0_PK] PRIMARY KEY CLUSTERED ([ETC_ID])
)

CREATE NONCLUSTERED INDEX [_dta_index_RETCTBL0_10_818101955__K1_2] ON [fdb_a].[RETCTBL0] ([ETC_ID]) INCLUDE ([ETC_NAME])
CREATE NONCLUSTERED INDEX [RETCTBL0_NX1] ON [fdb_a].[RETCTBL0] ([ETC_PARENT_ETC_ID])
CREATE NONCLUSTERED INDEX [RETCTBL0_NX2] ON [fdb_a].[RETCTBL0] ([ETC_ULTIMATE_PARENT_ETC_ID])

GO
