CREATE TABLE [fdb_b].[RETCCTD0] (
   [ETC_CHANGE_TYPE_CODE] [varchar](1) NOT NULL,
   [ETC_CHANGE_TYPE_CODE_DESC] [varchar](90) NULL

   ,CONSTRAINT [RETCCTD0_PK] PRIMARY KEY CLUSTERED ([ETC_CHANGE_TYPE_CODE])
)


GO
