CREATE TABLE [fdb_a].[RDPTRG0] (
   [ROUTED_GEN_ID] [numeric](8,0) NOT NULL,
   [DPT_CLASS_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RDPTRG0_PK] PRIMARY KEY CLUSTERED ([ROUTED_GEN_ID], [DPT_CLASS_ID])
)


GO
