CREATE TABLE [fdb_b].[RMTLEVL0] (
   [MTL_EXTRN_VOCAB_TYP_CODE] [varchar](2) NOT NULL,
   [MTL_EXTRN_VOCAB_CODE] [varchar](20) NOT NULL,
   [MTL_FDB_ID_TYP_CODE] [varchar](2) NOT NULL,
   [MTL_FDB_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RMTLEVL0_PK] PRIMARY KEY CLUSTERED ([MTL_EXTRN_VOCAB_TYP_CODE], [MTL_EXTRN_VOCAB_CODE], [MTL_FDB_ID_TYP_CODE], [MTL_FDB_ID])
)


GO
