CREATE TABLE [fdb_a].[RMIDFD1] (
   [MED_DOSAGE_FORM_ID] [numeric](5,0) NOT NULL,
   [MED_DOSAGE_FORM_ABBR] [varchar](4) NOT NULL,
   [MED_DOSAGE_FORM_DESC] [varchar](30) NOT NULL

   ,CONSTRAINT [RMIDFD1_PK] PRIMARY KEY CLUSTERED ([MED_DOSAGE_FORM_ID])
)

CREATE NONCLUSTERED INDEX [RMIDFD1_NX1] ON [fdb_a].[RMIDFD1] ([MED_DOSAGE_FORM_ABBR])

GO
