CREATE TABLE [fdb_b].[RSTRTD0] (
   [STRENGTH_TYP_CODE] [numeric](1,0) NOT NULL,
   [STRENGTH_TYP_DESC] [varchar](100) NULL

   ,CONSTRAINT [RSTRTD0_PK] PRIMARY KEY CLUSTERED ([STRENGTH_TYP_CODE])
)


GO
