CREATE TABLE [fdb_b].[RETCHCH0] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_REVISION_SEQNO] [numeric](5,0) NOT NULL,
   [ETC_CHANGE_TYPE_CODE] [varchar](1) NULL,
   [ETC_EFFECTIVE_DATE] [datetime] NULL

   ,CONSTRAINT [RETCHCH0_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN], [ETC_ID], [ETC_REVISION_SEQNO])
)

CREATE NONCLUSTERED INDEX [RETCHCH0_NX1] ON [fdb_b].[RETCHCH0] ([ETC_ID])

GO
