CREATE TABLE [fdb_a].[RMIMLTD1] (
   [MED_REF_MULTI_SOURCE_CD] [varchar](1) NOT NULL,
   [MED_REF_MULTI_SOURCE_CD_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMIMLTD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_MULTI_SOURCE_CD])
)


GO
