CREATE TABLE [fdb_b].[RHIC3D3] (
   [HIC3_SEQN] [numeric](6,0) NOT NULL,
   [HIC3] [varchar](3) NOT NULL,
   [HIC3_DESC] [varchar](50) NULL,
   [HIC3_GRPN] [numeric](6,0) NULL,
   [HIC3_ROOT] [numeric](6,0) NULL

   ,CONSTRAINT [RHIC3D3_PK] PRIMARY KEY CLUSTERED ([HIC3_SEQN])
)

CREATE NONCLUSTERED INDEX [RHIC3D3_NX1] ON [fdb_b].[RHIC3D3] ([HIC3])
CREATE NONCLUSTERED INDEX [RHIC3D3_NX2] ON [fdb_b].[RHIC3D3] ([HIC3_ROOT])

GO
