CREATE TABLE [fdb_a].[RDLIMID0] (
   [DLIM_INTER_TYP_CODE] [varchar](2) NOT NULL,
   [DLIM_INTER_TYP_CODE_DESC] [varchar](50) NULL

   ,CONSTRAINT [RDLIMID0_PK] PRIMARY KEY CLUSTERED ([DLIM_INTER_TYP_CODE])
)


GO
