CREATE TABLE [fdb_b].[RETCNDH0] (
   [NDC] [varchar](11) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_REVISION_SEQNO] [numeric](5,0) NOT NULL,
   [ETC_COMMON_USE_IND] [varchar](1) NULL,
   [ETC_DEFAULT_USE_IND] [varchar](1) NULL,
   [ETC_CHANGE_TYPE_CODE] [varchar](1) NULL,
   [ETC_EFFECTIVE_DATE] [datetime] NULL

   ,CONSTRAINT [RETCNDH0_PK] PRIMARY KEY CLUSTERED ([NDC], [ETC_ID], [ETC_REVISION_SEQNO])
)

CREATE NONCLUSTERED INDEX [RETCNDH0_NX1] ON [fdb_b].[RETCNDH0] ([ETC_ID])

GO
