CREATE TABLE [fdb_a].[RMTLSCD0] (
   [MTL_SPEC_LAB_ID_STATUS] [char](1) NOT NULL,
   [MTL_SPEC_LAB_ID_STATUS_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLSCD0_PK] PRIMARY KEY CLUSTERED ([MTL_SPEC_LAB_ID_STATUS])
)


GO
