CREATE TABLE [fdb_b].[RMIDE2D1] (
   [MED_REF_DESI2_IND] [varchar](1) NOT NULL,
   [MED_REF_DESI2_IND_DESC] [varchar](60) NOT NULL

   ,CONSTRAINT [RMIDE2D1_PK] PRIMARY KEY CLUSTERED ([MED_REF_DESI2_IND])
)


GO
