CREATE TABLE [fdb_b].[RUNITSD0] (
   [DOSING_MODULE_UNIT_ABBREV] [varchar](30) NOT NULL,
   [UNIT_DESC_ABBREV] [varchar](30) NULL,
   [UNIT_DESC_EXPANDED] [varchar](60) NULL

   ,CONSTRAINT [RUNITSD0_PK] PRIMARY KEY CLUSTERED ([DOSING_MODULE_UNIT_ABBREV])
)


GO
