CREATE TABLE [fdb_b].[RHIC4D2] (
   [HIC4_SEQN] [numeric](6,0) NOT NULL,
   [HIC4] [varchar](4) NULL,
   [HIC4_DESC] [varchar](50) NULL,
   [HIC4_ROOT] [numeric](6,0) NULL,
   [HIC4_POTENTIALLY_INACTV_IND] [numeric](1,0) NULL,
   [ING_STATUS_CD] [numeric](1,0) NULL

   ,CONSTRAINT [RHIC4D2_PK] PRIMARY KEY CLUSTERED ([HIC4_SEQN])
)

CREATE NONCLUSTERED INDEX [RHIC4D2_NX1] ON [fdb_b].[RHIC4D2] ([HIC4])
CREATE NONCLUSTERED INDEX [RHIC4D2_NX2] ON [fdb_b].[RHIC4D2] ([HIC4_ROOT])

GO
