CREATE TABLE [fdb_a].[RMIRMRH1] (
   [MED_REPL_ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [MED_PREV_ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [MED_ROUTED_MED_ID_REPL_EFF_DT] [datetime] NOT NULL

   ,CONSTRAINT [RMIRMRH1_PK] PRIMARY KEY CLUSTERED ([MED_REPL_ROUTED_MED_ID], [MED_PREV_ROUTED_MED_ID])
)

CREATE NONCLUSTERED INDEX [RMIRMRH1_NX1] ON [fdb_a].[RMIRMRH1] ([MED_PREV_ROUTED_MED_ID])

GO
