CREATE TABLE [fdb_b].[RDAMGHC0] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [DAM_ALRGN_GRP] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RDAMGHC0_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN], [DAM_ALRGN_GRP])
)


GO
