CREATE TABLE [fdb_b].[RDDIMIN0] (
   [DDI_NDC] [varchar](11) NOT NULL,
   [DDI_CODEX] [numeric](5,0) NOT NULL,
   [DDI_NDC_HICSEQN] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RDDIMIN0_PK] PRIMARY KEY CLUSTERED ([DDI_NDC], [DDI_CODEX], [DDI_NDC_HICSEQN])
)


GO
