CREATE TABLE [fdb_a].[RDAMGX0] (
   [DAM_ALRGN_GRP] [numeric](6,0) NOT NULL,
   [DAM_ALRGN_XSENSE] [numeric](4,0) NOT NULL

   ,CONSTRAINT [RDAMGX0_PK] PRIMARY KEY CLUSTERED ([DAM_ALRGN_GRP], [DAM_ALRGN_XSENSE])
)


GO
