CREATE TABLE [fdb_b].[RMIGECD1] (
   [MED_REF_GEN_THERA_EQU_CD] [varchar](1) NOT NULL,
   [MED_REF_GEN_THERA_EQU_CD_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMIGECD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_GEN_THERA_EQU_CD])
)


GO
