CREATE TABLE [fdb_a].[RDAMXSD0] (
   [DAM_ALRGN_XSENSE_STATUS_CD] [numeric](1,0) NOT NULL,
   [DAM_ALRGN_XSENSE_STATUS_CD_DSC] [varchar](50) NULL

   ,CONSTRAINT [RDAMXSD0_PK] PRIMARY KEY CLUSTERED ([DAM_ALRGN_XSENSE_STATUS_CD])
)


GO
