CREATE TABLE [fdb_b].[RGCNSEQ4] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [HIC3] [varchar](3) NULL,
   [HICL_SEQNO] [numeric](6,0) NULL,
   [GCDF] [varchar](2) NULL,
   [GCRT] [varchar](1) NULL,
   [STR] [varchar](10) NULL,
   [GTC] [numeric](2,0) NULL,
   [TC] [numeric](2,0) NULL,
   [DCC] [varchar](1) NULL,
   [GCNSEQ_GI] [varchar](1) NULL,
   [GENDER] [varchar](1) NULL,
   [HIC3_SEQN] [numeric](6,0) NULL,
   [STR60] [varchar](60) NULL

   ,CONSTRAINT [RGCNSEQ4_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO])
)

CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX1] ON [fdb_b].[RGCNSEQ4] ([HIC3])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX2] ON [fdb_b].[RGCNSEQ4] ([HICL_SEQNO])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX3] ON [fdb_b].[RGCNSEQ4] ([GCDF])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX4] ON [fdb_b].[RGCNSEQ4] ([GCRT])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX5] ON [fdb_b].[RGCNSEQ4] ([STR60])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX6] ON [fdb_b].[RGCNSEQ4] ([GTC])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX7] ON [fdb_b].[RGCNSEQ4] ([TC])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX8] ON [fdb_b].[RGCNSEQ4] ([DCC])
CREATE NONCLUSTERED INDEX [RGCNSEQ4_NX9] ON [fdb_b].[RGCNSEQ4] ([HIC3_SEQN])

GO
