CREATE TABLE [fdb_b].[RAHFSGC1] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [AHFS8] [numeric](8,0) NOT NULL,
   [AHFS_REL] [numeric](2,0) NULL

   ,CONSTRAINT [RAHFSGC1_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [AHFS8])
)

CREATE NONCLUSTERED INDEX [RAHFSGC0_NX1] ON [fdb_b].[RAHFSGC1] ([AHFS8])

GO
