CREATE TABLE [fdb_a].[RDLIMRM0] (
   [ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [DLIM_DRUG_GRP_ID] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDLIMRM0_PK] PRIMARY KEY CLUSTERED ([ROUTED_MED_ID], [DLIM_DRUG_GRP_ID])
)


GO
