CREATE TABLE [fdb_a].[REVDVT0] (
   [EVD_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_VOCAB_TYPE_DESC] [varchar](50) NOT NULL,
   [EVD_SOURCE_ID] [numeric](4,0) NOT NULL

   ,CONSTRAINT [REVDVT0_PK] PRIMARY KEY CLUSTERED ([EVD_VOCAB_TYPE_ID])
)


GO
