CREATE TABLE [fdb_b].[RMTLSND0] (
   [MTL_LAB_ID_SYN_NMTYP_CODE] [varchar](2) NOT NULL,
   [MTL_LAB_ID_SYN_NMTYP_CODE_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLSND0_PK] PRIMARY KEY CLUSTERED ([MTL_LAB_ID_SYN_NMTYP_CODE])
)


GO
