CREATE TABLE [fdb_b].[RMTLSSD0] (
   [MTL_LAB_ID_SYN_STATUS] [char](1) NOT NULL,
   [MTL_LAB_ID_SYN_STATUS_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLSSD0_PK] PRIMARY KEY CLUSTERED ([MTL_LAB_ID_SYN_STATUS])
)


GO
