CREATE TABLE [fdb_a].[RMIRH1] (
   [MED_REPL_MEDID] [numeric](8,0) NOT NULL,
   [MED_PREV_MEDID] [numeric](8,0) NOT NULL,
   [MED_MEDID_REPL_EFF_DT] [datetime] NOT NULL

   ,CONSTRAINT [RMIRH1_PK] PRIMARY KEY CLUSTERED ([MED_REPL_MEDID], [MED_PREV_MEDID])
)

CREATE NONCLUSTERED INDEX [RMIRH1_NX1] ON [fdb_a].[RMIRH1] ([MED_PREV_MEDID])

GO
