CREATE TABLE [fdb_b].[RDLIMGC1] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [DLIM_DRUG_GRP_ID] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDLIMGC1_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [DLIM_DRUG_GRP_ID])
)


GO
