CREATE TABLE [fdb_b].[RLBLWGC0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [LBL_WARN] [varchar](4) NOT NULL,
   [LBL_PRTY] [numeric](2,0) NULL

   ,CONSTRAINT [RLBLWGC0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [LBL_WARN])
)

CREATE NONCLUSTERED INDEX [RLBLWGC0_NX1] ON [fdb_b].[RLBLWGC0] ([LBL_WARN])

GO
