CREATE TABLE [fdb_a].[RADIMMO5] (
   [DDI_MONOX] [numeric](5,0) NOT NULL,
   [ADI_MONOSN] [numeric](3,0) NOT NULL,
   [IAMIDENTN] [varchar](1) NULL,
   [IAMTEXTN] [varchar](76) NULL,
   [IAMREFCAT] [varchar](1) NULL

   ,CONSTRAINT [RADIMMO5_PK] PRIMARY KEY CLUSTERED ([DDI_MONOX], [ADI_MONOSN])
)

CREATE NONCLUSTERED INDEX [RADIMMO5_NX1] ON [fdb_a].[RADIMMO5] ([IAMREFCAT])

GO
