CREATE TABLE [fdb_b].[RMINMD1] (
   [MED_NAME_TYPE_CD] [varchar](1) NOT NULL,
   [MED_NAME_TYPE_CD_DESC] [varchar](30) NOT NULL

   ,CONSTRAINT [RMINMD1_PK] PRIMARY KEY CLUSTERED ([MED_NAME_TYPE_CD])
)


GO
