CREATE TABLE [fdb_b].[RPEMORG0] (
   [ROUTED_GEN_ID] [numeric](8,0) NOT NULL,
   [PEMONO] [numeric](4,0) NOT NULL

   ,CONSTRAINT [RPEMORG0_PK] PRIMARY KEY CLUSTERED ([ROUTED_GEN_ID], [PEMONO])
)


GO
