CREATE TABLE [fdb_a].[RMTLAID0] (
   [MTL_ANALYTE_ID] [numeric](8,0) NOT NULL,
   [MTL_ANALYTE_ID_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLAID0_PK] PRIMARY KEY CLUSTERED ([MTL_ANALYTE_ID])
)


GO
