CREATE TABLE [fdb_a].[RETCSCH0] (
   [ETC_SEARCH_ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_PRODUCT_RELATED_ETC_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RETCSCH0_PK] PRIMARY KEY CLUSTERED ([ETC_SEARCH_ETC_ID], [ETC_PRODUCT_RELATED_ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCSCH0_NX1] ON [fdb_a].[RETCSCH0] ([ETC_PRODUCT_RELATED_ETC_ID])

GO
