CREATE TABLE [fdb_b].[RDLIMDR0] (
   [DLIM_DRUG_ID_TYP_CODE] [varchar](2) NOT NULL,
   [DLIM_DRUG_ID_TYP_CODE_DESC] [varchar](100) NULL

   ,CONSTRAINT [RDLIMDR0_PK] PRIMARY KEY CLUSTERED ([DLIM_DRUG_ID_TYP_CODE])
)


GO
