CREATE TABLE [fdb_b].[RDLIMSD0] (
   [DLIM_STATUS_CODE] [varchar](2) NOT NULL,
   [DLIM_STATUS_CODE_DESC] [varchar](100) NULL

   ,CONSTRAINT [RDLIMSD0_PK] PRIMARY KEY CLUSTERED ([DLIM_STATUS_CODE])
)


GO
