CREATE TABLE [fdb_a].[RETCNDC0] (
   [NDC] [varchar](11) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_COMMON_USE_IND] [varchar](1) NULL,
   [ETC_DEFAULT_USE_IND] [varchar](1) NULL

   ,CONSTRAINT [RETCNDC0_PK] PRIMARY KEY CLUSTERED ([NDC], [ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCNDC0_NX1] ON [fdb_a].[RETCNDC0] ([ETC_ID])

GO
