CREATE TABLE [fdb_b].[RMTLLSD0] (
   [MTL_LAB_ID_STATUS] [char](1) NOT NULL,
   [MTL_LAB_ID_STATUS_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLLSD0_PK] PRIMARY KEY CLUSTERED ([MTL_LAB_ID_STATUS])
)


GO
