CREATE TABLE [fdb_b].[RETCMNM0] (
   [MED_NAME_ID] [numeric](8,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RETCMNM0_PK] PRIMARY KEY CLUSTERED ([MED_NAME_ID], [ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCMNM0_NX1] ON [fdb_b].[RETCMNM0] ([ETC_ID])

GO
