CREATE TABLE [fdb_b].[RMEDIS0] (
   [MEDID] [numeric](8,0) NOT NULL,
   [TOTAL_PRODUCTS_CNT] [numeric](6,0) NULL,
   [PRODUCTS_RESEARCHED_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RMEDIS0_PK] PRIMARY KEY CLUSTERED ([MEDID])
)


GO
