CREATE TABLE [fdb_a].[RETCXRF0] (
   [ETC_ID] [numeric](8,0) NOT NULL,
   [HIC3_SEQN] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RETCXRF0_PK] PRIMARY KEY CLUSTERED ([ETC_ID], [HIC3_SEQN])
)

CREATE NONCLUSTERED INDEX [RETCXRF0_NX1] ON [fdb_a].[RETCXRF0] ([HIC3_SEQN])

GO
