CREATE TABLE [fdb_a].[RETCNMH0] (
   [MED_NAME_ID] [numeric](8,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_REVISION_SEQNO] [numeric](5,0) NOT NULL,
   [ETC_CHANGE_TYPE_CODE] [varchar](1) NULL,
   [ETC_EFFECTIVE_DATE] [datetime] NULL

   ,CONSTRAINT [RETCNMH0_PK] PRIMARY KEY CLUSTERED ([MED_NAME_ID], [ETC_ID], [ETC_REVISION_SEQNO])
)

CREATE NONCLUSTERED INDEX [RETCNMH0_NX1] ON [fdb_a].[RETCNMH0] ([ETC_ID])

GO
