CREATE TABLE [fdb_b].[REVDLT0] (
   [EVD_LINK_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_SOURCE_ID] [numeric](4,0) NOT NULL,
   [EVD_LINK_TYPE_DESC] [varchar](50) NOT NULL

   ,CONSTRAINT [REVDLT0_PK] PRIMARY KEY CLUSTERED ([EVD_LINK_TYPE_ID])
)


GO
