CREATE TABLE [fdb_a].[RHICRH0] (
   [REPL_HIC_SEQN] [numeric](6,0) NOT NULL,
   [PREV_HIC_SEQN] [numeric](6,0) NOT NULL,
   [HIC_REPL_EFF_DT] [datetime] NULL

   ,CONSTRAINT [RHICRH0_PK] PRIMARY KEY CLUSTERED ([REPL_HIC_SEQN], [PREV_HIC_SEQN])
)


GO
