CREATE TABLE [fdb_b].[RMEDMHL0] (
   [MED_CONCEPT_ID] [numeric](8,0) NOT NULL,
   [MED_CONCEPT_ID_TYP] [numeric](1,0) NOT NULL,
   [HICL_SEQNO] [numeric](6,0) NOT NULL,
   [MED_CONCEPT_HICL_SRC_CD] [numeric](1,0) NOT NULL,
   [MED_CONCEPT_OBSDATEC] [datetime] NULL

   ,CONSTRAINT [RMEDMHL0_PK] PRIMARY KEY CLUSTERED ([MED_CONCEPT_ID], [MED_CONCEPT_ID_TYP], [HICL_SEQNO], [MED_CONCEPT_HICL_SRC_CD])
)


GO
