CREATE TABLE [fdb_a].[RDPTRTM0] (
   [ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [DPT_CLASS_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RDPTRTM0_PK] PRIMARY KEY CLUSTERED ([ROUTED_MED_ID], [DPT_CLASS_ID])
)

CREATE NONCLUSTERED INDEX [RDPTRTM0_NX1] ON [fdb_a].[RDPTRTM0] ([DPT_CLASS_ID])

GO
