CREATE TABLE [fdb_b].[RHIC1D2] (
   [HIC1_SEQN] [numeric](6,0) NOT NULL,
   [HIC1] [varchar](1) NOT NULL,
   [HIC1_DESC] [varchar](50) NULL

   ,CONSTRAINT [RHIC1D2_PK] PRIMARY KEY CLUSTERED ([HIC1_SEQN])
)

CREATE NONCLUSTERED INDEX [RHIC1D2_NX1] ON [fdb_b].[RHIC1D2] ([HIC1])

GO
