CREATE TABLE [fdb_a].[RDDIMRM0] (
   [ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [DDI_CODEX] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDDIMRM0_PK] PRIMARY KEY CLUSTERED ([ROUTED_MED_ID], [DDI_CODEX])
)

CREATE NONCLUSTERED INDEX [RDDIMRM0_NX1] ON [fdb_a].[RDDIMRM0] ([DDI_CODEX])

GO
