CREATE TABLE [fdb_b].[RDAMCSD1] (
   [DAM_ALRGN_XSENSE] [numeric](4,0) NOT NULL,
   [DAM_ALRGN_XSENSE_DESC] [varchar](50) NULL,
   [DAM_XSENSE_POTENTIAL_INCTV_IND] [numeric](1,0) NULL,
   [DAM_ALRGN_XSENSE_STATUS_CD] [numeric](1,0) NULL

   ,CONSTRAINT [RDAMCSD1_PK] PRIMARY KEY CLUSTERED ([DAM_ALRGN_XSENSE])
)


GO
