CREATE TABLE [fdb_a].[RDPTGC0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [DPT_CLASS_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RDPTGC0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [DPT_CLASS_ID])
)

CREATE NONCLUSTERED INDEX [RDPTGC0_NX1] ON [fdb_a].[RDPTGC0] ([DPT_CLASS_ID])

GO
