CREATE TABLE [fdb_a].[RMINAMD1] (
   [MED_NAME_SOURCE_CD] [varchar](1) NOT NULL,
   [MED_NAME_SOURCE_CD_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMINAMD1_PK] PRIMARY KEY CLUSTERED ([MED_NAME_SOURCE_CD])
)


GO
