CREATE TABLE [fdb_a].[RDLIMMI0] (
   [DLIM_MONOGRAPH_ID] [numeric](8,0) NOT NULL,
   [DLIM_MONOGRAPH_TITLE] [varchar](255) NULL

   ,CONSTRAINT [RDLIMMI0_PK] PRIMARY KEY CLUSTERED ([DLIM_MONOGRAPH_ID])
)


GO
