CREATE TABLE [fdb_a].[RNDCINH0] (
   [NDC] [varchar](11) NOT NULL,
   [HIC_SEQN] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RNDCINH0_PK] PRIMARY KEY CLUSTERED ([NDC], [HIC_SEQN])
)

CREATE NONCLUSTERED INDEX [RNDCINH0_NX1] ON [fdb_a].[RNDCINH0] ([HIC_SEQN])

GO
