CREATE TABLE [fdb_a].[RDLIMCR0] (
   [DLIM_DRUG_ID] [numeric](8,0) NOT NULL,
   [DLIM_DRUG_ID_TYP_CODE] [varchar](2) NOT NULL,
   [DLIM_STATUS_CODE] [varchar](2) NOT NULL

   ,CONSTRAINT [RDLIMCR0_PK] PRIMARY KEY CLUSTERED ([DLIM_DRUG_ID], [DLIM_DRUG_ID_TYP_CODE])
)


GO
