CREATE TABLE [fdb_b].[RLBLWV0] (
   [LBL_WARN] [varchar](4) NOT NULL,
   [LBLW_VTYPE] [numeric](3,0) NOT NULL,
   [LBLW_VCODE] [varchar](10) NULL

   ,CONSTRAINT [RLBLWV0_PK] PRIMARY KEY CLUSTERED ([LBL_WARN], [LBLW_VTYPE])
)

CREATE NONCLUSTERED INDEX [RLBLWV0_NX1] ON [fdb_b].[RLBLWV0] ([LBLW_VTYPE])

GO
