CREATE TABLE [fdb_a].[RDLIMTD0] (
   [DLIM_TXT_TYP_CODE] [varchar](2) NOT NULL,
   [DLIM_TXT_TYP_CODE_DESC] [varchar](50) NOT NULL

   ,CONSTRAINT [RDLIMTD0_PK] PRIMARY KEY CLUSTERED ([DLIM_TXT_TYP_CODE])
)


GO
