CREATE TABLE [fdb_a].[RDDIMRG0] (
   [ROUTED_GEN_ID] [numeric](8,0) NOT NULL,
   [DDI_CODEX] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDDIMRG0_PK] PRIMARY KEY CLUSTERED ([ROUTED_GEN_ID], [DDI_CODEX])
)


GO
