CREATE TABLE [fdb_a].[RETCHIC0] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RETCHIC0_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN], [ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCHIC0_NX1] ON [fdb_a].[RETCHIC0] ([ETC_ID])

GO
