CREATE TABLE [fdb_b].[RDAMXHC0] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [DAM_ALRGN_XSENSE] [numeric](4,0) NOT NULL

   ,CONSTRAINT [RDAMXHC0_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN], [DAM_ALRGN_XSENSE])
)


GO
