CREATE TABLE [fdb_a].[RRTGNSD0] (
   [ROUTED_GEN_STATUS_CD] [varchar](1) NOT NULL,
   [ROUTED_GEN_STATUS_CD_DESC] [varchar](30) NOT NULL

   ,CONSTRAINT [RRTGNSD0_PK] PRIMARY KEY CLUSTERED ([ROUTED_GEN_STATUS_CD])
)


GO
