CREATE TABLE [fdb_b].[RMILGND1] (
   [MED_REF_FED_LEGEND_IND] [varchar](1) NOT NULL,
   [MED_REF_FED_LEGEND_IND_DESC] [varchar](60) NOT NULL

   ,CONSTRAINT [RMILGND1_PK] PRIMARY KEY CLUSTERED ([MED_REF_FED_LEGEND_IND])
)


GO
