CREATE TABLE [fdb_b].[RMTLVTD0] (
   [MTL_EXTRN_VOCAB_TYP_CODE] [varchar](2) NOT NULL,
   [MTL_EXTRN_VOCAB_TYP_CODE_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLVTD0_PK] PRIMARY KEY CLUSTERED ([MTL_EXTRN_VOCAB_TYP_CODE])
)


GO
