CREATE TABLE [fdb_a].[REVDEL0] (
   [EVD_FDB_VOCAB_ID] [varchar](20) NOT NULL,
   [EVD_FDB_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_EXT_VOCAB_ID] [varchar](50) NOT NULL,
   [EVD_EXT_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_LINK_TYPE_ID] [numeric](4,0) NOT NULL

   ,CONSTRAINT [REVDEL0_PK] PRIMARY KEY CLUSTERED ([EVD_FDB_VOCAB_ID], [EVD_FDB_VOCAB_TYPE_ID], [EVD_EXT_VOCAB_ID], [EVD_EXT_VOCAB_TYPE_ID])
)

CREATE NONCLUSTERED INDEX [_dta_index_REVDEL0_10_1323151759__K2_K4_K1] ON [fdb_a].[REVDEL0] ([EVD_FDB_VOCAB_TYPE_ID], [EVD_EXT_VOCAB_TYPE_ID], [EVD_FDB_VOCAB_ID])

GO
