CREATE TABLE [fdb_a].[RHIC3L2] (
   [HICL_SEQNO] [numeric](6,0) NOT NULL,
   [HIC3_SEQN] [numeric](6,0) NOT NULL,
   [HIC3] [varchar](3) NULL,
   [HIC3_RELNO] [numeric](1,0) NULL

   ,CONSTRAINT [RHIC3L2_PK] PRIMARY KEY CLUSTERED ([HICL_SEQNO], [HIC3_SEQN])
)

CREATE NONCLUSTERED INDEX [RHIC3L2_NX1] ON [fdb_a].[RHIC3L2] ([HIC3_SEQN])
CREATE NONCLUSTERED INDEX [RHIC3L2_NX2] ON [fdb_a].[RHIC3L2] ([HIC3])

GO
