CREATE TABLE [fdb_a].[RMIDESD1] (
   [MED_REF_DESI_IND] [varchar](1) NOT NULL,
   [MED_REF_DESI_IND_DESC] [varchar](60) NOT NULL

   ,CONSTRAINT [RMIDESD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_DESI_IND])
)


GO
