CREATE TABLE [fdb_b].[RMIGC1] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [MEDID] [numeric](8,0) NOT NULL

   ,CONSTRAINT [RMIGC1_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO])
)

CREATE NONCLUSTERED INDEX [RMIGC1_NX] ON [fdb_b].[RMIGC1] ([MEDID])

GO
