CREATE TABLE [fdb_a].[RMIGPCD1] (
   [MED_REF_GEN_COMP_PRICE_CD] [varchar](1) NOT NULL,
   [MED_REF_GEN_COMP_PRICE_CD_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMIGPCD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_GEN_COMP_PRICE_CD])
)


GO
