CREATE TABLE [fdb_a].[RHICL1] (
   [HICL_SEQNO] [numeric](6,0) NOT NULL,
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [HIC_REL_NO] [numeric](1,0) NULL,
   [HIC] [varchar](6) NULL

   ,CONSTRAINT [RHICL1_PK] PRIMARY KEY CLUSTERED ([HICL_SEQNO], [HIC_SEQN])
)

CREATE NONCLUSTERED INDEX [RHICL1_NX1] ON [fdb_a].[RHICL1] ([HIC_SEQN])
CREATE NONCLUSTERED INDEX [RHICL1_NX2] ON [fdb_a].[RHICL1] ([HIC])

GO
