CREATE TABLE [fdb_a].[RGCNINS0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [TOTAL_PRODUCTS_CNT] [numeric](6,0) NULL,
   [PRODUCTS_RESEARCHED_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RGCNINS0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO])
)


GO
