CREATE TABLE [fdb_b].[RETCGC0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_COMMON_USE_IND] [varchar](1) NULL,
   [ETC_DEFAULT_USE_IND] [varchar](1) NULL

   ,CONSTRAINT [RETCGC0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCGC0_NX1] ON [fdb_b].[RETCGC0] ([ETC_ID])

GO
