CREATE TABLE [fdb_a].[RHICCAS1] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [CAS9_TBL] [numeric](9,0) NULL,
   [HIC] [varchar](6) NULL

   ,CONSTRAINT [RHICCAS1_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN])
)


GO
