CREATE TABLE [fdb_b].[RHICHCR0] (
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [RELATED_HIC_SEQN] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RHICHCR0_PK] PRIMARY KEY CLUSTERED ([HIC_SEQN], [RELATED_HIC_SEQN])
)


GO
