CREATE TABLE [fdb_b].[RMIGSCD1] (
   [MED_REF_GEN_SPREAD_CD] [varchar](1) NOT NULL,
   [MED_REF_GEN_SPREAD_CD_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMIGSCD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_GEN_SPREAD_CD])
)


GO
