CREATE TABLE [fdb_a].[RMIDFRH1] (
   [MED_REPL_ROUTED_DF_MED_ID] [numeric](8,0) NOT NULL,
   [MED_PREV_ROUTED_DF_MED_ID] [numeric](8,0) NOT NULL,
   [MED_ROUTED_DF_MED_ID_REP_EF_DT] [datetime] NULL

   ,CONSTRAINT [RMIDFRH1_PK] PRIMARY KEY CLUSTERED ([MED_REPL_ROUTED_DF_MED_ID], [MED_PREV_ROUTED_DF_MED_ID])
)

CREATE NONCLUSTERED INDEX [RMIDFRH1_NX1] ON [fdb_a].[RMIDFRH1] ([MED_PREV_ROUTED_DF_MED_ID])

GO
