CREATE TABLE [fdb_b].[RMIINND1] (
   [MED_REF_INNOV_IND] [varchar](1) NOT NULL,
   [MED_REF_INNOV_IND_DESC] [varchar](90) NOT NULL

   ,CONSTRAINT [RMIINND1_PK] PRIMARY KEY CLUSTERED ([MED_REF_INNOV_IND])
)


GO
