CREATE TABLE [fdb_b].[RSTRSCD0] (
   [STRENGTH_STATUS_CODE] [numeric](1,0) NOT NULL,
   [STRENGTH_STATUS_DESC] [varchar](100) NULL

   ,CONSTRAINT [RSTRSCD0_PK] PRIMARY KEY CLUSTERED ([STRENGTH_STATUS_CODE])
)


GO
