CREATE TABLE [fdb_b].[RGCNINH0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [INACTV_NOT_PRES_CNT] [numeric](6,0) NULL,
   [INACTV_PRES_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RGCNINH0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [HIC_SEQN])
)

CREATE NONCLUSTERED INDEX [RGCNINH0_NX1] ON [fdb_b].[RGCNINH0] ([HIC_SEQN])

GO
