CREATE TABLE [fdb_b].[RMIRTD1] (
   [MED_ROUTE_ID] [numeric](5,0) NOT NULL,
   [MED_ROUTE_ABBR] [varchar](4) NOT NULL,
   [MED_ROUTE_DESC] [varchar](30) NOT NULL

   ,CONSTRAINT [RMIRTD1_PK] PRIMARY KEY CLUSTERED ([MED_ROUTE_ID])
)

CREATE NONCLUSTERED INDEX [RMIRTD1_NX1] ON [fdb_b].[RMIRTD1] ([MED_ROUTE_ABBR])

GO
