CREATE TABLE [fdb_a].[RDFIMRM0] (
   [ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [FDCDE] [numeric](3,0) NOT NULL

   ,CONSTRAINT [RDFIMRM0_PK] PRIMARY KEY CLUSTERED ([ROUTED_MED_ID], [FDCDE])
)

CREATE NONCLUSTERED INDEX [RDFIMRM0_NX1] ON [fdb_a].[RDFIMRM0] ([FDCDE])

GO
