CREATE TABLE [fdb_a].[RMEDNIS0] (
   [MED_NAME_ID] [numeric](8,0) NOT NULL,
   [TOTAL_PRODUCTS_CNT] [numeric](6,0) NULL,
   [PRODUCTS_RESEARCHED_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RMEDNIS0_PK] PRIMARY KEY CLUSTERED ([MED_NAME_ID])
)


GO
