CREATE TABLE [fdb_b].[RXRFAHX0] (
   [DAM_AGCSP] [numeric](6,0) NOT NULL,
   [HIC_SEQN] [numeric](6,0) NOT NULL,
   [HIC] [varchar](6) NOT NULL

   ,CONSTRAINT [RXRFAHX0_PK] PRIMARY KEY CLUSTERED ([DAM_AGCSP], [HIC_SEQN])
)

CREATE NONCLUSTERED INDEX [RXRFAHX0_NX1] ON [fdb_b].[RXRFAHX0] ([HIC_SEQN])
CREATE NONCLUSTERED INDEX [RXRFAHX0_NX2] ON [fdb_b].[RXRFAHX0] ([HIC])

GO
