CREATE TABLE [fdb_b].[RDAMGSD0] (
   [DAM_ALRGN_GRP_STATUS_CD] [numeric](1,0) NOT NULL,
   [DAM_ALRGN_GRP_STATUS_CD_DESC] [varchar](50) NULL

   ,CONSTRAINT [RDAMGSD0_PK] PRIMARY KEY CLUSTERED ([DAM_ALRGN_GRP_STATUS_CD])
)


GO
