CREATE TABLE [fdb_a].[RETCGCH0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_REVISION_SEQNO] [numeric](5,0) NOT NULL,
   [ETC_COMMON_USE_IND] [varchar](1) NULL,
   [ETC_DEFAULT_USE_IND] [varchar](1) NULL,
   [ETC_CHANGE_TYPE_CODE] [varchar](1) NULL,
   [ETC_EFFECTIVE_DATE] [datetime] NULL

   ,CONSTRAINT [RETCGCH0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [ETC_ID], [ETC_REVISION_SEQNO])
)

CREATE NONCLUSTERED INDEX [RETCGCH0_NX1] ON [fdb_a].[RETCGCH0] ([ETC_ID])

GO
