CREATE TABLE [fdb_b].[RMIDEAD1] (
   [MED_REF_DEA_CD] [varchar](1) NOT NULL,
   [MED_REF_DEA_CD_DESC] [varchar](60) NOT NULL

   ,CONSTRAINT [RMIDEAD1_PK] PRIMARY KEY CLUSTERED ([MED_REF_DEA_CD])
)


GO
