CREATE TABLE [fdb_a].[RMTLSID0] (
   [MTL_SPECIMEN_ID] [numeric](5,0) NOT NULL,
   [MTL_SPECIMEN_ID_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLSID0_PK] PRIMARY KEY CLUSTERED ([MTL_SPECIMEN_ID])
)


GO
