CREATE TABLE [fdb_a].[RETCMED0] (
   [MEDID] [numeric](8,0) NOT NULL,
   [ETC_ID] [numeric](8,0) NOT NULL,
   [ETC_COMMON_USE_IND] [varchar](1) NULL,
   [ETC_DEFAULT_USE_IND] [varchar](1) NULL

   ,CONSTRAINT [RETCMED0_PK] PRIMARY KEY CLUSTERED ([MEDID], [ETC_ID])
)

CREATE NONCLUSTERED INDEX [RETCMED0_NX1] ON [fdb_a].[RETCMED0] ([ETC_ID])

GO
