CREATE TABLE [fdb_b].[RMTLPSD0] (
   [MTL_PANEL_ID_STATUS] [char](1) NOT NULL,
   [MTL_PANEL_ID_STATUS_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLPSD0_PK] PRIMARY KEY CLUSTERED ([MTL_PANEL_ID_STATUS])
)


GO
