CREATE TABLE [fdb_a].[RMIGCND1] (
   [MED_GCNSEQNO_ASSIGN_CD] [varchar](1) NOT NULL,
   [MED_GCNSEQNO_ASSIGN_CD_DESC] [varchar](60) NOT NULL

   ,CONSTRAINT [RMIGCND1_PK] PRIMARY KEY CLUSTERED ([MED_GCNSEQNO_ASSIGN_CD])
)


GO
