CREATE TABLE [fdb_a].[RDAMCD0] (
   [DAM_CONCEPT_ID_TYP] [numeric](3,0) NOT NULL,
   [DAM_CONCEPT_ID_TYP_DESC] [varchar](50) NULL

   ,CONSTRAINT [RDAMCD0_PK] PRIMARY KEY CLUSTERED ([DAM_CONCEPT_ID_TYP])
)


GO
