CREATE TABLE [fdb_b].[RMTLITD0] (
   [MTL_FDB_ID_TYP_CODE] [varchar](2) NOT NULL,
   [MTL_FDB_ID_TYP_CODE_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMTLITD0_PK] PRIMARY KEY CLUSTERED ([MTL_FDB_ID_TYP_CODE])
)


GO
