CREATE TABLE [fdb_a].[RMEDRIS0] (
   [ROUTED_MED_ID] [numeric](8,0) NOT NULL,
   [TOTAL_PRODUCTS_CNT] [numeric](6,0) NULL,
   [PRODUCTS_RESEARCHED_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RMEDRIS0_PK] PRIMARY KEY CLUSTERED ([ROUTED_MED_ID])
)


GO
