CREATE TABLE [fdb_b].[REVDEV0] (
   [EVD_EXT_VOCAB_ID] [varchar](50) NOT NULL,
   [EVD_EXT_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_SEQ_SN] [numeric](4,0) NOT NULL,
   [EVD_EXT_VOCAB_DESC] [varchar](255) NOT NULL

   ,CONSTRAINT [REVDEV0_PK] PRIMARY KEY CLUSTERED ([EVD_EXT_VOCAB_ID], [EVD_EXT_VOCAB_TYPE_ID], [EVD_SEQ_SN])
)


GO
