CREATE TABLE [fdb_b].[RDLIMDI0] (
   [DLIM_DRUG_GRP_ID] [numeric](5,0) NOT NULL,
   [DLIM_DRUG_GRP_ID_DESC] [varchar](100) NULL

   ,CONSTRAINT [RDLIMDI0_PK] PRIMARY KEY CLUSTERED ([DLIM_DRUG_GRP_ID])
)


GO
