CREATE TABLE [fdb_b].[RDLIMDD0] (
   [DLIM_DOC_LEVEL_CODE] [varchar](2) NOT NULL,
   [DLIM_DOC_LEVEL_CODE_DESC] [varchar](50) NULL

   ,CONSTRAINT [RDLIMDD0_PK] PRIMARY KEY CLUSTERED ([DLIM_DOC_LEVEL_CODE])
)


GO
