CREATE TABLE [fdb_a].[RMEDDIS0] (
   [ROUTED_DOSAGE_FORM_MED_ID] [numeric](8,0) NOT NULL,
   [TOTAL_PRODUCTS_CNT] [numeric](6,0) NULL,
   [PRODUCTS_RESEARCHED_CNT] [numeric](6,0) NULL

   ,CONSTRAINT [RMEDDIS0_PK] PRIMARY KEY CLUSTERED ([ROUTED_DOSAGE_FORM_MED_ID])
)


GO
