CREATE TABLE [fdb_a].[RDLIMRG0] (
   [ROUTED_GEN_ID] [numeric](8,0) NOT NULL,
   [DLIM_DRUG_GRP_ID] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDLIMRG0_PK] PRIMARY KEY CLUSTERED ([ROUTED_GEN_ID], [DLIM_DRUG_GRP_ID])
)


GO
