CREATE TABLE [fdb_b].[RMEDMGL0] (
   [MED_CONCEPT_ID] [numeric](8,0) NOT NULL,
   [MED_CONCEPT_ID_TYP] [numeric](1,0) NOT NULL,
   [GENERIC_MED_CONCEPT_ID] [numeric](8,0) NOT NULL,
   [MED_CONCEPT_OBSDATEC] [datetime] NULL

   ,CONSTRAINT [RMEDMGL0_PK] PRIMARY KEY CLUSTERED ([MED_CONCEPT_ID], [MED_CONCEPT_ID_TYP], [GENERIC_MED_CONCEPT_ID])
)


GO
