CREATE TABLE [fdb_a].[RMEDCD0] (
   [MED_CONCEPT_ID_TYP] [numeric](1,0) NOT NULL,
   [MED_CONCEPT_ID_TYP_DESC] [varchar](50) NULL

   ,CONSTRAINT [RMEDCD0_PK] PRIMARY KEY CLUSTERED ([MED_CONCEPT_ID_TYP])
)


GO
