CREATE TABLE [fdb_b].[RMTLPID0] (
   [MTL_PANEL_ID] [numeric](5,0) NOT NULL,
   [MTL_PANEL_ID_DESC] [varchar](50) NULL,
   [MTL_PANEL_ID_STATUS] [varchar](1) NULL

   ,CONSTRAINT [RMTLPID0_PK] PRIMARY KEY CLUSTERED ([MTL_PANEL_ID])
)


GO
