CREATE TABLE [fdb_b].[RPEMGC0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [PEC] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RPEMGC0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [PEC])
)

CREATE NONCLUSTERED INDEX [RPEMGC0_NX1] ON [fdb_b].[RPEMGC0] ([PEC])

GO
