CREATE TABLE [dbo].[RDDCMGC0] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [DDXCN] [numeric](5,0) NOT NULL

   ,CONSTRAINT [RDDCMGC0_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [DDXCN])
)

CREATE NONCLUSTERED INDEX [RDDCMGC0_NX1] ON [dbo].[RDDCMGC0] ([DDXCN])

GO
