CREATE TABLE [dbo].[RDDCMMA1] (
   [DDXCN] [numeric](5,0) NOT NULL,
   [DDXCN_SN] [numeric](2,0) NOT NULL,
   [FDBDX] [varchar](9) NULL,
   [DDXCN_SL] [varchar](1) NULL,
   [DDXCN_REF] [varchar](26) NULL,
   [DXID] [numeric](8,0) NULL

   ,CONSTRAINT [RDDCMMA1_PK] PRIMARY KEY CLUSTERED ([DDXCN], [DDXCN_SN])
)

CREATE NONCLUSTERED INDEX [_dta_index_RDDCMMA1_12_1806629479__K1_K6_K4] ON [dbo].[RDDCMMA1] ([DDXCN], [DXID], [DDXCN_SL])
CREATE NONCLUSTERED INDEX [RDDCMMA1_NX1] ON [dbo].[RDDCMMA1] ([FDBDX])
CREATE NONCLUSTERED INDEX [RDDCMMA1_NX2] ON [dbo].[RDDCMMA1] ([DXID])

GO
