CREATE TABLE [dbo].[REVDCVX0_EXT_VOCAB_CVX_DESC] (
   [EVD_CVX_CD] [varchar](10) NOT NULL,
   [EVD_CVX_CD_DESC_SHORT] [varchar](100) NOT NULL,
   [EVD_CVX_CD_DESC_LONG] [varchar](255) NOT NULL,
   [EVD_CVX_CD_USAGE] [numeric](2,0) NOT NULL,
   [EVD_CVX_CD_STATUS] [varchar](30) NOT NULL,
   [EVD_CVX_CD_NONVACCINE] [varchar](30) NULL,
   [EVD_CVX_CD_ADD_DT] [datetime] NOT NULL,
   [EVD_CVX_CD_OBS_DT] [datetime] NULL,
   [EVD_CVX_LAST_UPDATE_DT] [datetime] NOT NULL

   ,CONSTRAINT [REVDCVX0_PK] PRIMARY KEY CLUSTERED ([EVD_CVX_CD])
)


GO
