CREATE TABLE [dbo].[REVDEVN0_EXT_VOCAB_NOTE] (
   [EVD_EXT_VOCAB_ID] [varchar](50) NOT NULL,
   [EVD_EXT_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_SEQ_SN] [numeric](4,0) NOT NULL,
   [EVD_EXT_VOCAB_NOTE] [varchar](255) NOT NULL

   ,CONSTRAINT [REVDEVN0_PK] PRIMARY KEY CLUSTERED ([EVD_EXT_VOCAB_ID], [EVD_EXT_VOCAB_TYPE_ID], [EVD_SEQ_SN])
)


GO
