CREATE TABLE [dbo].[REVDEV0_EXT_VOCAB_DESC] (
   [EVD_EXT_VOCAB_ID] [varchar](50) NOT NULL,
   [EVD_EXT_VOCAB_TYPE_ID] [numeric](4,0) NOT NULL,
   [EVD_SEQ_SN] [numeric](4,0) NOT NULL,
   [EVD_EXT_VOCAB_DESC] [varchar](255) NOT NULL
)


GO
