CREATE TABLE [dbo].[REVDUSE0_EXT_VOCAB_CVX_USAGE] (
   [EVD_CVX_CD_USAGE] [numeric](2,0) NOT NULL,
   [EVD_CVX_CD_USAGE_DESC_SHORT] [varchar](100) NOT NULL,
   [EVD_CVX_CD_USAGE_DESC_LONG] [varchar](255) NOT NULL

   ,CONSTRAINT [REVDUSE0_PK] PRIMARY KEY CLUSTERED ([EVD_CVX_CD_USAGE])
)


GO
