CREATE TABLE [dbo].[REVDVD0_VOCAB_DATA_VERSION] (
   [EVD_DATA_ID] [numeric](4,0) NOT NULL,
   [EVD_DATA_DESC] [varchar](50) NOT NULL,
   [EVD_SOURCE_ID] [numeric](4,0) NOT NULL,
   [EVD_SOURCE_DESC] [varchar](50) NOT NULL,
   [EVD_DATA_VERSION_DT] [datetime] NOT NULL

   ,CONSTRAINT [REVDVD0_PK] PRIMARY KEY CLUSTERED ([EVD_DATA_ID])
)


GO
