CREATE TABLE [dbo].[REVDCM0_CVX_MVX_LINK] (
   [EVD_CVX_CD] [varchar](10) NOT NULL,
   [EVD_MVX_CD] [varchar](10) NOT NULL,
   [EVD_CVX_CD_DESC_SHORT] [varchar](100) NOT NULL,
   [EVD_CVX_CD_DESC_LONG] [varchar](255) NOT NULL,
   [EVD_CVX_CD_USAGE] [numeric](2,0) NOT NULL,
   [EVD_CVX_CD_USAGE_DESC_SHORT] [varchar](100) NOT NULL,
   [EVD_CVX_CD_STATUS] [varchar](30) NULL,
   [EVD_MVX_CD_DESC] [varchar](100) NOT NULL,
   [EVD_MVX_CD_STATUS] [varchar](30) NULL

   ,CONSTRAINT [REVDCM0_PK] PRIMARY KEY CLUSTERED ([EVD_CVX_CD], [EVD_MVX_CD])
)


GO
