CREATE TABLE [dbo].[REVDUR0_RXCUI_ULT_REPL] (
   [EVD_EXT_VOCAB_ID] [varchar](50) NOT NULL,
   [EVD_EXT_ULT_REP_VOCAB_ID] [varchar](50) NOT NULL

   ,CONSTRAINT [REVDURO_PK] PRIMARY KEY CLUSTERED ([EVD_EXT_VOCAB_ID], [EVD_EXT_ULT_REP_VOCAB_ID])
)


GO
