CREATE TABLE [dbo].[RFMLISR0] (
   [SEARCH_ICD9CM] [varchar](10) NOT NULL,
   [RELATED_DXID] [numeric](8,0) NOT NULL,
   [FML_CLIN_CODE] [varchar](2) NOT NULL,
   [FML_NAV_CODE] [varchar](2) NOT NULL

   ,CONSTRAINT [RFMLISR0_PK] PRIMARY KEY CLUSTERED ([SEARCH_ICD9CM], [RELATED_DXID], [FML_CLIN_CODE])
)

CREATE NONCLUSTERED INDEX [_dta_index_RFMLISR0_12_1854629650__K3_K1_K2_K4] ON [dbo].[RFMLISR0] ([FML_CLIN_CODE], [SEARCH_ICD9CM], [RELATED_DXID], [FML_NAV_CODE])
CREATE NONCLUSTERED INDEX [RFMLISR0_NX1] ON [dbo].[RFMLISR0] ([FML_CLIN_CODE])
CREATE NONCLUSTERED INDEX [RFMLISR0_NX2] ON [dbo].[RFMLISR0] ([FML_NAV_CODE])
CREATE NONCLUSTERED INDEX [RFMLISR0_NX3] ON [dbo].[RFMLISR0] ([RELATED_DXID])

GO
