CREATE TABLE [dbo].[RMDCOV0] (
   [MDT_ID] [varchar](2) NOT NULL,
   [MDT_COV] [varchar](1) NOT NULL,
   [MDT_COVD] [varchar](50) NULL

   ,CONSTRAINT [RMDCOV0_PK] PRIMARY KEY CLUSTERED ([MDT_ID], [MDT_COV])
)


GO
