CREATE TABLE [dbo].[RMDCOPD0] (
   [MDT_ID] [varchar](2) NOT NULL,
   [MDT_COP] [varchar](1) NOT NULL,
   [MDT_COPD] [varchar](50) NULL

   ,CONSTRAINT [RMDCOPD0_PK] PRIMARY KEY CLUSTERED ([MDT_ID], [MDT_COP])
)


GO
