CREATE TABLE [dbo].[RPOEOSX1] (
   [POEOSTRID] [numeric](10,0) NOT NULL,
   [POETEXTTYP] [numeric](2,0) NOT NULL,
   [POETXTSTRL] [numeric](1,0) NOT NULL,
   [POETEXTCDE] [numeric](10,0) NOT NULL

   ,CONSTRAINT [RPOEOSX1_PK] PRIMARY KEY CLUSTERED ([POEOSTRID], [POETEXTTYP], [POETXTSTRL])
)

CREATE NONCLUSTERED INDEX [RPOEOSX1_NX2] ON [dbo].[RPOEOSX1] ([POETEXTTYP])
CREATE NONCLUSTERED INDEX [RPOEOSX1_NX3] ON [dbo].[RPOEOSX1] ([POETXTSTRL])
CREATE NONCLUSTERED INDEX [RPOEOSX1_NX4] ON [dbo].[RPOEOSX1] ([POETEXTCDE])

GO
