CREATE TABLE [dbo].[RPOETXT1] (
   [POETEXTCDE] [numeric](10,0) NOT NULL,
   [POELANGCDE] [numeric](2,0) NOT NULL,
   [POECOCDE] [numeric](2,0) NOT NULL,
   [POETXTNUM] [numeric](3,0) NOT NULL,
   [POETXLINE] [varchar](70) NULL

   ,CONSTRAINT [RPOETXT1_PK] PRIMARY KEY CLUSTERED ([POETEXTCDE], [POELANGCDE], [POECOCDE], [POETXTNUM])
)

CREATE NONCLUSTERED INDEX [RPOETXT1_NX1] ON [dbo].[RPOETXT1] ([POELANGCDE])
CREATE NONCLUSTERED INDEX [RPOETXT1_NX2] ON [dbo].[RPOETXT1] ([POECOCDE])

GO
