CREATE TABLE [dbo].[RPOEGCS1] (
   [GCN_SEQNO] [numeric](6,0) NOT NULL,
   [POECLINID] [numeric](6,0) NOT NULL,
   [POEOSETID] [numeric](6,0) NOT NULL

   ,CONSTRAINT [RPOEGCS1_PK] PRIMARY KEY CLUSTERED ([GCN_SEQNO], [POECLINID], [POEOSETID])
)

CREATE NONCLUSTERED INDEX [RPOEGCS1_NX1] ON [dbo].[RPOEGCS1] ([POEOSETID])
CREATE NONCLUSTERED INDEX [RPOEGCS1_NX2] ON [dbo].[RPOEGCS1] ([POECLINID])

GO
