CREATE TABLE [dbo].[RPOEOS1] (
   [POEOSETID] [numeric](6,0) NOT NULL,
   [POEOSTRSEQ] [numeric](2,0) NOT NULL,
   [POEOSTRID] [numeric](10,0) NOT NULL,
   [POEDOSETYP] [varchar](2) NOT NULL,
   [POECALCREQ] [varchar](1) NULL

   ,CONSTRAINT [RPOEOS1_PK] PRIMARY KEY CLUSTERED ([POEOSETID], [POEOSTRSEQ], [POEOSTRID])
)

CREATE NONCLUSTERED INDEX [RPOEOS1_NX1] ON [dbo].[RPOEOS1] ([POEOSTRID])
CREATE NONCLUSTERED INDEX [RPOEOS1_NX2] ON [dbo].[RPOEOS1] ([POEDOSETYP])

GO
