CREATE TABLE [dbo].[RXRFPCX0] (
   [PIF_ALG] [numeric](5,0) NOT NULL,
   [PIF_ALGSUB] [varchar](2) NOT NULL,
   [CHEMNO] [varchar](4) NOT NULL,
   [CHEMSE] [varchar](2) NOT NULL

   ,CONSTRAINT [RXRFPCX0_PK] PRIMARY KEY CLUSTERED ([PIF_ALG], [PIF_ALGSUB], [CHEMNO], [CHEMSE])
)

CREATE NONCLUSTERED INDEX [RXRFPCX0_NX1] ON [dbo].[RXRFPCX0] ([PIF_ALGSUB])
CREATE NONCLUSTERED INDEX [RXRFPCX0_NX2] ON [dbo].[RXRFPCX0] ([CHEMNO])
CREATE NONCLUSTERED INDEX [RXRFPCX0_NX3] ON [dbo].[RXRFPCX0] ([CHEMSE])

GO
