CREATE TABLE [dbo].[RXRFHCX0] (
   [HIC_SEQN] [numeric](6,0) NULL,
   [CHEMNO] [varchar](4) NULL,
   [CHEMSE] [varchar](2) NULL,
   [HIC] [varchar](6) NULL,
   [XRF_STATUS] [varchar](1) NOT NULL

   ,CONSTRAINT [RXRFHCX0_UK1] UNIQUE NONCLUSTERED ([HIC_SEQN], [CHEMNO], [CHEMSE])
)

CREATE NONCLUSTERED INDEX [RXRFHCX0_NX1] ON [dbo].[RXRFHCX0] ([CHEMNO], [CHEMSE])
CREATE NONCLUSTERED INDEX [RXRFHCX0_NX2] ON [dbo].[RXRFHCX0] ([XRF_STATUS])
CREATE NONCLUSTERED INDEX [RXRFHCX0_NX3] ON [dbo].[RXRFHCX0] ([HIC])

GO
