SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [adm].[UserPaymentLocksReport]
  @days INT=1
AS 
BEGIN 
  
	SELECT DR.DR_ID,DR_LAST_NAME,DR_FIRST_NAME,DR_MIDDLE_INITIAL,DR_ADDRESS1,DR_CITY,DR_STATE,DR_ZIP,DR_PHONE,DG_NAME,DR_EMAIL,CASE WHEN AC.ADMIN_COMPANY_NAME is NULL then 'RxNT' ELSE AC.ADMIN_COMPANY_NAME END ADMIN_COMPANY_NAME , 
	(Case WHEN DR.SALES_PERSON_ID IS NULL THEN 0 ELSE DR.SALES_PERSON_ID END) SALEPERSON,SALE_PERSON_FNAME,SALE_PERSON_LNAME,SALE.EMAIL, 
	(CASE WHEN blowusageemail IS NULL THEN 0 ELSE blowusageemail END) EMAILSENT 
	FROM DOCTORS DR							WITH(NOLOCK)
	INNER JOIN DOC_GROUPS DG				WITH(NOLOCK) ON DR.DG_ID = DG.DG_ID 
	INNER JOIN DOC_COMPANIES DC				WITH(NOLOCK) ON DG.DC_ID = DC.DC_ID 
	LEFT OUTER JOIN ADMIN_COMPANIES AC			WITH(NOLOCK) ON DC.ADMIN_COMPANY_ID = AC.ADMIN_COMPANY_ID 
	LEFT OUTER JOIN SALES_PERSON_INFO SALE	WITH(NOLOCK) ON DR.SALES_PERSON_ID = SALE.SALE_PERSON_ID 
	LEFT OUTER JOIN DOCTOR_INFO DI on DR.DR_ID = DI.DR_ID 
	WHERE 
	1 = 1
	--DR_ENABLED = 1 
        AND PRESCRIBING_AUTHORITY > 2  
        --AND lowusage_lock = 0
        AND ISNULL(DR.billing_enabled,0) = 1
		AND DATEADD(D, 0, DATEDIFF(D, 0, DR.billingDate)) < DATEADD(D, 0, DATEDIFF(D, 0,GETDATE()))
		AND DATEADD(D, 0, DATEDIFF(D, 0, DR.billingDate)) >= DATEADD(D, 0, DATEDIFF(D, 0,GETDATE()-@days)) 
        ORDER BY DC.ADMIN_COMPANY_ID ASC 
                    
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
