SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [adm].[usp_GetPrescribingDoctorsInGroup]
	@DoctorGroupId	BIGINT	= NULL
AS

BEGIN
	SET NOCOUNT ON;

	SELECT D.DR_ID,D.DG_ID,DG.DC_ID,D.DR_FIRST_NAME,D.DR_LAST_NAME,D.DR_MIDDLE_INITIAL FROM DOCTORS D WITH(NOLOCK)
	INNER JOIN DOC_GROUPS DG WITH(NOLOCK) ON D.DG_ID = DG.DG_ID 
	LEFT OUTER JOIN DOC_FAV_INFO DF WITH(NOLOCK) ON D.DR_ID = DF.DR_ID  
	WHERE D.DG_ID = @DoctorGroupId  AND D.DR_ENABLED = 1  AND loginlock = 0 AND lowusage_lock = 0 
	AND (D.billing_enabled=0 or (D.billing_enabled=1 
	AND D.billingDate > getdate()))  
	AND D.PRESCRIBING_AUTHORITY >= 3 order by dr_first_name,DR_LAST_NAME
	
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
