SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Nambi
-- Create date: 19-OCT-2017
-- Description:	Search Prescriptions to Map Fill
-- =============================================
CREATE PROCEDURE [erx].[SearchPrescriptionsToLinkFillStatus]
	@PatientId BIGINT
AS
BEGIN
	SELECT P.PRES_ID, P.PRES_APPROVED_DATE, PD.DRUG_NAME, PD.pd_id
	FROM PRESCRIPTIONS P  WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID   
	INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
	LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID  
	AND PAM.PA_ID = PT.PA_ID   
	WHERE PT.PA_ID = @PatientId AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL
	
	UNION
	 
	SELECT P.PRES_ID, P.PRES_APPROVED_DATE, PD.DRUG_NAME, PD.pd_id
	FROM PRESCRIPTIONS_ARCHIVE P  WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID   
	INNER JOIN PRESCRIPTION_DETAILS_ARCHIVE PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
	LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID  
	AND PAM.PA_ID = PT.PA_ID   
	WHERE PT.PA_ID = @PatientId AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
