SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Ganeshan
-- Create date: 2007/05/18
-- Description:	Fetch the patient history based on parameters
-- =============================================
CREATE PROCEDURE [dbo].[FetchPatientHistoryASP]
	@pa_id int, @num_months int,  @drugname varchar(255), @bActiveMedFilter bit, @bDischargeFilter bit
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	-- Check if active meds are filtered
	IF @bActiveMedFilter = 1
		BEGIN
			-- Check if we need to remove discharged prescriptions
			IF @bDischargeFilter = 1 
				BEGIN
				    SELECT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, 
					PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,
					PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, 
					DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
					PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, 
					PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,  
					PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD, 
					CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED 
					FROM PRESCRIPTIONS P  WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
					INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
					INNER JOIN DOCTORS DR  WITH(NOLOCK) ON P.DR_ID = DR.DR_ID 
					LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK)  ON P.PHARM_ID = PH.PHARM_ID 
					LEFT OUTER JOIN VWDIAGNOSIS D WITH(NOLOCK)  ON PD.ICD9 = D.ICD9 
					LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID
					LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
					AND PAM.PA_ID = PT.PA_ID
					WHERE PT.PA_ID = @pa_id  AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL AND P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE())  AND 
					PD.DRUG_NAME LIKE  @drugname  and PAM.DRUG_ID is not null  and HISTORY_ENABLED = 1  
					ORDER BY P.PRES_ID DESC, PRES_APPROVED_DATE	DESC
				END
			ELSE
				BEGIN
					SELECT DISTINCT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, 
					PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,
					PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, 
					DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
					PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, 
					PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,discharge_desc,discharge_date,discharge_dr_id,
					PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD, 
					CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED 
					FROM PRESCRIPTIONS P WITH(NOLOCK)  INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
					INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
					INNER JOIN DOCTORS DR WITH(NOLOCK)  ON P.DR_ID = DR.DR_ID 
					LEFT OUTER JOIN PHARMACIES PH  WITH(NOLOCK) ON P.PHARM_ID = PH.PHARM_ID 
					LEFT OUTER JOIN VWDIAGNOSIS D WITH(NOLOCK)  ON PD.ICD9 = D.ICD9 
					LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID
					LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
					AND PAM.PA_ID = PT.PA_ID
					WHERE PT.PA_ID = @pa_id AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS					NOT NULL AND P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE())					AND	PD.DRUG_NAME LIKE  @drugname  and PAM.DRUG_ID is not null
					ORDER BY P.PRES_ID DESC, PRES_APPROVED_DATE	DESC				
				END
		END
	ELSE
		BEGIN
			IF @bDischargeFilter = 1 
				BEGIN
				    SELECT DISTINCT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, 
					PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,
					PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, 
					DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
					PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, 
					PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,  
					PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD, 
					CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED 
					FROM PRESCRIPTIONS P WITH(NOLOCK)  INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
					INNER JOIN PRESCRIPTION_DETAILS PD  WITH(NOLOCK) ON P.PRES_ID = PD.PRES_ID 
					INNER JOIN DOCTORS DR WITH(NOLOCK)  ON P.DR_ID = DR.DR_ID 
					LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK)  ON P.PHARM_ID = PH.PHARM_ID 
					LEFT OUTER JOIN VWDIAGNOSIS D  WITH(NOLOCK) ON PD.ICD9 = D.ICD9 
					LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID
					LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
					AND PAM.PA_ID = PT.PA_ID
					WHERE PT.PA_ID = @pa_id AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE						IS NOT NULL AND
					P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE())  AND 
					PD.DRUG_NAME LIKE  @drugname   and HISTORY_ENABLED = 1  
					ORDER BY P.PRES_ID DESC, PRES_APPROVED_DATE	DESC
				END
			ELSE
				BEGIN
					SELECT DISTINCT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, 
					PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,
					PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, 
					DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
					PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, 
					PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,discharge_desc,discharge_date,discharge_dr_id,
					PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD, 
					CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED 
					FROM PRESCRIPTIONS P WITH(NOLOCK)  INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
					INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
					INNER JOIN DOCTORS DR WITH(NOLOCK)  ON P.DR_ID = DR.DR_ID 
					LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK)  ON P.PHARM_ID = PH.PHARM_ID 
					LEFT OUTER JOIN VWDIAGNOSIS D WITH(NOLOCK)  ON PD.ICD9 = D.ICD9 
					LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID
					LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
					AND PAM.PA_ID = PT.PA_ID
					WHERE PT.PA_ID = @pa_id  AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS					NOT NULL AND
					P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE())  AND 
					PD.DRUG_NAME LIKE  @drugname  
					ORDER BY P.PRES_ID DESC, PRES_APPROVED_DATE	DESC				
				END
		END
	RETURN
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
