SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Ganeshan
-- Create date: 2007/07/30
-- Description:	Fetches the active med list with details
-- =============================================
CREATE PROCEDURE [dbo].[FetchActiveMedDetailsASP]	
	@PA_ID int, @num_months int, @bsingledosage bit = 0 
AS
BEGIN	
	SET NOCOUNT ON;

IF @bsingledosage = 1
BEGIN
    SELECT DISTINCT  R.MED_MEDID_DESC, R.MEDID, R.MED_NAME,PAM.DATE_ADDED, PAM.COMPOUND,DR.DR_FIRST_NAME AD_FNAME, DR.DR_LAST_NAME AD_LNAME, S.* FROM PATIENT_ACTIVE_MEDS PAM LEFT OUTER JOIN RNMMIDNDC R ON PAM.DRUG_ID = R.MEDID INNER JOIN DOCTORS DR ON PAM.ADDED_BY_DR_ID = DR.DR_ID LEFT OUTER JOIN 
(
SELECT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,  
PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD
FROM PRESCRIPTIONS P WITH(NOLOCK) INNER JOIN PATIENTS PT ON P.PA_ID = PT.PA_ID  
 INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK) ON P.PRES_ID = PD.PRES_ID 
 INNER JOIN DOCTORS DR ON P.DR_ID = DR.DR_ID 
 LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK) ON P.PHARM_ID = PH.PHARM_ID 
 LEFT OUTER JOIN VWDIAGNOSIS D ON PD.ICD9 = D.ICD9 
 LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK) ON PD.PD_ID = PTS.PD_ID
 LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK) ON PD.DDID = PAM.DRUG_ID  AND PAM.PA_ID = PT.PA_ID WHERE P.PRES_ID IN (
SELECT MAX(P.PRES_ID) PRESIDS FROM PRESCRIPTIONS P WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK) ON P.PA_ID =
PT.PA_ID INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK) ON P.PRES_ID = PD.PRES_ID WHERE PT.PA_ID = @PA_ID  AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL AND HISTORY_ENABLED = 1 AND P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE())
GROUP BY PD.DDID
)
 ) S ON PAM.DRUG_ID = S.DDID  WHERE PAM.PA_ID = @PA_ID ORDER BY R.MED_MEDID_DESC, S.PRES_ID DESC

END
ELSE
BEGIN
    SELECT DISTINCT  R.MED_MEDID_DESC, R.MEDID,R.MED_NAME, PAM.DATE_ADDED, PAM.COMPOUND,DR.DR_FIRST_NAME AD_FNAME, DR.DR_LAST_NAME AD_LNAME, S.* FROM PATIENT_ACTIVE_MEDS PAM LEFT OUTER JOIN RNMMIDNDC R ON PAM.DRUG_ID = R.MEDID INNER JOIN DOCTORS DR ON PAM.ADDED_BY_DR_ID = DR.DR_ID LEFT OUTER JOIN 
(
SELECT P.PRES_ID, PD.PD_ID, P.PRES_APPROVED_DATE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC, PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.PRN_DESCRIPTION, PD.ICD9,PD.DDID, PD.COMMENTS, PD.COMPOUND, PD.HISTORY_ENABLED, D.DESCRIPTION ICD9_DESC, DR.DR_FIRST_NAME, DR.DR_LAST_NAME, PT.PA_FIRST, PT.PA_LAST, 
PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY, PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,  
PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD
FROM PRESCRIPTIONS P WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK) ON P.PA_ID = PT.PA_ID  
 INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK) ON P.PRES_ID = PD.PRES_ID 
 INNER JOIN DOCTORS DR WITH(NOLOCK) ON P.DR_ID = DR.DR_ID 
 LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK) ON P.PHARM_ID = PH.PHARM_ID 
 LEFT OUTER JOIN VWDIAGNOSIS D ON PD.ICD9 = D.ICD9 
 LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK) ON PD.PD_ID = PTS.PD_ID
 LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK) ON PD.DDID = PAM.DRUG_ID  AND PAM.PA_ID = PT.PA_ID WHERE PT.PA_ID = @PA_ID  AND P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL AND HISTORY_ENABLED = 1 AND P.PRES_APPROVED_DATE > DATEADD(MM, -@num_months ,GETDATE()) ) S ON PAM.DRUG_ID = S.DDID  WHERE PAM.PA_ID = @PA_ID ORDER BY R.MED_MEDID_DESC, S.PRES_ID DESC
END


END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
