SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author		: Rasheed
-- Create date	: 2016/10/Oct
-- Description	: Fetch the patient history based on parameters
-- =============================================
CREATE PROCEDURE [dbo].[FetchPatientMedicationOrders]
	@pa_id int
AS
BEGIN
	( SELECT P.PRES_ID, P.PRES_APPROVED_DATE AS PRES_START_DATE, P.PRES_END_DATE,P.PRIM_DR_ID,PD.PD_ID, P.PRES_APPROVED_DATE, P.PRES_PRESCRIPTION_TYPE,  PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC,
	PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.drug_indication PRN_DESCRIPTION, PD.ICD9,PD.CANCEL_STATUS,PD.CANCEL_STATUS_TEXT,
	PD.DDID, PD.days_supply, PD.COMMENTS, case when AD.IS_ACTIVE IS NULL THEN 1 ELSE AD.IS_ACTIVE END IS_ACTIVE ,PD.discharge_date, PD.discharge_desc, PD.discharge_dr_id, PD.COMPOUND, PD.HISTORY_ENABLED, D.ICD9CM_DESC100 ICD9_DESC,
	DR.DR_ID,DR.DR_FIRST_NAME, DR.DR_LAST_NAME,DR.NPI, PT.PA_FIRST, PT.PA_LAST,
	PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY,
	PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,discharge_desc,discharge_date,discharge_dr_id,
	PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD,PTS.cancel_req_response_date,PTS.cancel_req_response_type,PTS.cancel_req_response_text,
	CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED
	,CASE WHEN P.PRES_ID IS NULL THEN 0 ELSE 1 END  RX_TYPE 
	,hdr.hospice_drug_relatedness_id,hdr.Code,hdr.Description,vwGCN.GCN_SEQNO
	FROM PRESCRIPTIONS P  WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
	INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
	INNER JOIN DOCTORS DR  WITH(NOLOCK) ON P.DR_ID = DR.DR_ID 
	LEFT OUTER JOIN ACTIVE_DRUGS AD ON PD.DDID = AD.MEDID
	LEFT OUTER JOIN vwMedGCN vwGCN WITH(NOLOCK) ON vwGCN.MEDID = PD.DDID
	LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK)  ON P.PHARM_ID = PH.PHARM_ID
	LEFT OUTER JOIN RFMLINM0 D ON PD.ICD9 = D.ICD9CM
	LEFT OUTER JOIN prescription_status PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID 
	LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
	AND PAM.PA_ID = PT.PA_ID 
	LEFT OUTER JOIN hospice_drug_relatedness hdr WITH(NOLOCK) ON pd.hospice_drug_relatedness_id = hdr.hospice_drug_relatedness_id
	WHERE PT.PA_ID = @pa_id AND 
	P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL 
	AND P.PRES_APPROVED_DATE IS NOT NULL  
	--and HISTORY_ENABLED != 1

	UNION
	SELECT P.PRES_ID, P.PRES_APPROVED_DATE AS PRES_START_DATE, P.PRES_END_DATE,P.PRIM_DR_ID,PD.PD_ID, P.PRES_APPROVED_DATE,P.PRES_PRESCRIPTION_TYPE,   PD.DRUG_NAME, PD.DOSAGE, PD.USE_GENERIC,
	PD.NUMB_REFILLS, PD.DURATION_AMOUNT, PD.DURATION_UNIT, PD.PRN, PD.drug_indication PRN_DESCRIPTION, PD.ICD9,PD.CANCEL_STATUS,PD.CANCEL_STATUS_TEXT,
	PD.DDID, PD.days_supply, PD.COMMENTS, case when AD.IS_ACTIVE IS NULL THEN 1 ELSE AD.IS_ACTIVE END IS_ACTIVE,PD.discharge_date, PD.discharge_desc, PD.discharge_dr_id, PD.COMPOUND, PD.HISTORY_ENABLED, D.ICD9CM_DESC100 ICD9_DESC,
	DR.DR_ID,DR.DR_FIRST_NAME, DR.DR_LAST_NAME,DR.NPI, PT.PA_FIRST, PT.PA_LAST,
	PH.PHARM_ID, PH.PHARM_COMPANY_NAME, PH.PHARM_ADDRESS1, PH.PHARM_ADDRESS2, PH.PHARM_CITY,
	PH.PHARM_STATE, PH.PHARM_ZIP, PH.PHARM_PHONE, PH.PHARM_FAX,discharge_desc,discharge_date,discharge_dr_id,
	PTS.RESPONSE_TYPE, PTS.RESPONSE_TEXT, PTS.RESPONSE_DATE, PTS.DELIVERY_METHOD,PTS.cancel_req_response_date,PTS.cancel_req_response_type,PTS.cancel_req_response_text,
	CASE WHEN PAM.DRUG_ID IS NULL THEN 0 ELSE 1 END ACTIVE_MED,CASE WHEN P.PRES_ID IS NULL THEN 0 ELSE 1 END  RX_TYPE
	,hdr.hospice_drug_relatedness_id,hdr.Code,hdr.Description,vwGCN.GCN_SEQNO
	FROM PRESCRIPTIONS_ARCHIVE P  WITH(NOLOCK) INNER JOIN PATIENTS PT WITH(NOLOCK)  ON P.PA_ID = PT.PA_ID  
	INNER JOIN PRESCRIPTION_DETAILS_ARCHIVE PD WITH(NOLOCK)  ON P.PRES_ID = PD.PRES_ID 
	INNER JOIN DOCTORS DR  WITH(NOLOCK) ON P.DR_ID = DR.DR_ID  
	LEFT OUTER JOIN ACTIVE_DRUGS AD ON PD.DDID = AD.MEDID 
	LEFT OUTER JOIN vwMedGCN vwGCN WITH(NOLOCK) ON vwGCN.MEDID = PD.DDID
	LEFT OUTER JOIN PHARMACIES PH WITH(NOLOCK)  ON P.PHARM_ID = PH.PHARM_ID 
	LEFT OUTER JOIN RFMLINM0 D ON PD.ICD9 = D.ICD9CM 
	LEFT OUTER JOIN prescription_status_ARCHIVE PTS WITH(NOLOCK)  ON PD.PD_ID = PTS.PD_ID 
	LEFT OUTER JOIN PATIENT_ACTIVE_MEDS PAM WITH(NOLOCK)  ON PD.DDID = PAM.DRUG_ID 
	AND PAM.PA_ID = PT.PA_ID  
	LEFT OUTER JOIN hospice_drug_relatedness hdr WITH(NOLOCK) ON pd.hospice_drug_relatedness_id = hdr.hospice_drug_relatedness_id
	WHERE PT.PA_ID = @pa_id AND 
	P.PRES_VOID = 0 AND P.PRES_APPROVED_DATE IS NOT NULL
	AND P.PRES_APPROVED_DATE  IS NOT NULL
	--and HISTORY_ENABLED != 1
	)
	ORDER BY PRES_ID DESC, PRES_APPROVED_DATE	DESC

END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
