SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Rasheed
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[FetchAllDrugs]
	-- Add the parameters for the stored procedure here
	@PageIndex BIGINT = NULL, 
	@PageSize int = 1000
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	With ranked AS   --- Or you can make it a view
	(
		SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY A.MEDID) AS RowNum, 
		A.MEDID, A.MED_MEDID_DESC	DESCRIPTION,D.MED_NAME [MED NAME],A.MED_STRENGTH [MED STRENGTH],E.MED_DOSAGE_FORM_DESC	DOSAGEFORM,
		'LEVEL_'+CAST(ISNULL(A.MED_REF_DEA_CD,9) AS VARCHAR(10))	DrugLevel,
		CASE A.MED_REF_FED_LEGEND_IND WHEN 1 THEN 'enRx' WHEN 2 THEN 'enOTC' WHEN 3 THEN 'enBoth' WHEN 4 THEN 'enUnknown' ELSE 'enUnknown' END DrugType,
		F.ETC_NAME DrugClass,
		A.MED_STRENGTH_UOM [MED STRENGTH UOM (Units)], 
		CASE WHEN A.MED_REF_GEN_DRUG_NAME_CD IN (1,4) THEN 'Yes' ELSE 'No' END [Generic(Yes/No)]
		FROM  RMIID1 A WITH(NOLOCK) 
		INNER JOIN RMIDFID1 B WITH(NOLOCK) ON A.ROUTED_DOSAGE_FORM_MED_ID = B.ROUTED_DOSAGE_FORM_MED_ID
		INNER JOIN RMIRMID1 C WITH(NOLOCK) ON B.ROUTED_MED_ID = C.ROUTED_MED_ID 
		INNER JOIN RMINMID1 D WITH(NOLOCK) ON C.MED_NAME_ID = D.MED_NAME_ID 
		INNER JOIN RMIDFD1 E WITH(NOLOCK) ON B.MED_DOSAGE_FORM_ID = E.MED_DOSAGE_FORM_ID 
		INNER JOIN RNMMIDNDC F WITH(NOLOCK) ON A.MEDID=F.MEDID
		WHERE  A.Medid BETWEEN 1 AND 999998 
		 
	) AS t 
	)
	
	SELECT DISTINCT Rnk.MEDID, Rnk.DESCRIPTION,Rnk.[MED NAME],Rnk.[MED STRENGTH],Rnk.DOSAGEFORM,
		Rnk.DrugLevel,
		Rnk.DrugType,
		Rnk.DrugClass,Rnk.[MED STRENGTH UOM (Units)], 
		Rnk.[Generic(Yes/No)],
		G.EVD_EXT_VOCAB_ID RxNormCode
	FROM Ranked Rnk WITH(NOLOCK)
		LEFT OUTER JOIN (SELECT MAX(EVD_EXT_VOCAB_ID) EVD_EXT_VOCAB_ID,EVD_FDB_VOCAB_ID  
		from REVDEL0 R1 WITH(NOLOCK) 
		WHERE EVD_FDB_VOCAB_TYPE_ID=3 --AND EVD_EXT_VOCAB_TYPE_ID in (502,504,505) 
		GROUP BY EVD_FDB_VOCAB_ID
		) G ON  G.EVD_FDB_VOCAB_ID= Rnk.Medid   
		WHERE @PageIndex=1

END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
