SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [dbo].[GetRxforRefillResponse]
	@PresId int,@MEDID INT,@_supervisorId INT
AS
BEGIN
	SET NOCOUNT ON;
	IF @_supervisorId = 0
	BEGIN
		SELECT PRES.pres_id,pharm_company_name,pharm_address1,pharm_city,pharm_state,pharm_phone,pharm_zip,ncpdp_numb,
		pa_last,pa_first,pa_middle,pa_address1,pa_address2,pa_city,pa_state,pa_zip,PA_DOB,PA_sex,PA_PHONE,
		spi_id,DR_SUFFIX,dr_last_name,dr_first_name,dr_middle_initial,dr_phone,dr_address1,dr_address2,dr_city,dr_state,dr_zip,
		DG_NAME,MD.NDC,STRENGTH,MED_STRENGTH_UOM,PD.DRUG_NAME,DOSAGE,USE_GENERIC,NUMB_REFILLS,DURATION_AMOUNT,DURATION_UNIT,PD.COMMENTS,PRES.pres_approved_date,
		PRES_VOID, PRES_VOID_CODE,PRES_VOID_COMMENTS,trc_number,ctrl_number,STATUS_CODE,ref.response_type,STATUS_MSG,REF.DRUG_NAME REFDRUG,
		DRUG_FORM,DRUG_STRENGTH,DRUG_STRENGTH_UNITS,QTY1,QTY1_UNITS,QTY1_ENUM,QTY2,QTY2_UNITS,QTY2_ENUM,dosage1,dosage2,REF.days_supply,date1,
		date1_enum,date2,date2_enum,date3,date3_enum,substitution_code,refills,refills_enum,void_comments,void_code,
		comments1,comments2,comments3,'' SU_FNAME,'' SU_MI,'' SU_ADDR1,'' SU_CITY,'' SU_STATE,'' SU_ZIP FROM PRESCRIPTIONS PRES
		INNER JOIN PATIENTS PAT ON PRES.PA_ID=PAT.PA_ID INNER JOIN PRESCRIPTION_DETAILS PD ON PRES.PRES_ID=PD.PRES_ID 
		INNER JOIN PHARMACIES PHARM ON PRES.PHARM_ID=PHARM.PHARM_ID INNER JOIN REFILL_REQUESTS REF ON PRES.PRES_ID=REF.PRES_ID INNER JOIN 
		(SELECT A.medid,MAX(NDC)NDC,MAX(MED_STRENGTH)STRENGTH,MAX(MED_STRENGTH_UOM)MED_STRENGTH_UOM FROM RMIID1 A inner join RMINDC1 B on A.MEDID=B.MEDID WHERE A.MEDID= @MEDID
		GROUP BY A.MEDID)MD on PD.DDID=MD.MEDID INNER JOIN DOCTORS DR ON DR.DR_ID=PRES.DR_ID INNER JOIN DOC_GROUPS DG ON DR.DG_ID=DG.DG_ID where PRES.pres_id=@PresId
	END
	ELSE
	BEGIN
		SELECT PRES.pres_id,pharm_company_name,pharm_address1,pharm_city,pharm_state,pharm_phone,pharm_zip,ncpdp_numb,
		pa_last,pa_first,pa_middle,pa_address1,pa_address2,pa_city,pa_state,pa_zip,PA_DOB,PA_sex,PA_PHONE,
		spi_id,DR_SUFFIX,dr_last_name,dr_first_name,dr_middle_initial,dr_phone,dr_address1,dr_address2,dr_city,dr_state,dr_zip,
		DG_NAME,MD.NDC,STRENGTH,MED_STRENGTH_UOM,PD.DRUG_NAME,DOSAGE,USE_GENERIC,NUMB_REFILLS,DURATION_AMOUNT,DURATION_UNIT,PD.COMMENTS,PRES.pres_approved_date,
		PRES_VOID, PRES_VOID_CODE,PRES_VOID_COMMENTS,trc_number,ctrl_number,STATUS_CODE,ref.response_type,STATUS_MSG,REF.DRUG_NAME REFDRUG,
		DRUG_FORM,DRUG_STRENGTH,DRUG_STRENGTH_UNITS,QTY1,QTY1_UNITS,QTY1_ENUM,QTY2,QTY2_UNITS,QTY2_ENUM,dosage1,dosage2,REF.days_supply,date1,
		date1_enum,date2,date2_enum,date3,date3_enum,substitution_code,refills,refills_enum,void_comments,void_code,
		comments1,comments2,comments3,SU_FNAME,SU_MI,SU_ADDR1,SU_CITY,SU_STATE,SU_ZIP FROM PRESCRIPTIONS PRES
		INNER JOIN PATIENTS PAT ON PRES.PA_ID=PAT.PA_ID INNER JOIN PRESCRIPTION_DETAILS PD ON PRES.PRES_ID=PD.PRES_ID 
		INNER JOIN PHARMACIES PHARM ON PRES.PHARM_ID=PHARM.PHARM_ID INNER JOIN REFILL_REQUESTS REF ON PRES.PRES_ID=REF.PRES_ID INNER JOIN 
		(SELECT A.medid,MAX(NDC)NDC,MAX(MED_STRENGTH)STRENGTH,MAX(MED_STRENGTH_UOM)MED_STRENGTH_UOM FROM RMIID1 A inner join RMINDC1 B on A.MEDID=B.MEDID WHERE A.MEDID= @MEDID
		GROUP BY A.MEDID)MD on PD.DDID=MD.MEDID INNER JOIN DOCTORS DR ON DR.DR_ID=PRES.DR_ID INNER JOIN DOC_GROUPS DG ON DR.DG_ID=DG.DG_ID INNER JOIN 
		(SELECT DR_ID,DR_LAST_NAME SU_LNAME,DR_FIRST_NAME SU_FNAME,DR_MIDDLE_INITIAL SU_MI,DR_ADDRESS1 SU_ADDR1,
		DR_CITY SU_CITY,DR_STATE SU_STATE,DR_ZIP SU_ZIP FROM DOCTORS WHERE DR_ID=@_supervisorId)SUPERVISOR 
		ON PRES.AUTHORIZING_DR_ID=SUPERVISOR.DR_ID where PRES.pres_id=@PresId
	END
	Return 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
