SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Thomas Kavukat
-- Create date: 2009-02-02
-- Description:	Batch Resends faxed scripts electronically from pharmacy list in RXNTREPORTUTILS..SEMI_LIST
-- =============================================
CREATE PROCEDURE [dbo].[ResendRxErrorList]	
		@dtstartdate datetime
As
	BEGIN
	DECLARE @PRESID INT;
	DECLARE @SQL VARCHAR(2000)
	SET NOCOUNT ON;
	SET @PRESID = 0;
	SET @SQL='';
	SELECT PRES.PRES_ID INTO #temp FROM PRESCRIPTIONS PRES INNER JOIN PRESCRIPTION_DETAILS PD ON PRES.PRES_ID=PD.PRES_ID
	INNER JOIN DOCTORS DR ON DR.DR_ID=PRES.DR_ID WHERE DR.SS_ENABLE=1 AND PRES_APPROVED_DATE > @dtstartdate AND PRES_DELIVERY_METHOD=1 AND
	PHARM_ID IN (SELECT DR_ID FROM RXNTREPORTUTILS..semI_list) AND DDID NOT IN(SELECT MEDID FROM RMIID1
	WHERE MED_REF_DEA_CD>0)
	SET @PRESID = (SELECT TOP 1 PRES_ID FROM #TEMP WHERE PRES_ID > @PRESID ORDER BY PRES_ID ASC)
	WHILE	(@PRESID IS NOT NULL)
		BEGIN
			SET @SQL = 'INSERT INTO PRESCRIPTION_STATUS(PD_ID,DELIVERY_METHOD,RESPONSE_TYPE,RESPONSE_TEXT,RESPONSE_DATE,CONFIRMATION_ID,QUEUED_DATE) SELECT PD_ID,262144,NULL,NULL,NULL,NULL,GETDATE() FROM PRESCRIPTION_DETAILS WHERE PRES_ID=' + CONVERT(VARCHAR(15),@PRESID ,0)
			EXEC (@SQL)
			SET @SQL = 'INSERT INTO PRESCRIPTION_TRANSMITTALS(PRES_ID,PD_ID,QUEUED_DATE,DELIVERY_METHOD,TRANSMISSION_FLAGS,PRESCRIPTION_TYPE,SEND_DATE,RESPONSE_TYPE,RESPONSE_TEXT,RESPONSE_DATE,CONFIRMATION_ID) SELECT PRES.PRES_ID,PD_ID,getdate(),262144,0,PRES_PRESCRIPTION_TYPE,NULL,NULL,NULL,NULL,NULL FROM PRESCRIPTIONS PRES INNER JOIN PRESCRIPTION_DETAILS PD ON PRES.PRES_ID=PD.PRES_ID WHERE PD.PRES_ID=' + CONVERT(VARCHAR(15),@PRESID ,0)
			EXEC (@SQL)
			SET @SQL = 'UPDATE PRESCRIPTIONS SET PRES_DELIVERY_METHOD=262145 WHERE PRES_ID=' + CONVERT(VARCHAR(15),@PRESID ,0)
			EXEC (@SQL)
			SET @PRESID = (SELECT TOP 1 PRES_ID FROM #TEMP WHERE PRES_ID > @PRESID ORDER BY PRES_ID ASC)
		END
	END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
