SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- =============================================
-- Author:		Nambi
-- Create date: 12-SEP-2017
-- Description:	Search NDC for Drug
-- Modified By: 
-- Modified Date: 
-- =============================================
CREATE PROCEDURE [dbo].[SearchNDCForDrug]
	@pdid BIGINT
AS

BEGIN
	SELECT TOP 1 
	CASE 
		WHEN (ISNULL(RND.REPACK,0)=0 AND RND.OBSDTEC IS NULL AND ISNULL(RND.PLBLR,0)=0 AND ISNULL(RND.UD,0)=0) 
			THEN 1 
		WHEN (RND.OBSDTEC IS NULL AND ISNULL(RND.PLBLR,0)=0 AND ISNULL(RND.UD,0)=0)
			THEN 2 
		WHEN (ISNULL(RND.PLBLR,0)=0 AND ISNULL(RND.UD,0)=0)
			THEN 3
		WHEN (ISNULL(RND.UD,0)=0)
			THEN 4
		ELSE 5 END NDCRank,
	RN.NDC FROM
	RMIID1 RM WITH(NOLOCK) 
	INNER JOIN RMINDC1 RN WITH(NOLOCK) ON RM.MEDID = RN.MEDID
	INNER JOIN PRESCRIPTION_DETAILS PD WITH(NOLOCK) ON RN.MEDID=PD.ddid
	INNER JOIN RNDC14 RND WITH(NOLOCK) ON RN.NDC = RND.NDC
	WHERE PD.pd_id=@pdid
	ORDER BY NDCRank ASC
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
