SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [DBO].[STAGEII_MISSING_PATIENT_LABRESULTS]
@DR_ID INT,  
@REPORTING_START_DATE DATETIME,  
@REPORTING_END_DATE DATETIME,
@MEASURECODE VARCHAR(3)
AS   
BEGIN
WITH
 NUMERATOR_DATA AS      
 (      
  SELECT  DISTINCT MC.PA_ID AS NUMERATOR
  FROM  DBO.MUMEASURECOUNTS MC WITH(NOLOCK)      
  WHERE  1=1      
  AND MC.DR_ID = @DR_ID      
  AND MC.MEASURECODE = @MEASURECODE      
  AND MC.DATEADDED BETWEEN @REPORTING_START_DATE AND @REPORTING_END_DATE      
  AND MC.ISNUMERATOR = 1           
 ),      
 DENOMINATOR_DATA AS      
 (         
  SELECT DISTINCT PA_ID AS DENOMINATOR FROM(      
   SELECT  M.PA_ID, M.DR_ID,ROW_NUMBER() OVER (PARTITION BY M.ID ORDER BY M.ID) AS PAT_RANK       
   FROM  DBO.PATIENT_LAB_ORDERS O       
   INNER  JOIN DBO.MUMEASURECOUNTS M ON O.PA_ID = M.PA_ID       
   AND M.ISDENOMINATOR=1       
   AND O.ISACTIVE=1       
   AND M.MEASURECODE=@MEASURECODE      
   AND O.ORDER_DATE BETWEEN @REPORTING_START_DATE       
   AND @REPORTING_END_DATE       
   AND M.DR_ID = @DR_ID      
  )AS SUBQUERY      
  WHERE 1=1 AND  PAT_RANK = 1             
 )      

 SELECT  DISTINCT P.PA_ID AS PATIENT,P.PA_FIRST AS FIRSTNAME, P.PA_LAST AS LASTNAME, P.PA_DOB AS DATEOFBIRTH, P.PA_SEX AS SEX,    
	P.PA_ADDRESS1 AS ADDRESS1, P.PA_CITY AS CITY,P.PA_STATE AS STATE, P.PA_ZIP AS ZIPCODE,P.PA_SSN AS CHART   
	FROM PATIENTS P  WITH(NOLOCK) 
	INNER JOIN DENOMINATOR_DATA DD ON P.PA_ID = DD.DENOMINATOR
	LEFT OUTER JOIN NUMERATOR_DATA ND ON P.PA_ID = ND.NUMERATOR
	WHERE 1=1
    AND ND.NUMERATOR  IS NULL  
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
