SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [dbo].[STAGEII_MISSING_PATIENT_SMOKINGSTATUS]
@DR_ID INT,  
@REPORTING_START_DATE DATETIME,  
@REPORTING_END_DATE DATETIME

AS   
BEGIN
WITH
PATIENT_ENCOUNTERS AS      
 (      
  SELECT  ENC.PATIENT_ID, 
  MAX(ENC.ENC_DATE) AS LAST_ENCOUNTER_DATE      
  FROM  DBO.ENCHANCED_ENCOUNTER  ENC  WITH(NOLOCK)      
  INNER JOIN DBO.PATIENTS    PAT  WITH(NOLOCK) ON PAT.PA_ID  = ENC.PATIENT_ID      
  WHERE  1=1      
  AND   ENC.DR_ID  = @DR_ID      
  AND   ENC.ENC_DATE BETWEEN @REPORTING_START_DATE AND @REPORTING_END_DATE 
  and enc.issigned = 1     
  GROUP BY ENC.PATIENT_ID    
 ),  
       
 PATIENT_FLAG_DATA AS      
 (      
  SELECT  PAT.PA_ID      
  FROM  PATIENT_ENCOUNTERS   PEN  WITH(NOLOCK)      
  INNER JOIN DBO.PATIENTS    PAT  WITH(NOLOCK) ON PAT.PA_ID  = PEN.PATIENT_ID      
  INNER JOIN DBO.PATIENT_FLAG_DETAILS PFD  WITH(NOLOCK) ON PFD.PA_ID  = PEN.PATIENT_ID      
  WHERE  1=1      
  AND   PFD.FLAG_ID     IN  (-1,-2,-3,-4,-5,5,6,7) 
  And   DATEDIFF(YEAR, PAT.PA_DOB, PEN.LAST_ENCOUNTER_DATE) >= 13     
  GROUP BY PAT.PA_ID      
 )  
 
 SELECT  DISTINCT P.PA_ID AS PATIENT,
	P.PA_FIRST AS FIRSTNAME, 
	P.PA_LAST AS LASTNAME, 
	P.PA_DOB AS DATEOFBIRTH, 
	P.PA_SEX AS SEX,  
    P.PA_ADDRESS1 AS ADDRESS1, 
    P.PA_CITY AS CITY,  
    P.PA_STATE AS STATE, 
    P.PA_ZIP AS ZIPCODE,
	P.PA_SSN As CHART 
    FROM dbo.PATIENTS P  with(nolock) 
    INNER JOIN PATIENT_ENCOUNTERS pe ON P.PA_ID = pe.PATIENT_ID   
    LEFT OUTER JOIN PATIENT_FLAG_DATA pfd on p.pa_id = pfd.pa_id
    WHERE 1=1 
    AND pfd.pa_id IS NULL 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
