SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [support].[CheckDrugExists]
/* 
	EXEC [support].[CheckDrugExists] 
	@NDC = '<Enter NDC here>',				-- Optional
	@RxNorm = '<Enter RxNorm code here>'	-- Optional
	GO
*/
@NDC VARCHAR(20) = NULL, 
@RxNorm VARCHAR(100)=NULL 
AS
	IF @NDC IS NOT NULL
	BEGIN 
		SELECT RM.MEDID RxNTDrugId,RNM.MED_NAME_ID DrugName,RN.NDC
		FROM RMINDC1 RN with(nolock)
		INNER JOIN RMIID1 RM WITH(NOLOCK) ON RM.MEDID = RN.MEDID
		LEFT OUTER JOIN RNMMIDNDC RNM WITH(NOLOCK) on RN.NDC = RNM.NDC		
		WHERE RN.NDC  LIKE @NDC+'%'
	END
	
	IF @RxNorm IS NOT NULL
	BEGIN
		select RNM.MEDID RxNTDrugId,MED_NAME_ID DrugName,NDC,EVD_EXT_VOCAB_ID RxNorm 
		from 
		RNMMIDNDC RNM WITH(NOLOCK)  
		INNER JOIN REVDEL0 R1 WITH(NOLOCK) ON RNM.MEDID = R1.EVD_FDB_VOCAB_ID inner join REVDVT0 R2 WITH(NOLOCK) on 
		R1.EVD_EXT_VOCAB_TYPE_ID=R2.EVD_VOCAB_TYPE_ID INNER JOIN RMIID1 R3 ON EVD_FDB_VOCAB_ID = R3.MEDID where 
		EVD_FDB_VOCAB_TYPE_ID=3 AND EVD_EXT_VOCAB_TYPE_ID in (502,504,505)   AND R3.med_ref_gen_drug_name_cd =  2
		AND EVD_EXT_VOCAB_ID  LIKE @RxNorm+'%'
		UNION
		SELECT RNM.MEDID RxNTDrugId,MED_NAME_ID DrugName,NDC,EVD_EXT_VOCAB_ID RxNorm 
		from 
		RNMMIDNDC RNM WITH(NOLOCK) 
		INNER JOIN REVDEL0 R1 WITH(NOLOCK) ON RNM.MEDID = R1.EVD_FDB_VOCAB_ID inner join REVDVT0 R2 WITH(NOLOCK) on 
		R1.EVD_EXT_VOCAB_TYPE_ID=R2.EVD_VOCAB_TYPE_ID where EVD_FDB_VOCAB_TYPE_ID=3 AND EVD_EXT_VOCAB_TYPE_ID in (501,503)
		AND EVD_EXT_VOCAB_ID  LIKE @RxNorm+'%'
	END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
