ALTER TABLE [dbo].[PARTNER_ACCOUNTS] ADD CONSTRAINT [DF_PARTNER_ACCOUNTS_ENABLED] DEFAULT ((0)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[PARTNER_ACCOUNTS] ADD CONSTRAINT [DF_PARTNER_ACCOUNTS_admin_company_id] DEFAULT ((0)) FOR [admin_company_id]
GO
