ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_OFFSET] DEFAULT ((-1)) FOR [OFFSET_HR]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_OFFSET_MI] DEFAULT ((0)) FOR [OFFSET_MI]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_DST_OFFSET] DEFAULT ((-1)) FOR [DST_OFFSET_HR]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_DST_OFFSET_MI] DEFAULT ((0)) FOR [DST_OFFSET_MI]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_DST_EFF_DT] DEFAULT ('03210200') FOR [DST_EFF_DT]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_DST_END_DT] DEFAULT ('11110200') FOR [DST_END_DT]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_EFF_DT] DEFAULT (getutcdate()) FOR [EFF_DT]
GO
ALTER TABLE [dbo].[TIME_ZONES] ADD CONSTRAINT [DF_TIME_ZONES_END_DT] DEFAULT ('12/31/9999') FOR [END_DT]
GO
